#!/usr/bin/env tsx
/*
 * Generates the request media-type table from `openapi.yaml`: for every operation that declares a
 * `requestBody`, the content types it accepts. The 415 guard
 * (`src/infrastructure/http/middlewares/content-type.ts`) reads it, so a body in a type the
 * contract does not declare is refused instead of arriving as an empty `{}`. Each row carries its
 * path matcher as a regex literal, so the guard compiles nothing at boot.
 *
 * Backend-only: the frontend has no server to guard. Written beside the other generated contract
 * files under `api/`, which `npm run gen:api` rebuilds from scratch.
 *
 * `--check` writes nothing and exits 1 on a mismatch (the shared `writeOrCheck` helper).
 *
 * Usage: tsx scripts/contracts/generate-request-content-types.ts --out <path> [--check]
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeOrCheck } from './generated-file';
import { parse } from 'yaml';

/** The slice of an OpenAPI operation this generator reads. */
interface OperationObject {
    requestBody?: { content?: Record<string, unknown> };
}

/** The slice of the bundled document this generator reads. */
interface OpenApiDocument {
    paths: Record<string, Record<string, OperationObject | undefined>>;
}

/** The HTTP methods whose body the guard checks. `get` and `head` carry none by contract. */
const BODY_METHODS = ['post', 'put', 'patch', 'delete'] as const;

/** The repo root. `import.meta.url` rather than `__dirname`: this script runs as ESM. */
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

/** The bundled root contract this generator reads. */
const INPUT = path.resolve(ROOT, 'openapi.yaml');

/*
 * Reads the required `--out` argument.
 *
 * @returns Absolute path of the file to generate.
 */
const resolveOutputPath = (): string => {
    const flagIndex = process.argv.indexOf('--out');
    const value = flagIndex === -1 ? undefined : process.argv[flagIndex + 1];
    if (!value) {
        console.error('Missing required argument: --out <path>');
        process.exit(1);
    }
    return path.resolve(ROOT, value);
};

/** Absolute path of the file to generate, from `--out`. */
const OUTPUT = resolveOutputPath();

/**
 * The bundled contract, parsed. `parse` is the `yaml` package's YAML 1.2 loader; the `as` narrows
 * its `any` to the slice this file reads. https://eemeli.org/yaml/#yaml-parse
 */
const document = parse(readFileSync(INPUT, 'utf8')) as OpenApiDocument;

/**
 * Compiles a contract path template into the text of a regex literal, so the guard never builds a
 * matcher at boot: `/products/{id}/restore` becomes `/^\/products\/[^/]+\/restore$/`.
 *
 * @param template - a contract path such as `/products/{id}/restore`
 * @returns the literal's source text, and how many `{param}` segments the template has
 */
const compileTemplate = (template: string): { literal: string; parameterCount: number } => {
    const segments = template.split('/');
    const source = segments
        .map((segment) =>
            segment.startsWith('{')
                ? '[^/]+'
                : segment.replaceAll(/[$()*+.?[\\\]^{|}]/g, String.raw`\$&`)
        )
        .join(String.raw`\/`);
    return {
        literal: `/^${source}$/`,
        parameterCount: segments.filter((segment) => segment.startsWith('{')).length
    };
};

/*
 * One row per operation that declares a body. Fewest parameters first, so a static segment
 * (`/products/search`) is tried before `/products/{id}`; ties by key, so a regeneration is a
 * stable diff.
 *
 * @returns the rows as source text.
 */
const renderRows = (): string[] =>
    Object.entries(document.paths)
        .flatMap(([route, operations]) =>
            BODY_METHODS.flatMap((method) => {
                const types = Object.keys(operations[method]?.requestBody?.content ?? {});
                if (types.length === 0) return [];
                const { literal, parameterCount } = compileTemplate(route);
                return [
                    {
                        key: `${method.toUpperCase()} ${route}`,
                        parameterCount,
                        text: `    { method: ${JSON.stringify(method.toUpperCase())}, pattern: ${literal}, parameterCount: ${String(parameterCount)}, types: ${JSON.stringify(types)} },`
                    }
                ];
            })
        )
        .toSorted(
            (left, right) =>
                left.parameterCount - right.parameterCount || left.key.localeCompare(right.key)
        )
        .map((row) => row.text);

/** The whole generated file's text. */
const output =
    '// Code generated by `npm run gen:api`. DO NOT EDIT.\n' +
    '/*\n' +
    ' * GENERATED — do not edit manually.\n' +
    ' * Source: openapi.yaml  |  Regenerate: npm run gen:api\n' +
    ' */\n\n' +
    '/** One operation that declares a request body, ready to match against a request. */\n' +
    'export interface RequestContentType {\n' +
    '    /** Upper-case HTTP method. */\n' +
    '    method: string;\n' +
    "    /** Matches the request path of the operation's contract path template. */\n" +
    '    pattern: RegExp;\n' +
    '    /** How many `{param}` segments the template has — fewer means more specific. */\n' +
    '    parameterCount: number;\n' +
    "    /** The media types the contract declares for the operation's body. */\n" +
    '    types: readonly string[];\n' +
    '}\n\n' +
    '/** Every operation that declares a request body, fewest path parameters first. */\n' +
    `export const REQUEST_CONTENT_TYPES: readonly RequestContentType[] = [\n${renderRows().join('\n')}\n];\n`;

// Write the file, or under `--check` compare it with what is on disk.
writeOrCheck(OUTPUT, output, 'openapi.yaml');
