import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';
import configPrettier from 'eslint-config-prettier';
import pluginUnicorn from 'eslint-plugin-unicorn';
import pluginBoundaries from 'eslint-plugin-boundaries';
import comments from '@eslint-community/eslint-plugin-eslint-comments/configs';
import { globalIgnores } from 'eslint/config';
import path from 'node:path';
import localRules from './eslint/rules';

/**
 * `x as unknown as T` — the double cast that erases the type system's objection instead of
 * answering it — is banned everywhere, tests included. `no-restricted-syntax` does not merge
 * across configs (the nearest match REPLACES the list), so every block that configures that
 * rule spreads this in, or the ban would silently lift for exactly those files.
 */
const bannedDoubleCasts = [
    {
        selector: 'TSAsExpression > TSAsExpression[typeAnnotation.type="TSUnknownKeyword"]',
        message:
            '`as unknown as T` erases the type error instead of answering it. Type the source honestly (`.lean<T>()`, a typed factory) — or, for a hand-built test stub, use the one sanctioned seam: `asStub<T>()` from tests/support/stub.ts.'
    },
    {
        selector: 'TSAsExpression > TSAsExpression[typeAnnotation.type="TSAnyKeyword"]',
        message:
            '`as any as T` erases the type error instead of answering it. Type the source honestly — or, for a hand-built test stub, use `asStub<T>()` from tests/support/stub.ts.'
    }
];

export default tseslint.config(
    /**
     * Excluded files — GENERATED OR FOREIGN ONLY.
     *
     * The bar for an entry here: linting it is impossible or meaningless, not merely
     * inconvenient. Tool configs, migrations and CLI scripts used to sit in this list because
     * they fall outside the `tsconfig` project; they are linted now, through the scoped blocks
     * near the bottom that switch off the type-aware program instead of the whole linter.
     */
    globalIgnores([
        /*
         * The k6 load scenarios. They are JavaScript, but not this project's JavaScript: they run
         * inside the k6 Go runtime and import from `k6/http`, a module specifier that resolves
         * only there. Linting them means resolving imports that cannot resolve and enforcing
         * rules written for the app on a file the app never loads.
         */
        'k6/**',
        '**/node_modules/**',
        '**/dist/**',
        '**/coverage/**',
        // The built docs site and its build cache; the authored source under `docs/` is markdown,
        // and the VitePress config is linted through the tool-config block below.
        'docs/.vitepress/dist/**',
        'docs/.vitepress/cache/**',
        /*
         * Stryker copies the whole project here per run. Without this, `npm run lint` fails with
         * one parser error per generated file the moment a mutation run is in flight — or forever,
         * if a crashed run left the directory behind — because the copies sit outside the
         * `tsconfig` project `parserOptions.project` resolves against. `jest.config.js` ignores
         * the same path for the same reason; see the note in `stryker.config.json`.
         */
        '.stryker-tmp/**',
        // Per-run in-memory Mongo data directories — see tests/support/global-setup.ts
        '.tmp/**',
        // Generated by orval — do not lint generated output
        'api/**',
        // Generated by `npm run gen:asyncapi`, same as `api` above
        'src/types/asyncapi.generated.ts',
        '.prism/**',
        '.dev/**'
    ]),

    /**
     * Base eslint + typescript presets.
     *
     * The three type-checked tiers are the point of setting `parserOptions.project` at all:
     * the type information is already being built for the parser, so the rules that consume it
     * (`no-floating-promises`, `no-misused-promises`, `no-unnecessary-condition`, …) cost almost
     * nothing extra and catch the bugs a syntax-only pass cannot see.
     */
    js.configs.recommended,
    ...tseslint.configs.strictTypeChecked,
    ...tseslint.configs.stylisticTypeChecked,

    /**
     * Unicorn plugin
     */
    pluginUnicorn.configs['flat/recommended'],

    /**
     * Every `eslint-disable` must say why. The two project-local rules and the `TryStatement`
     * restriction below are deliberately annoying; a bare disable comment converts "deliberately
     * annoying" into "silently ignored", and the description requirement is what keeps each
     * exemption an argument instead of a shrug.
     */
    comments.recommended,

    /**
     * All global rules
     */
    {
        languageOptions: {
            parserOptions: {
                project: path.resolve('./tsconfig.json')
            },
            // A server: `process`, `Buffer` and friends are the environment, `window` is not.
            globals: {
                ...globals.node
            },
            ecmaVersion: 'latest',
            sourceType: 'module'
        },

        plugins: {
            local: { rules: localRules },
            boundaries: pluginBoundaries
        },

        rules: {
            'no-console': 'warn',
            'no-debugger': 'warn',
            'no-restricted-syntax': ['error', ...bannedDoubleCasts],
            /*
             * `!` is allowed where a value has ALREADY been proven present by something the
             * compiler cannot follow — the `isAdmin` middleware guaranteeing `request.authContext`,
             * a `.some(x => !x)` guard proving the `.map` below it finds no `undefined`. The
             * alternative is a cast, which `no-restricted-syntax` above bans for being the same
             * claim in a form that also silences type errors. The claim itself is the same either
             * way; `!` is the spelling that stays narrow.
             */
            '@typescript-eslint/no-non-null-assertion': 'off',
            '@typescript-eslint/use-unknown-in-catch-callback-variable': 'off',
            'no-nested-ternary': 'off',
            'unicorn/no-nested-ternary': 'off',
            'unicorn/prefer-top-level-await': 'off',

            /*
             * Four unicorn rules turned off rather than exempted seventeen times.
             *
             * Each was being disabled inline wherever it fired, which is the signal that the rule
             * disagrees with the stack rather than with the code:
             *
             *   no-null            — Mongo and Express both use `null` with meaning. `deletedAt:
             *                        null` is not `undefined`, and `res.json(null)` is a body.
             *   no-useless-undefined — an explicit `return undefined` is this codebase's stated
             *                        convention for "looked, found nothing" (see the union-return
             *                        note in `infrastructure/http/response.ts`).
             *   no-process-exit    — this is a server with a shutdown path; `server-lifecycle.ts`
             *                        exits deliberately, four times, after draining.
             *   prefer-module      — it flags every `__dirname`, and `__dirname` is how this
             *                        stack actually runs: tsx and jest both execute the TS as
             *                        CommonJS, so `import.meta.dirname` would be `undefined` at
             *                        runtime. Fifty findings, every one a rename into a crash.
             *
             * A rule that needs six exemptions is not catching bugs, it is collecting signatures.
             */
            'unicorn/no-null': 'off',
            'unicorn/no-useless-undefined': 'off',
            'unicorn/no-process-exit': 'off',
            'unicorn/prefer-module': 'off',

            '@typescript-eslint/restrict-plus-operands': [
                'error',
                {
                    allowNumberAndString: true
                }
            ],

            /*
             * strictTypeChecked's default rejects numbers in template literals, which turns every
             * log line and metric label into a `String()` ceremony. Numbers stringify one way;
             * the risk the rule guards against is objects and `undefined`, which stay banned.
             */
            '@typescript-eslint/restrict-template-expressions': [
                'error',
                {
                    allowNumber: true
                }
            ],

            /*
             * `value || fallback` on a STRING is this codebase's idiom for "empty means unset" —
             * the `host` npm script deliberately sets `NODE_DB_URI=` to blank, and a blank
             * feedback name falls back to translated copy. For everything non-string, `??` stays
             * the required spelling.
             */
            '@typescript-eslint/prefer-nullish-coalescing': [
                'error',
                {
                    ignorePrimitives: { string: true }
                }
            ],

            /*
             * `(request, response) => response.json(body)` is the shape of half the controllers
             * in an Express app; the "confusing" void return is Express's own idiom, and the
             * fixer's `{ response.json(body); }` says nothing the shorthand does not.
             */
            '@typescript-eslint/no-confusing-void-expression': [
                'error',
                {
                    ignoreArrowShorthand: true
                }
            ],

            /*
             * An underscore prefix is the deliberate spelling of "unused on purpose" — a handler
             * signature that must take `(error, request, response, next)` to be an error handler,
             * a destructuring that drops a key. Everything unprefixed stays an error.
             */
            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_'
                }
            ],

            /*
             * `const { name } = user` over `const name = user.name` — one read of the object per
             * binding site instead of a scatter of member accesses. Only for declarations that
             * read a property into a same-named variable; assignments and arrays are exempt
             * because `[first] = parts` hides which index is being read.
             */
            'prefer-destructuring': 'off',
            '@typescript-eslint/prefer-destructuring': [
                'error',
                {
                    VariableDeclarator: { array: false, object: true },
                    AssignmentExpression: { array: false, object: false }
                }
            ],

            '@typescript-eslint/naming-convention': [
                'error',
                /*
                 * `allowSingleOrDouble`, not `allow`. A single leading underscore was permitted
                 * and a double one was not, which is the entire reason this rule was being
                 * disabled inline nineteen times: `__esModule` (the flag every `jest.mock`
                 * factory must set) and `__v` (Mongo's version key) are both fixed spellings
                 * owned by other ecosystems, not names this codebase gets to choose.
                 */
                {
                    selector: 'default',
                    format: ['camelCase', 'PascalCase'],
                    leadingUnderscore: 'allowSingleOrDouble',
                    trailingUnderscore: 'allow'
                },
                // Allow any format for identifiers that require quotes (e.g. dotted AsyncAPI channel names)
                {
                    selector: ['objectLiteralProperty', 'typeProperty'],
                    modifiers: ['requiresQuotes'],
                    format: null
                },
                {
                    selector: 'variable',
                    format: ['camelCase', 'UPPER_CASE'],
                    leadingUnderscore: 'allowSingleOrDouble',
                    trailingUnderscore: 'allow'
                },
                {
                    selector: ['class', 'typeLike', 'enum'],
                    format: ['PascalCase']
                },
                {
                    selector: ['function'],
                    format: ['camelCase'],
                    leadingUnderscore: 'allow'
                },
                {
                    selector: 'interface',
                    format: ['PascalCase'],
                    custom: {
                        regex: '^I[A-Z]',
                        match: false
                    }
                },
                {
                    selector: 'typeAlias',
                    format: ['PascalCase'],
                    custom: {
                        regex: '^[TI][A-Z]',
                        match: false
                    }
                },
                {
                    selector: 'enum',
                    format: ['PascalCase'],
                    custom: {
                        regex: '^E[A-Z]',
                        match: false
                    }
                },
                {
                    selector: 'typeParameter',
                    format: ['PascalCase'],
                    custom: {
                        regex: '^T[A-Z]?',
                        match: true
                    }
                },
                /*
                 * `snake_case` is in the list because wire formats decide these names, not this
                 * codebase: audit entries (`actor_user_id`, `target_type`), analytics properties
                 * (`order_id`) and header-shaped keys are all read by something outside the repo.
                 */
                {
                    selector: ['memberLike', 'enumMember'],
                    format: ['camelCase', 'PascalCase', 'UPPER_CASE', 'snake_case'],
                    leadingUnderscore: 'allowSingleOrDouble',
                    trailingUnderscore: 'allow'
                }
            ],

            // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/better-regex.md
            'unicorn/better-regex': 'error',

            // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/consistent-destructuring.md
            'unicorn/consistent-destructuring': 'error',

            // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/filename-case.md
            // Every file is kebab-case
            'unicorn/filename-case': [
                'error',
                {
                    case: 'kebabCase'
                }
            ],

            // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/catch-error-name.md
            'unicorn/catch-error-name': [
                'error',
                {
                    name: 'error'
                }
            ],

            // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prevent-abbreviations.md
            'unicorn/prevent-abbreviations': [
                'error',
                {
                    replacements: {
                        i: false,
                        e: false,
                        len: false,
                        prop: false,
                        props: false,
                        prev: false,
                        opts: {
                            options: true
                        },
                        ref: {
                            reference: false
                        }
                    }
                }
            ],

            // A bare `eslint-disable` is an unexplained hole in every rule above.
            '@eslint-community/eslint-comments/require-description': 'error'
        }
    },

    /**
     * A migration talks to the DRIVER, never to this application.
     *
     * `migrate-mongo` replays these files against databases of every age, including ones written
     * before the model they would import existed. A migration that reaches a mongoose model runs
     * today's schema — hooks, defaults, validators and all — against yesterday's documents, which
     * is how a migration stops being replayable.
     *
     * Migrations are CommonJS `.js`, so the guard is `no-restricted-syntax` over `require()`
     * calls: `no-restricted-imports` only matches `import` declarations, which a `.js` migration
     * never contains. (Its predecessor matched `db/migrations/**\/*.ts` — a glob with zero
     * matching files, so the rule it carried never fired.) The path aliases are unresolvable at
     * migrate-mongo runtime anyway; `../../src/` is the spelling a mistake would actually use.
     */
    {
        files: ['db/migrations/**/*.js'],
        rules: {
            'no-restricted-syntax': [
                'error',
                {
                    selector: String.raw`CallExpression[callee.name="require"] > Literal[value=/^(@app|@infrastructure|@modules|@kernel)\u002F/]`,
                    message:
                        'A migration talks to the driver, never to this application — replaying it against an old database must not run today’s schema. Use the `db` handle migrate-mongo passes in.'
                },
                {
                    selector: String.raw`CallExpression[callee.name="require"] > Literal[value=/\u002Fsrc\u002F/]`,
                    message:
                        'A migration talks to the driver, never to this application — replaying it against an old database must not run today’s schema. Use the `db` handle migrate-mongo passes in.'
                }
            ]
        }
    },

    /**
     * The two project-local rules — defined in `eslint/rules/`, unit-tested in
     * `tests/unit/eslint/` — plus the try/catch restriction.
     *
     * Scoped to `src/`, deliberately: a test asserting what the reject envelope does with a
     * string is not shipping user-facing copy, and `tests/unit/infrastructure/http/response.test.ts` passes
     * a dozen literals for exactly that reason. Likewise a test may try/catch freely to assert on
     * what was thrown, and a CLI script's try around an optional read is its error handling.
     *
     * The `TryStatement` restriction is a speed bump, not a wall: production code prefers typed
     * verdicts and promise rejection into the pipeline's handlers, and each surviving try/catch
     * carries an `eslint-disable` whose description (enforced above) says what it is protecting.
     */
    {
        files: ['src/**/*.ts'],
        rules: {
            'local/no-hardcoded-user-text': 'error',
            'no-restricted-syntax': [
                'error',
                ...bannedDoubleCasts,
                {
                    selector: 'TryStatement',
                    message:
                        'try/catch in production code is for the rare spot where a throwing API has no safe wrapper and the failure has a local answer. Prefer returning a verdict or letting the rejection reach the pipeline’s handler; if this spot truly needs one, disable this rule on the line with a description of what is being contained.'
                }
            ]
        }
    },

    /**
     * Controllers, and the one rule that is only theirs.
     *
     * A fire-and-forget promise chain is legitimate in an adapter — `enqueueEmail` deliberately
     * does not block a response on SMTP — and is not legitimate in a request handler, which owes
     * the caller an answer and owes the system its cleanup. So the rule is scoped here rather
     * than run repo-wide, which is exactly the distinction the old source-scanning test drew by
     * only ever looking inside `controllers/` directories.
     */
    {
        files: ['src/modules/*/controllers/**/*.ts'],
        rules: {
            'local/controller-chain-must-catch': 'error'
        }
    },

    /**
     * ── THE REPOSITORY IS THE ONLY DOOR ───────────────────────────────────────────────────────
     *
     * A collection is reached through `repository.ts` and nowhere else. That file owns the query
     * shapes, the lean/hydrated decision and the mapping from a document to plain data, and it
     * owns them so that a schema change has ONE place to land. Every other holder of `orderModel`
     * is a second door: the rename in `model.ts` becomes a hunt through callers, and an
     * `updateOne` runs from a service with none of the repository's guards around it.
     *
     * This block is the general rule and applies to a module's whole tree, minus the three files
     * that are the exception by definition — `model.ts` declares the schema, `repository.ts` is
     * the door, `demo.ts` is a seeder whose entire job is bulk-writing fixtures past the domain
     * rules (already documented as an exception elsewhere) — and minus `tests/**`, where reaching
     * the model directly is how a schema contract gets asserted at all.
     *
     * Only `Model` bindings, deliberately. A service holding `productRepository` is the intended
     * design, not a violation; the wall this block defends is the one between a module and the
     * raw mongoose handle. Controllers get the stricter reading in the block below.
     */
    {
        files: ['src/modules/**/*.ts'],
        ignores: [
            'src/modules/*/model.ts',
            'src/modules/*/repository.ts',
            'src/modules/*/demo.ts',
            'src/modules/**/tests/**'
        ],
        rules: {
            'local/no-persistence-imports': ['error', { bindings: ['Model'], paths: false }]
        }
    },

    /**
     * Controllers, where the same rule is absolute.
     *
     * A controller reads the request, calls one service, and turns a verdict into a status code.
     * It has no business holding a repository either: the moment it does, the transaction
     * boundary and the domain rules that the service was carrying are bypassed by the HTTP layer
     * itself, and the same operation now behaves differently depending on whether it was reached
     * through the controller or through the service a job calls. So here BOTH suffixes are
     * refused, and so is any import whose path is the persistence file — including `import type
     * { OrderDocument } from '../model'`, which puts the storage layout into a signature that is
     * supposed to be about HTTP.
     *
     * Stated AFTER the general block on purpose. A rule's options do not merge across configs any
     * more than `no-restricted-syntax`'s list does — for a file matching both blocks the LAST
     * match wins outright — so this one has to come second or controllers would silently inherit
     * the lax `{ bindings: ['Model'], paths: false }` above and stop reporting `userRepository`.
     */
    {
        files: ['src/modules/*/controllers/**/*.ts'],
        rules: {
            'local/no-persistence-imports': [
                'error',
                { bindings: ['Repository', 'Model'], paths: true }
            ]
        }
    },

    /**
     * `@infrastructure/http/controller` is for controllers, and the name is the whole argument.
     *
     * That file's own docblock opens "The four steps every CONTROLLER repeats". Four services
     * nevertheless imported `validationErrors` from it — a pure `ZodError → ResponseErrorItem[]`
     * mapping with nothing HTTP about it, which they need because they validate with translated
     * messages before answering. Neither side was wrong: the helper was simply filed under a
     * layer rather than beside the shape it builds, and the import line read as a service reaching
     * into the controller layer every time somebody opened it.
     *
     * The helper moved to `./response`, next to the `ResponseErrorItem` it returns, and this wall
     * is what stops the next one landing back here. Everything left in `controller.ts` takes an
     * express `Response`, so a non-controller importing it is now a real finding rather than an
     * ambiguous one.
     *
     * Scoped by `ignores` rather than by listing every non-controller folder: a new file anywhere
     * under `src/modules` is covered the day it is written, which is the property a glob-listed
     * wall never has.
     */
    {
        files: ['src/modules/**/*.ts'],
        ignores: ['src/modules/*/controllers/**/*.ts', 'src/modules/**/tests/**'],
        rules: {
            'no-restricted-imports': [
                'error',
                {
                    paths: [
                        {
                            name: '@infrastructure/http/controller',
                            message:
                                'Everything here takes an express Response, so only a controller can use it. A service that needs to turn a ZodError into the contract’s error list wants `validationErrors` from `@infrastructure/http/response`, which is where that shape is defined.'
                        }
                    ]
                }
            ]
        }
    },

    /**
     * ── THE TIER WALLS ────────────────────────────────────────────────────────────────────────
     *
     * Which tier may depend on which, stated once as a graph instead of six times as file globs.
     *
     * The arrows point one way and only one way: `infrastructure` is the bottom and reaches
     * nothing above it — that inversion is what turned the old `src/utils/` into a dumping ground;
     * `kernel` IS the module system, so it knows modules exist but never which ones; a `module`
     * owns its domain and may not reach the tier that assembles the application; and `domain` is
     * plain TypeScript over plain data, reaching nothing at all.
     *
     * ── Why a plugin rather than `no-restricted-imports` ──────────────────────────────────────
     * Two properties the built-in rule cannot express, both of which used to be carried by tests:
     *
     *   1. **Coverage, at both levels.** `no-restricted-imports` is scoped by file glob, so a NEW
     *      top-level directory under `src/` matches no block, is bound by no wall, and is reported
     *      by nothing. It is not violating a rule — it is invisible. Two things close that here,
     *      and they are the guarantee `deptrac --fail-on-uncovered` gives the PHP twin:
     *      `boundaries/no-unknown-files` refuses a FILE no descriptor claims, and the
     *      `default: 'disallow'` below refuses an EDGE no policy claims — so classifying a new
     *      tier is not enough either, its arrows have to be argued for before it can import
     *      anything.
     *   2. **Relation.** What a module's spec may import depends on WHICH module owns it, and a
     *      glob cannot say "its own". `capture` reads the module name out of the path and
     *      `{{ from.element.captured.module }}` compares the two sides, so one policy covers every
     *      domain — including the one added tomorrow.
     *
     * ── The two doors, and why they are stated as files ───────────────────────────────────────
     * A module publishes `index.ts` (its runtime API) and `demo.ts` (its fixtures), and nothing
     * else. `fileInternalPath` names those two files inside the target element, so the rule is
     * about the door rather than about the path spelling that reaches it.
     */
    {
        settings: {
            /*
             * Only `src/`. The tiers live here, and this is the tree `no-unknown-files` is meant
             * to hold exhaustively — `tests/`, `scripts/`, `db/` and `shared/` have no tier and
             * would each need a descriptor for the sake of being ignored.
             */
            'boundaries/include': ['src/**/*.ts'],

            /*
             * Every wall below is stated in terms of the FILE an import resolves to, so an
             * unresolved specifier is a silent pass: `@modules/products` reads as an npm package,
             * belongs to no element, and matches no policy. The TypeScript resolver reads the
             * `paths` map out of `tsconfig.json`, which is where `@modules`, `@kernel`,
             * `@infrastructure` and `@app` are actually defined.
             */
            'import/resolver': {
                typescript: { alwaysTryTypes: true, project: './tsconfig.json' }
            },

            /*
             * Anchored at the repo root (`partialMatch: false`) rather than matched right-to-left.
             * The default tries progressively longer suffixes, so a bare `modules/*` would also
             * claim `src/infrastructure/modules/anything` — the anchored form says where each tier
             * lives, which is the fact being stated.
             *
             * ORDER IS SIGNIFICANT: the first descriptor that matches wins, so `domain` must be
             * declared before the `module` that contains it.
             */
            'boundaries/elements': [
                {
                    type: 'domain',
                    pattern: 'src/modules/*/domain',
                    capture: ['module'],
                    partialMatch: false
                },
                {
                    type: 'module',
                    pattern: 'src/modules/*',
                    capture: ['module'],
                    partialMatch: false
                },
                { type: 'kernel', pattern: 'src/kernel', partialMatch: false },
                { type: 'infrastructure', pattern: 'src/infrastructure', partialMatch: false },
                { type: 'app', pattern: 'src/app', partialMatch: false },
                { type: 'types', pattern: 'src/types', partialMatch: false }
            ],

            /*
             * The file layer, for the four files that are a tier each on their own — an element
             * descriptor matches folders, and these have no folder.
             *
             * Named one by one rather than as `src/*.ts`, deliberately: the whole point of
             * `no-unknown-files` is that something new has to be classified before it can be
             * imported, and a wildcard here would wave through the next file to land beside them.
             */
            'boundaries/files': [
                { pattern: 'src/app.ts', category: 'composition-root' },
                { pattern: 'src/cluster.ts', category: 'process-supervisor' },
                { pattern: 'src/modules.ts', category: 'registry' },
                { pattern: 'src/globals.d.ts', category: 'ambient' },
                { pattern: 'src/modules/*/tests/**/*.ts', category: 'spec' }
            ]
        },
        rules: {
            /*
             * The uncovered check. A file under `src/` that matches no element and no category is
             * an error here, one commit before it can quietly import anything it likes.
             */
            'boundaries/no-unknown-files': 'error',

            'boundaries/dependencies': [
                'error',
                {
                    default: 'disallow',
                    message:
                        '{{from.element.type}} may not depend on {{to.element.type}} — see docs/theory/layers.md.',
                    policies: [
                        /*
                         * ── What is permitted ─────────────────────────────────────────────────
                         *
                         * The default is `disallow`, so this half is not decoration: an edge no
                         * policy names is refused. That is the property `--fail-on-uncovered` gives
                         * the PHP twin's deptrac one level up — `no-unknown-files` refuses a FILE
                         * no descriptor claims, and denying by default refuses an EDGE no policy
                         * claims. With `allow` as the default, adding a tier to the element list
                         * and forgetting to write its rules leaves it able to import anything, and
                         * nothing says so.
                         *
                         * Read top to bottom: the last matching policy wins, so these open the
                         * legitimate arrows and the walls below close the illegitimate ones.
                         */
                        {
                            // npm. The graph being described is this repository's, and a package
                            // belongs to no tier of it.
                            allow: { to: { module: { origin: 'external' } } }
                        },
                        {
                            // Downward, which is what the tiers are for: everything may reach the
                            // substrate below it, and `types` is erased at compile time.
                            allow: { to: { element: { type: ['infrastructure', 'types'] } } }
                        },
                        {
                            // `kernel` is the module system, reachable by what sits above it.
                            from: { element: { type: ['module', 'domain', 'app'] } },
                            allow: { to: { element: { type: 'kernel' } } }
                        },
                        {
                            // `app` assembles the application and is the one tier allowed to know
                            // which domains exist.
                            from: { element: { type: 'app' } },
                            allow: { to: { element: { type: ['app', 'module'] } } }
                        },
                        {
                            // A tier reaches its own files freely — that is what makes it a tier
                            // rather than a pile of files that happen to share a folder.
                            from: { element: { type: 'infrastructure' } },
                            allow: { to: { element: { type: 'infrastructure' } } }
                        },
                        {
                            from: { element: { type: 'kernel' } },
                            allow: { to: { element: { type: 'kernel' } } }
                        },
                        {
                            /*
                             * The three files that are a tier each — `app.ts` composes,
                             * `cluster.ts` supervises, `modules.ts` IS the registry and is the one
                             * caller allowed to import `@modules/<name>/module`. They have no
                             * element (an element descriptor matches folders), so they are named
                             * by the file categories declared above.
                             */
                            from: {
                                file: {
                                    categories: [
                                        'composition-root',
                                        'process-supervisor',
                                        'registry'
                                    ]
                                }
                            },
                            allow: { to: { element: { type: '*' } } }
                        },
                        {
                            // …including each other: `cluster.ts` imports `app.ts`, and neither
                            // belongs to an element, so the edge is named by category on both ends.
                            from: {
                                file: {
                                    categories: [
                                        'composition-root',
                                        'process-supervisor',
                                        'registry'
                                    ]
                                }
                            },
                            allow: {
                                to: {
                                    file: {
                                        categories: [
                                            'composition-root',
                                            'process-supervisor',
                                            'registry'
                                        ]
                                    }
                                }
                            }
                        },

                        {
                            /*
                             * The registry is readable by the tier that composes the application
                             * and by any spec that needs the real module list — `app/routes.ts`
                             * mounts what it enumerates, and a co-located spec asserting
                             * cross-module cleanup has to run the registry rather than a stand-in.
                             *
                             * Not by `infrastructure` or `kernel`: those sit below the domains, and
                             * reading the list of them is knowing which ones exist.
                             */
                            from: [
                                { element: { type: 'app' } },
                                { file: { categories: ['spec'] } }
                            ],
                            allow: { to: { file: { categories: ['registry'] } } }
                        },

                        /*
                         * ── What is refused ───────────────────────────────────────────────────
                         */
                        {
                            from: { element: { type: 'infrastructure' } },
                            disallow: {
                                to: { element: { type: ['kernel', 'module', 'domain', 'app'] } }
                            },
                            message:
                                'infrastructure is the bottom of the dependency graph. It may not reach up into application code — that inversion is what turned the old src/utils/ into a dumping ground.'
                        },
                        {
                            from: { element: { type: 'kernel' } },
                            disallow: { to: { element: { type: ['module', 'domain', 'app'] } } },
                            message:
                                'kernel IS the module system: it knows that modules exist but never which ones. One import of a named module would make the mechanism depend on a thing it carries, and "delete a domain, delete a folder" would stop being true.'
                        },
                        {
                            from: { element: { type: ['module', 'domain'] } },
                            disallow: { to: { element: { type: 'app' } } },
                            message:
                                'A module may not reach the app tier. `app` assembles the application and is allowed to know every domain; reaching back would point the arrow both ways. A guard every module needs belongs in @kernel behind a port — see kernel/authentication.ts.'
                        },

                        /*
                         * The two doors. A sibling is reachable through `index.ts` (its runtime
                         * API) or `demo.ts` (its fixtures); every other file of it is internal.
                         * The allow follows the disallow because the LAST matching policy wins.
                         */
                        {
                            from: { element: { type: ['module', 'domain'] } },
                            disallow: { to: { element: { type: ['module', 'domain'] } } },
                            message:
                                'Import a sibling module through one of its two public paths: @modules/<name> for its runtime API, @modules/<name>/demo for its demo fixtures. Never its internals — the moment one is reached the module stops being deletable.'
                        },
                        {
                            from: { element: { type: ['module', 'domain'] } },
                            allow: {
                                to: {
                                    element: {
                                        type: 'module',
                                        fileInternalPath: ['index.ts', 'demo.ts']
                                    }
                                }
                            }
                        },

                        /*
                         * The second door is narrower than the first, and the asymmetry is the
                         * whole reason it exists: `demo.ts` is published so that a SEEDER may
                         * point at a sibling's fixtures, and for no other reason.
                         *
                         * Before the split, `products/index.ts` published `SEED_PRODUCT_IDS` and
                         * `productFixtures` beside `productService`, so a controller could have
                         * imported demo rows without anything failing — the barrel made runtime
                         * and demo the same surface, and nothing could tell the two edges apart.
                         * Splitting the paths only helps while something asserts they carry
                         * different traffic.
                         *
                         * The other half of that — a barrel re-exporting its own `demo.ts` — is
                         * NOT expressible here: it is an edge inside one element, and this plugin
                         * only weighs edges between them. Nothing asserts it — a barrel
                         * re-exporting its own demo fixtures is a review question.
                         */
                        {
                            from: { element: { type: ['module', 'domain'] } },
                            disallow: {
                                to: { element: { type: 'module', fileInternalPath: 'demo.ts' } }
                            },
                            message:
                                'Only a seeder may take a sibling’s /demo path. Demo data exists to be written by db/demo, and an import of it from runtime code puts fixtures into the graph the application actually runs.'
                        },
                        {
                            from: { element: { fileInternalPath: 'demo.ts' } },
                            allow: {
                                to: { element: { type: 'module', fileInternalPath: 'demo.ts' } }
                            }
                        },

                        /*
                         * A module reaches its own files freely — a service imports its repository,
                         * a controller imports its service — so "the same module" is compared by
                         * the captured name rather than listed per domain.
                         */
                        {
                            from: { element: { type: ['module', 'domain'] } },
                            allow: {
                                to: {
                                    element: {
                                        captured: { module: '{{ from.element.captured.module }}' }
                                    }
                                }
                            }
                        },

                        /*
                         * The domain layer: plain TypeScript over plain data. It is the only tier
                         * whose rule is about what it may TOUCH rather than which tier it may
                         * reach — no framework, no tier, no sibling, and not even the outer files
                         * of its own module, so the arrow points inward only.
                         *
                         * `@types` is the one thing it may take, and always could: those are
                         * ambient declarations, erased at compile time, so importing one adds no
                         * edge to the runtime graph at all.
                         *
                         * Its own folder stays reachable, which the same-module allow above
                         * already grants and the disallow here must not take back — hence the
                         * final policy restoring it.
                         */
                        {
                            from: { element: { type: 'domain' } },
                            disallow: {
                                to: {
                                    element: {
                                        type: ['infrastructure', 'kernel', 'app', 'module']
                                    }
                                }
                            },
                            message:
                                'The domain layer imports nothing but plain TypeScript — no tier, no sibling module, and none of the outer files of its own module. If a rule needs i18n it is returning a message where it should return a verdict; if it needs a repository it is doing the job of the service layer.'
                        },
                        {
                            from: { element: { type: 'domain' } },
                            allow: {
                                to: {
                                    element: {
                                        type: 'domain',
                                        captured: { module: '{{ from.element.captured.module }}' }
                                    }
                                }
                            }
                        },

                        /*
                         * Co-located specs, and the rule that used to need a test.
                         *
                         * A spec is deleted with the module it belongs to, so it cannot leave
                         * coupling behind that outlives either one — and it legitimately needs two
                         * things production code must not have: its own module's internals (a unit
                         * test of `service.ts` tests `service.ts`, not the barrel's view of it) and
                         * a sibling's `module.ts` manifest, because asserting cross-module cleanup
                         * means running the real registry.
                         *
                         * Stated last so it overrides the module walls above for spec files only.
                         */
                        {
                            from: { file: { categories: ['spec'] } },
                            allow: {
                                to: {
                                    element: {
                                        type: ['module', 'domain'],
                                        fileInternalPath: ['index.ts', 'module.ts', 'tests/**']
                                    }
                                }
                            }
                        }
                    ]
                }
            ]
        }
    },

    /**
     * What the domain layer may not TOUCH, as opposed to which tier it may reach.
     *
     * Left with `no-restricted-imports` on purpose: `mongoose` and `express` are external
     * packages, not tiers, so they are not a boundary question and stating them as one would mean
     * describing npm in the element graph.
     */
    {
        files: ['src/modules/*/domain/**/*.ts'],
        rules: {
            'no-restricted-imports': [
                'error',
                {
                    paths: [
                        {
                            name: 'mongoose',
                            message:
                                'The domain layer may not know how anything is stored. Take the data as a plain argument and let the repository do the reading.'
                        },
                        {
                            name: 'express',
                            message:
                                'The domain layer may not know it is being called over HTTP. Return a verdict; the controller turns it into a status code.'
                        }
                    ]
                }
            ]
        }
    },
    /**
     * The analytics event catalogue — the one namespace both repos write into.
     *
     * Every name here becomes a row in Umami, and a name is the only part of an event that a
     * dashboard groups by. `Cart_Item_Added` and `cart_item_added` are two different funnels in
     * that table, and nothing downstream can merge them back — so the convention is not a style
     * preference, it is the difference between one funnel and two.
     *
     * `snake_case` values, `SCREAMING_SNAKE` keys, and `noun_pastTenseVerb` for the shape of the
     * name itself. Only the first two are machine-checkable; the third is still prose, because no
     * selector knows a noun from a verb.
     *
     * Scoped to where names are AUTHORED: a module's own file, and the client's half in
     * `shared/contracts/analytics.frontend.ts`. The published catalogue is generated from these
     * and carries `DO NOT EDIT`, so linting it would only ever report a bug in the bundler.
     *
     * The `TryStatement` selector is repeated from the `src/**` block: `no-restricted-syntax`
     * does not merge across configs — the nearest match REPLACES the list — so leaving it out
     * here would silently lift the try/catch restriction for exactly these files.
     */
    {
        files: ['src/modules/*/analytics.ts', 'shared/contracts/analytics.frontend.ts'],
        rules: {
            'no-restricted-syntax': [
                'error',
                ...bannedDoubleCasts,
                {
                    selector:
                        'Property > Literal[value]:not([value=/^[a-z][a-z0-9]*(_[a-z0-9]+)*$/])',
                    message:
                        'An analytics event name is lower snake_case — `cart_item_added`. It is written verbatim into Umami, where a differently-spelled name is a separate funnel nothing can merge back.'
                },
                {
                    selector: 'Property > Identifier.key:not([name=/^[A-Z][A-Z0-9_]*$/])',
                    message:
                        'An analytics event constant is SCREAMING_SNAKE — `CART_ITEM_ADDED`. The published catalogue is sliced out of this declaration by matching that shape, so a differently-cased key is dropped from the frontend copy without failing anything.'
                },
                {
                    selector: 'TryStatement',
                    message:
                        'try/catch in production code is for the rare spot where a throwing API has no safe wrapper and the failure has a local answer. Prefer returning a verdict or letting the rejection reach the pipeline’s handler; if this spot truly needs one, disable this rule on the line with a description of what is being contained.'
                }
            ]
        }
    },

    /**
     * CLI tooling and seeders: node programs inside the `tsconfig` project, so they keep the
     * type-aware rules — but a script's interface is the terminal and its exit code, so
     * `no-console` would flag every line of output it exists to produce.
     */
    {
        files: ['scripts/**/*.ts', 'db/**/*.ts'],
        languageOptions: {
            globals: {
                ...globals.node
            }
        },
        rules: {
            'no-console': 'off'
        }
    },

    /**
     * The local rule definitions. In the `tsconfig` project so their tests can import them, but
     * an ESLint rule walks an untyped AST — `context` and every node come in as `any`, and typing
     * them properly means depending on `@types/estree` for two rules with their own unit tests.
     * The `no-unsafe-*` family follows `no-explicit-any` out for the same reason: every node
     * access in an AST walk is "unsafe" to a checker that has no ESTree types to check against.
     */
    {
        files: ['eslint/**/*.ts'],
        languageOptions: {
            globals: {
                ...globals.node
            }
        },
        rules: {
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/no-unsafe-assignment': 'off',
            '@typescript-eslint/no-unsafe-member-access': 'off',
            '@typescript-eslint/no-unsafe-call': 'off',
            '@typescript-eslint/no-unsafe-argument': 'off',
            '@typescript-eslint/no-unsafe-return': 'off'
        }
    },

    /**
     * Tool configs at the repo root, and the VitePress config: TypeScript, but OUTSIDE the
     * `tsconfig` project, so the type-aware program is switched off — for these files it would be
     * a parser error, not a finding. Everything syntax-level still applies.
     *
     * `.dependency-cruiser.cjs` is CommonJS rather than TypeScript, and is here for the same
     * reason: outside the project, so type-aware rules cannot run on it.
     */
    {
        files: [
            'eslint.config.ts',
            'orval.config.ts',
            '.dependency-cruiser.cjs',
            'jest.config.cluster.js',
            'docs/.vitepress/**/*.{ts,mts}'
        ],
        extends: [tseslint.configs.disableTypeChecked],
        languageOptions: {
            globals: {
                ...globals.node
            }
        },
        rules: {
            'no-console': 'off',
            // `props`, `env`, `dir`: the VitePress/orval config surface spells its own keys.
            'unicorn/prevent-abbreviations': 'off',
            // dependency-cruiser and jest both read CommonJS configs; `module.exports` and
            // `require` are their interface, not a style choice.
            'unicorn/prefer-module': 'off',
            '@typescript-eslint/no-require-imports': 'off'
        }
    },

    /**
     * Plain CommonJS tooling: jest's configs (a `.js` because the per-file coverage thresholds
     * inside need an explanation attached, and JSON cannot carry a comment), commitlint,
     * migrate-mongo's config and the migrations it replays. Outside the `tsconfig` project, so
     * the type-aware program is off; CommonJS, so the ESM-preference rules yield.
     */
    {
        files: [
            'jest.config.js',
            'jest.config.mutation.js',
            'commitlint.config.cjs',
            'migrate-mongo-config.js',
            'db/migrations/**/*.js'
        ],
        extends: [tseslint.configs.disableTypeChecked],
        languageOptions: {
            sourceType: 'commonjs',
            globals: {
                ...globals.node
            }
        },
        rules: {
            'no-console': 'off',
            '@typescript-eslint/no-require-imports': 'off',
            // `up(db, client)` is migrate-mongo's signature and `moduleNameMapper` is jest's key:
            // these files spell what their tools spell.
            'unicorn/prevent-abbreviations': 'off'
        }
    },

    /**
     * "Special" files names are better to be left untouched
     */
    {
        files: ['tests/**/*', '**/*.spec.ts', '**/*.test.ts', '**/*.d.ts'],
        rules: {
            'unicorn/filename-case': 'off',
            'unicorn/prevent-abbreviations': 'off'
        }
    },

    /**
     * Type-aware relief for test code, and only the relief the mocking idiom actually needs.
     *
     * `jest.mock` factories, `jest.requireActual`, and every `expect.any(...)` shape come back
     * `any` — the `no-unsafe-*` family would demand a cast ceremony on top of each one that
     * asserts nothing the test does not already assert. `no-unnecessary-condition` reads
     * `?.`-probing of a payload as redundant, but probing IS the assertion in a test; and a test
     * legitimately deletes `process.env` keys (`no-dynamic-delete`) and passes `() => {}` as the
     * callback it is not exercising (`no-empty-function`). Everything else — including the
     * deprecation and floating-promise checks — stays on.
     */
    {
        files: ['tests/**/*.ts', 'src/modules/*/tests/**/*.ts'],
        rules: {
            '@typescript-eslint/no-unsafe-assignment': 'off',
            '@typescript-eslint/no-unsafe-member-access': 'off',
            '@typescript-eslint/no-unsafe-call': 'off',
            '@typescript-eslint/no-unsafe-argument': 'off',
            '@typescript-eslint/no-unsafe-return': 'off',
            '@typescript-eslint/no-unnecessary-condition': 'off',
            '@typescript-eslint/no-dynamic-delete': 'off',
            '@typescript-eslint/no-empty-function': 'off',
            // `expect(mock.method)` hands the method around unbound by design,
            // and a test try/catches to assert on what was thrown. The double-cast ban stays:
            // tests are where that idiom bred.
            '@typescript-eslint/unbound-method': 'off',
            'no-restricted-syntax': ['error', ...bannedDoubleCasts]
        }
    },

    /**
     * The unit layer does not boot the application, and does not open a database.
     *
     * "Unit" here means two things: no HTTP, and no Mongo, real or in-memory. It was not always the
     * second — 36 module specs used to call `setupTestDb()` against the run's shared in-memory
     * mongod, on the reasoning that most of what a repository or a service does IS what Mongo does.
     * That reasoning was sound for `npm test`; it stopped being sound the moment mutation testing
     * entered the picture. Stryker executes the unit suite once per mutant, so anything the layer
     * imports or connects to at module scope is paid thousands of times over, and a `beforeEach`
     * wipe that is microseconds in a normal run adds up across a mutant count in the thousands. Those
     * 36 specs now live in each module's `tests/integration/` — see NODE_MUTATION_MONGOD.md for the
     * per-module breakdown — and `unit-layer-stays-database-free` in `.dependency-cruiser.cjs` is
     * what keeps a new spec from drifting back in. That rule is stated as REACHABILITY, so it also
     * catches the way it actually arrives: a spec importing a helper that already had the database.
     * The bans below give the direct form at lint time, in the editor, for the two entry points
     * that are clean import names.
     *
     * `@app/*` is deliberately NOT banned. `tests/unit/app/process-error-handlers.test.ts` unit
     * tests a file that lives in the app tier, which is the tier being tested rather than the
     * application being started; the composition root is `src/app.ts`, and that is what the pattern
     * below names.
     *
     * This block sits after the module-spec exemption above, which switches `no-restricted-imports`
     * off wholesale — flat config gives the last match, so the order is what makes this apply to
     * co-located unit specs at all.
     */
    {
        files: ['tests/unit/**/*.ts', 'src/modules/*/tests/unit/**/*.ts'],
        rules: {
            'no-restricted-imports': [
                'error',
                {
                    paths: [
                        {
                            name: 'supertest',
                            message:
                                'A unit test that sends a request is an integration test. Move it to tests/integration/, where the app is booted once for the whole suite.'
                        },
                        {
                            name: '@tests/http',
                            message:
                                '`api()` mounts src/app.ts — every module, every middleware — to exercise one function. Move the spec to tests/integration/, or call the unit under test directly.'
                        },
                        {
                            name: '@tests/setup-test-db',
                            message:
                                'A unit test that opens a database is an integration test. Move it to tests/integration/, where Stryker does not rerun it once per mutant.'
                        },
                        {
                            name: '@tests/database',
                            message:
                                'A unit test that opens a database is an integration test. Move it to tests/integration/, where Stryker does not rerun it once per mutant.'
                        },
                        {
                            name: 'mongodb-memory-server',
                            message:
                                'A unit test that boots an in-memory mongod is an integration test. Move it to tests/integration/, where Stryker does not rerun it once per mutant.'
                        }
                    ],
                    patterns: [
                        {
                            group: ['**/src/app', '**/src/cluster'],
                            message:
                                'The composition root starts the application. A unit test importing it pays for the whole registry on every mutant Stryker runs.'
                        }
                    ]
                }
            ]
        }
    },

    {
        files: ['**/*.d.ts'],
        rules: {
            '@typescript-eslint/naming-convention': 'off'
        }
    },

    /**
     * Jest's globals, for the standalone suites and the co-located module specs alike.
     */
    {
        files: ['tests/**/*', 'src/modules/*/tests/**/*'],

        languageOptions: {
            globals: {
                ...globals.jest
            }
        }
    },

    /**
     * Disable conflicts with prettier
     */
    configPrettier
);
