import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';
import configPrettier from 'eslint-config-prettier';
import pluginUnicorn from 'eslint-plugin-unicorn';
import comments from '@eslint-community/eslint-plugin-eslint-comments/configs';
import { globalIgnores } from 'eslint/config';
import path from 'node:path';
import localRules from './eslint/rules';

/**
 * `x as unknown as T` — the double cast that erases the type system's objection instead of
 * answering it — is banned everywhere, tests included. `no-restricted-syntax` does not merge
 * across configs (the nearest match REPLACES the list), so every block that configures that
 * rule spreads this in, or the ban would silently lift for exactly those files.
 */
const bannedDoubleCasts = [
    {
        selector: 'TSAsExpression > TSAsExpression[typeAnnotation.type="TSUnknownKeyword"]',
        message:
            '`as unknown as T` erases the type error instead of answering it. Type the source honestly (`.lean<T>()`, a typed factory) — or, for a hand-built test stub, use the one sanctioned seam: `asStub<T>()` from tests/support/stub.ts.'
    },
    {
        selector: 'TSAsExpression > TSAsExpression[typeAnnotation.type="TSAnyKeyword"]',
        message:
            '`as any as T` erases the type error instead of answering it. Type the source honestly — or, for a hand-built test stub, use `asStub<T>()` from tests/support/stub.ts.'
    }
];

export default tseslint.config(
    /**
     * Excluded files — GENERATED OR FOREIGN ONLY.
     *
     * The bar for an entry here: linting it is impossible or meaningless, not merely
     * inconvenient. Tool configs, migrations and CLI scripts used to sit in this list because
     * they fall outside the `tsconfig` project; they are linted now, through the scoped blocks
     * near the bottom that switch off the type-aware program instead of the whole linter.
     */
    globalIgnores([
        /*
         * The k6 load scenarios. They are JavaScript, but not this project's JavaScript: they run
         * inside the k6 Go runtime and import from `k6/http`, a module specifier that resolves
         * only there. Linting them means resolving imports that cannot resolve and enforcing
         * rules written for the app on a file the app never loads.
         */
        'k6/**',
        '**/node_modules/**',
        '**/dist/**',
        '**/coverage/**',
        // The built docs site and its build cache; the authored source under `docs/` is markdown,
        // and the VitePress config is linted through the tool-config block below.
        'docs/.vitepress/dist/**',
        'docs/.vitepress/cache/**',
        /*
         * Stryker copies the whole project here per run. Without this, `npm run lint` fails with
         * one parser error per generated file the moment a mutation run is in flight — or forever,
         * if a crashed run left the directory behind — because the copies sit outside the
         * `tsconfig` project `parserOptions.project` resolves against. `jest.config.js` ignores
         * the same path for the same reason; see the note in `stryker.config.json`.
         */
        '.stryker-tmp/**',
        // Per-run in-memory Mongo data directories — see tests/support/global-setup.ts
        '.tmp/**',
        // Generated by orval — do not lint generated output
        'api/**',
        // Generated by `npm run gen:asyncapi`, same as `api` above
        'src/types/asyncapi.generated.ts',
        '.prism/**',
        '.dev/**'
    ]),

    /**
     * Base eslint + typescript presets.
     *
     * The three type-checked tiers are the point of setting `parserOptions.project` at all:
     * the type information is already being built for the parser, so the rules that consume it
     * (`no-floating-promises`, `no-misused-promises`, `no-unnecessary-condition`, …) cost almost
     * nothing extra and catch the bugs a syntax-only pass cannot see.
     */
    js.configs.recommended,
    ...tseslint.configs.strictTypeChecked,
    ...tseslint.configs.stylisticTypeChecked,

    /**
     * Unicorn plugin
     */
    pluginUnicorn.configs['flat/recommended'],

    /**
     * Every `eslint-disable` must say why. The two project-local rules and the `TryStatement`
     * restriction below are deliberately annoying; a bare disable comment converts "deliberately
     * annoying" into "silently ignored", and the description requirement is what keeps each
     * exemption an argument instead of a shrug.
     */
    comments.recommended,

    /**
     * All global rules
     */
    {
        languageOptions: {
            parserOptions: {
                project: path.resolve('./tsconfig.json')
            },
            // A server: `process`, `Buffer` and friends are the environment, `window` is not.
            globals: {
                ...globals.node
            },
            ecmaVersion: 'latest',
            sourceType: 'module'
        },

        plugins: {
            local: { rules: localRules }
        },

        rules: {
            'no-console': 'warn',
            'no-debugger': 'warn',
            'no-restricted-syntax': ['error', ...bannedDoubleCasts],
            /*
             * `!` is allowed where a value has ALREADY been proven present by something the
             * compiler cannot follow — the `isAdmin` middleware guaranteeing `request.authContext`,
             * a `.some(x => !x)` guard proving the `.map` below it finds no `undefined`. The
             * alternative is a cast, which `no-restricted-syntax` above bans for being the same
             * claim in a form that also silences type errors. The claim itself is the same either
             * way; `!` is the spelling that stays narrow.
             */
            '@typescript-eslint/no-non-null-assertion': 'off',
            '@typescript-eslint/use-unknown-in-catch-callback-variable': 'off',
            'no-nested-ternary': 'off',
            'unicorn/no-nested-ternary': 'off',
            'unicorn/prefer-top-level-await': 'off',

            /*
             * Four unicorn rules turned off rather than exempted seventeen times.
             *
             * Each was being disabled inline wherever it fired, which is the signal that the rule
             * disagrees with the stack rather than with the code:
             *
             *   no-null            — Mongo and Express both use `null` with meaning. `deletedAt:
             *                        null` is not `undefined`, and `res.json(null)` is a body.
             *   no-useless-undefined — an explicit `return undefined` is this codebase's stated
             *                        convention for "looked, found nothing" (see the union-return
             *                        note in `infrastructure/http/response.ts`).
             *   no-process-exit    — this is a server with a shutdown path; `server-lifecycle.ts`
             *                        exits deliberately, four times, after draining.
             *   prefer-module      — it flags every `__dirname`, and `__dirname` is how this
             *                        stack actually runs: tsx and jest both execute the TS as
             *                        CommonJS, so `import.meta.dirname` would be `undefined` at
             *                        runtime. Fifty findings, every one a rename into a crash.
             *
             * A rule that needs six exemptions is not catching bugs, it is collecting signatures.
             */
            'unicorn/no-null': 'off',
            'unicorn/no-useless-undefined': 'off',
            'unicorn/no-process-exit': 'off',
            'unicorn/prefer-module': 'off',

            '@typescript-eslint/restrict-plus-operands': [
                'error',
                {
                    allowNumberAndString: true
                }
            ],

            /*
             * strictTypeChecked's default rejects numbers in template literals, which turns every
             * log line and metric label into a `String()` ceremony. Numbers stringify one way;
             * the risk the rule guards against is objects and `undefined`, which stay banned.
             */
            '@typescript-eslint/restrict-template-expressions': [
                'error',
                {
                    allowNumber: true
                }
            ],

            /*
             * `value || fallback` on a STRING is this codebase's idiom for "empty means unset" —
             * the `host` npm script deliberately sets `NODE_DB_URI=` to blank, and a blank
             * feedback name falls back to translated copy. For everything non-string, `??` stays
             * the required spelling.
             */
            '@typescript-eslint/prefer-nullish-coalescing': [
                'error',
                {
                    ignorePrimitives: { string: true }
                }
            ],

            /*
             * `(request, response) => response.json(body)` is the shape of half the controllers
             * in an Express app; the "confusing" void return is Express's own idiom, and the
             * fixer's `{ response.json(body); }` says nothing the shorthand does not.
             */
            '@typescript-eslint/no-confusing-void-expression': [
                'error',
                {
                    ignoreArrowShorthand: true
                }
            ],

            /*
             * An underscore prefix is the deliberate spelling of "unused on purpose" — a handler
             * signature that must take `(error, request, response, next)` to be an error handler,
             * a destructuring that drops a key. Everything unprefixed stays an error.
             */
            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_'
                }
            ],

            /*
             * `const { name } = user` over `const name = user.name` — one read of the object per
             * binding site instead of a scatter of member accesses. Only for declarations that
             * read a property into a same-named variable; assignments and arrays are exempt
             * because `[first] = parts` hides which index is being read.
             */
            'prefer-destructuring': 'off',
            '@typescript-eslint/prefer-destructuring': [
                'error',
                {
                    VariableDeclarator: { array: false, object: true },
                    AssignmentExpression: { array: false, object: false }
                }
            ],

            '@typescript-eslint/naming-convention': [
                'error',
                /*
                 * `allowSingleOrDouble`, not `allow`. A single leading underscore was permitted
                 * and a double one was not, which is the entire reason this rule was being
                 * disabled inline nineteen times: `__esModule` (the flag every `jest.mock`
                 * factory must set) and `__v` (Mongo's version key) are both fixed spellings
                 * owned by other ecosystems, not names this codebase gets to choose.
                 */
                {
                    selector: 'default',
                    format: ['camelCase', 'PascalCase'],
                    leadingUnderscore: 'allowSingleOrDouble',
                    trailingUnderscore: 'allow'
                },
                // Allow any format for identifiers that require quotes (e.g. dotted AsyncAPI channel names)
                {
                    selector: ['objectLiteralProperty', 'typeProperty'],
                    modifiers: ['requiresQuotes'],
                    format: null
                },
                {
                    selector: 'variable',
                    format: ['camelCase', 'UPPER_CASE'],
                    leadingUnderscore: 'allowSingleOrDouble',
                    trailingUnderscore: 'allow'
                },
                {
                    selector: ['class', 'typeLike', 'enum'],
                    format: ['PascalCase']
                },
                {
                    selector: ['function'],
                    format: ['camelCase'],
                    leadingUnderscore: 'allow'
                },
                {
                    selector: 'interface',
                    format: ['PascalCase'],
                    custom: {
                        regex: '^I[A-Z]',
                        match: false
                    }
                },
                {
                    selector: 'typeAlias',
                    format: ['PascalCase'],
                    custom: {
                        regex: '^[TI][A-Z]',
                        match: false
                    }
                },
                {
                    selector: 'enum',
                    format: ['PascalCase'],
                    custom: {
                        regex: '^E[A-Z]',
                        match: false
                    }
                },
                {
                    selector: 'typeParameter',
                    format: ['PascalCase'],
                    custom: {
                        regex: '^T[A-Z]?',
                        match: true
                    }
                },
                /*
                 * `snake_case` is in the list because wire formats decide these names, not this
                 * codebase: audit entries (`actor_user_id`, `target_type`), analytics properties
                 * (`order_id`) and header-shaped keys are all read by something outside the repo.
                 */
                {
                    selector: ['memberLike', 'enumMember'],
                    format: ['camelCase', 'PascalCase', 'UPPER_CASE', 'snake_case'],
                    leadingUnderscore: 'allowSingleOrDouble',
                    trailingUnderscore: 'allow'
                }
            ],

            // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/better-regex.md
            'unicorn/better-regex': 'error',

            // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/consistent-destructuring.md
            'unicorn/consistent-destructuring': 'error',

            // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/filename-case.md
            // Every file is kebab-case
            'unicorn/filename-case': [
                'error',
                {
                    case: 'kebabCase'
                }
            ],

            // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/catch-error-name.md
            'unicorn/catch-error-name': [
                'error',
                {
                    name: 'error'
                }
            ],

            // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prevent-abbreviations.md
            'unicorn/prevent-abbreviations': [
                'error',
                {
                    replacements: {
                        i: false,
                        e: false,
                        len: false,
                        prop: false,
                        props: false,
                        prev: false,
                        opts: {
                            options: true
                        },
                        ref: {
                            reference: false
                        }
                    }
                }
            ],

            // A bare `eslint-disable` is an unexplained hole in every rule above.
            '@eslint-community/eslint-comments/require-description': 'error'
        }
    },

    /**
     * A migration talks to the DRIVER, never to this application.
     *
     * `migrate-mongo` replays these files against databases of every age, including ones written
     * before the model they would import existed. A migration that reaches a mongoose model runs
     * today's schema — hooks, defaults, validators and all — against yesterday's documents, which
     * is how a migration stops being replayable.
     *
     * Migrations are CommonJS `.js`, so the guard is `no-restricted-syntax` over `require()`
     * calls: `no-restricted-imports` only matches `import` declarations, which a `.js` migration
     * never contains. (Its predecessor matched `db/migrations/**\/*.ts` — a glob with zero
     * matching files, so the rule it carried never fired.) The path aliases are unresolvable at
     * migrate-mongo runtime anyway; `../../src/` is the spelling a mistake would actually use.
     */
    {
        files: ['db/migrations/**/*.js'],
        rules: {
            'no-restricted-syntax': [
                'error',
                {
                    selector: String.raw`CallExpression[callee.name="require"] > Literal[value=/^(@app|@infrastructure|@modules|@kernel)\u002F/]`,
                    message:
                        'A migration talks to the driver, never to this application — replaying it against an old database must not run today’s schema. Use the `db` handle migrate-mongo passes in.'
                },
                {
                    selector: String.raw`CallExpression[callee.name="require"] > Literal[value=/\u002Fsrc\u002F/]`,
                    message:
                        'A migration talks to the driver, never to this application — replaying it against an old database must not run today’s schema. Use the `db` handle migrate-mongo passes in.'
                }
            ]
        }
    },

    /**
     * The two project-local rules — defined in `eslint/rules/`, unit-tested in
     * `tests/unit/eslint/` — plus the try/catch restriction.
     *
     * Scoped to `src/`, deliberately: a test asserting what the reject envelope does with a
     * string is not shipping user-facing copy, and `tests/unit/infrastructure/http/response.test.ts` passes
     * a dozen literals for exactly that reason. Likewise a test may try/catch freely to assert on
     * what was thrown, and a CLI script's try around an optional read is its error handling.
     *
     * The `TryStatement` restriction is a speed bump, not a wall: production code prefers typed
     * verdicts and promise rejection into the pipeline's handlers, and each surviving try/catch
     * carries an `eslint-disable` whose description (enforced above) says what it is protecting.
     */
    {
        files: ['src/**/*.ts'],
        rules: {
            'local/no-hardcoded-user-text': 'error',
            'no-restricted-syntax': [
                'error',
                ...bannedDoubleCasts,
                {
                    selector: 'TryStatement',
                    message:
                        'try/catch in production code is for the rare spot where a throwing API has no safe wrapper and the failure has a local answer. Prefer returning a verdict or letting the rejection reach the pipeline’s handler; if this spot truly needs one, disable this rule on the line with a description of what is being contained.'
                }
            ]
        }
    },

    /**
     * Controllers, and the one rule that is only theirs.
     *
     * A fire-and-forget promise chain is legitimate in an adapter — `enqueueEmail` deliberately
     * does not block a response on SMTP — and is not legitimate in a request handler, which owes
     * the caller an answer and owes the system its cleanup. So the rule is scoped here rather
     * than run repo-wide, which is exactly the distinction the old source-scanning test drew by
     * only ever looking inside `controllers/` directories.
     */
    {
        files: ['src/modules/*/controllers/**/*.ts'],
        rules: {
            'local/controller-chain-must-catch': 'error'
        }
    },

    /**
     * `src/infrastructure/**` is the technical substrate: bootstrap, adapters,
     * observability and HTTP plumbing. It is the bottom of the dependency
     * graph and must never reach up into application code — that inversion is
     * what turned the old `src/utils/` into a dumping ground.
     *
     * `@modules/*` and `@kernel/*` are in the list because infrastructure sits below both. Without them
     * the rule was silently incomplete: `src/infrastructure/http/errors.ts` could import a domain service
     * and lint stayed quiet, while `docs/theory/layers.md` claimed the tier was enforced.
     */
    {
        files: ['src/infrastructure/**/*.ts'],
        rules: {
            'no-restricted-imports': [
                'error',
                {
                    patterns: ['@kernel/*', '@modules/*', '@app/*']
                }
            ]
        }
    },

    /**
     * A module's own specs, co-located under `src/modules/<name>/tests/`.
     *
     * Exempt from the boundary rule above, deliberately. That rule protects the RUNTIME import
     * graph — it is what makes "delete the folder, delete the domain" true. A spec is deleted with
     * the module it belongs to, so it cannot leave coupling behind that outlives either one, and
     * it legitimately needs two things production code must not have: its own module's internals
     * (a unit test of `service.ts` tests `service.ts`, not the barrel's view of it) and other
     * modules' `module.ts` manifests, because asserting cross-module cleanup means running the
     * real registry.
     *
     * Switched off here does NOT mean unenforced. The rule a spec must follow is relational —
     * what it may import depends on which module owns it — and `no-restricted-imports` only
     * matches file globs, so stating it here would take one near-identical block per module, with
     * a new one silently missing the day someone adds a domain. It is asserted instead by
     * `tests/cross-cutting/module-test-boundaries.test.ts`, which knows the owner of each spec and
     * allows exactly four things: its own module, a sibling's barrel, a sibling's manifest, and a
     * sibling's test helpers.
     */
    {
        files: ['src/modules/*/tests/**/*.ts'],
        rules: {
            'no-restricted-imports': 'off'
        }
    },

    /**
     * `src/kernel/**` IS the module system — the registry, the bus between modules, and the auth
     * port that keeps the shared guard out of a `users → account → users` cycle. It knows that
     * modules exist but never which ones. It may reach `infrastructure`; a single import of `@modules/<name>`
     * would make the mechanism depend on one of the things it is meant to carry, and "delete a
     * domain, delete a folder" would stop being true.
     *
     * The test for what belongs here: would this file still make sense in an app with no modules
     * at all? If yes it is `infrastructure`, however domain-free it looks — which is why the request
     * pipeline lives in `infrastructure/http/middlewares` and the queue consumers in `infrastructure/adapters`.
     */
    {
        files: ['src/kernel/**/*.ts'],
        rules: {
            'no-restricted-imports': [
                'error',
                {
                    patterns: ['@modules/*', '@app/*']
                }
            ]
        }
    },

    /**
     * Module boundaries.
     *
     * A module owns everything about its domain and exposes TWO surfaces, and no others:
     *
     *   `@modules/<name>`        the barrel — the runtime API a sibling may call
     *   `@modules/<name>/demo`  the demo fixtures a sibling's seeder may point at
     *
     * Reaching `@modules/<name>/service` or any other internal is what this rule exists to stop,
     * because the moment one happens the module stops being deletable.
     *
     * The second door is not a hole in the rule, it is the rest of it. Six modules have a
     * `demo.ts` and a seeded cart line has to name a seeded product, so the coupling is real and
     * has to go somewhere. With one entry point it went through the barrel — `products/index.ts`
     * published `SEED_PRODUCT_IDS` and `productFixtures` beside `productService`, which made "what
     * may a sibling import" and "what is the production API" stop being the same question. Naming
     * the demo path separately answers both at the call site, and lets the two edges be counted
     * apart: `tests/cross-cutting/module-test-boundaries.test.ts` asserts that nothing outside a
     * `demo.ts` ever takes one, so demo data cannot reach the runtime import graph.
     *
     * The pattern matches two segments or more, so both doors stay legal while everything below
     * them does not. A module reaches its own files relatively — `./service`,
     * `./controllers/get-products` — which no pattern here touches.
     *
     * `src/modules.ts` sits outside `src/modules/` and so is not covered: the registry is the one
     * caller allowed to import `@modules/<name>/module`, which is the manifest's whole purpose.
     *
     * The layer aliases (`@services/*`, `@controllers/*`, …) used to be banned here as well. They
     * were removed from `tsconfig.json` when the directories went, so an import naming one is
     * already an unresolved module — a TypeScript error before it is a lint one, and a rule that
     * cannot fire is a rule nobody can trust.
     */
    {
        files: ['src/modules/**/*.ts'],
        // Co-located specs are exempt — see the block after this one.
        ignores: ['src/modules/*/tests/**'],
        rules: {
            'no-restricted-imports': [
                'error',
                {
                    patterns: [
                        {
                            // The negation keeps `@modules/<name>/demo` legal while every other
                            // second segment stays banned. Two allowed shapes, no per-module list,
                            // so adding a domain needs no edit here.
                            group: ['@modules/*/*', '!@modules/*/demo'],
                            message:
                                'Import a sibling module through one of its two public paths: @modules/<name> for its runtime API, @modules/<name>/demo for its demo fixtures. Never its internals.'
                        },
                        {
                            group: ['@app/*'],
                            message:
                                'A module may not reach the app tier. `app` assembles the application and is allowed to know every domain; reaching back would point the arrow both ways. A guard every module needs belongs in @kernel behind a port — see kernel/authentication.ts.'
                        }
                    ]
                }
            ]
        }
    },

    /**
     * The domain layer: `src/modules/<name>/domain/**` — pure business rules.
     *
     * The only rule here about what a file may TOUCH rather than which tier it may reach. Plain
     * TypeScript over plain data: no framework, no tier, no sibling, and no `../` — the arrow
     * points inward only, so domain cannot read `../model` or `../repository`.
     *
     * The folder is optional; most modules have none.
     * See `docs/theory/domain-layer.md`.
     */
    {
        files: ['src/modules/*/domain/**/*.ts'],
        rules: {
            'no-restricted-imports': [
                'error',
                {
                    paths: [
                        {
                            name: 'mongoose',
                            message:
                                'The domain layer may not know how anything is stored. Take the data as a plain argument and let the repository do the reading.'
                        },
                        {
                            name: 'express',
                            message:
                                'The domain layer may not know it is being called over HTTP. Return a verdict; the controller turns it into a status code.'
                        }
                    ],
                    patterns: [
                        {
                            group: [
                                '@infrastructure/*',
                                '@kernel/*',
                                '@app/*',
                                '@modules/*',
                                '../*',
                                '../../*'
                            ],
                            message:
                                'The domain layer imports nothing but plain TypeScript — no tier, no sibling module, and none of the outer files of its own module. If a rule needs i18n it is returning a message where it should return a verdict; if it needs a repository it is doing the job of the service layer.'
                        }
                    ]
                }
            ]
        }
    },

    /**
     * The analytics event catalogue — the one namespace both repos write into.
     *
     * Every name here becomes a row in Umami, and a name is the only part of an event that a
     * dashboard groups by. `Cart_Item_Added` and `cart_item_added` are two different funnels in
     * that table, and nothing downstream can merge them back — so the convention is not a style
     * preference, it is the difference between one funnel and two.
     *
     * `snake_case` values, `SCREAMING_SNAKE` keys, and `noun_pastTenseVerb` for the shape of the
     * name itself. Only the first two are machine-checkable; the third is still prose, because no
     * selector knows a noun from a verb.
     *
     * Scoped to where names are AUTHORED: a module's own file, and the client's half in
     * `shared/contracts/analytics.frontend.ts`. The published catalogue is generated from these
     * and carries `DO NOT EDIT`, so linting it would only ever report a bug in the bundler.
     *
     * The `TryStatement` selector is repeated from the `src/**` block: `no-restricted-syntax`
     * does not merge across configs — the nearest match REPLACES the list — so leaving it out
     * here would silently lift the try/catch restriction for exactly these files.
     */
    {
        files: ['src/modules/*/analytics.ts', 'shared/contracts/analytics.frontend.ts'],
        rules: {
            'no-restricted-syntax': [
                'error',
                ...bannedDoubleCasts,
                {
                    selector:
                        'Property > Literal[value]:not([value=/^[a-z][a-z0-9]*(_[a-z0-9]+)*$/])',
                    message:
                        'An analytics event name is lower snake_case — `cart_item_added`. It is written verbatim into Umami, where a differently-spelled name is a separate funnel nothing can merge back.'
                },
                {
                    selector: 'Property > Identifier.key:not([name=/^[A-Z][A-Z0-9_]*$/])',
                    message:
                        'An analytics event constant is SCREAMING_SNAKE — `CART_ITEM_ADDED`. The published catalogue is sliced out of this declaration by matching that shape, so a differently-cased key is dropped from the frontend copy without failing anything.'
                },
                {
                    selector: 'TryStatement',
                    message:
                        'try/catch in production code is for the rare spot where a throwing API has no safe wrapper and the failure has a local answer. Prefer returning a verdict or letting the rejection reach the pipeline’s handler; if this spot truly needs one, disable this rule on the line with a description of what is being contained.'
                }
            ]
        }
    },

    /**
     * CLI tooling and seeders: node programs inside the `tsconfig` project, so they keep the
     * type-aware rules — but a script's interface is the terminal and its exit code, so
     * `no-console` would flag every line of output it exists to produce.
     */
    {
        files: ['scripts/**/*.ts', 'db/**/*.ts'],
        languageOptions: {
            globals: {
                ...globals.node
            }
        },
        rules: {
            'no-console': 'off'
        }
    },

    /**
     * The local rule definitions. In the `tsconfig` project so their tests can import them, but
     * an ESLint rule walks an untyped AST — `context` and every node come in as `any`, and typing
     * them properly means depending on `@types/estree` for two rules with their own unit tests.
     * The `no-unsafe-*` family follows `no-explicit-any` out for the same reason: every node
     * access in an AST walk is "unsafe" to a checker that has no ESTree types to check against.
     */
    {
        files: ['eslint/**/*.ts'],
        languageOptions: {
            globals: {
                ...globals.node
            }
        },
        rules: {
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/no-unsafe-assignment': 'off',
            '@typescript-eslint/no-unsafe-member-access': 'off',
            '@typescript-eslint/no-unsafe-call': 'off',
            '@typescript-eslint/no-unsafe-argument': 'off',
            '@typescript-eslint/no-unsafe-return': 'off'
        }
    },

    /**
     * Tool configs at the repo root, and the VitePress config: TypeScript, but OUTSIDE the
     * `tsconfig` project, so the type-aware program is switched off — for these files it would be
     * a parser error, not a finding. Everything syntax-level still applies.
     */
    {
        files: ['eslint.config.ts', 'orval.config.ts', 'docs/.vitepress/**/*.{ts,mts}'],
        extends: [tseslint.configs.disableTypeChecked],
        languageOptions: {
            globals: {
                ...globals.node
            }
        },
        rules: {
            'no-console': 'off',
            // `props`, `env`, `dir`: the VitePress/orval config surface spells its own keys.
            'unicorn/prevent-abbreviations': 'off'
        }
    },

    /**
     * Plain CommonJS tooling: jest's configs (a `.js` because the per-file coverage thresholds
     * inside need an explanation attached, and JSON cannot carry a comment), commitlint,
     * migrate-mongo's config and the migrations it replays. Outside the `tsconfig` project, so
     * the type-aware program is off; CommonJS, so the ESM-preference rules yield.
     */
    {
        files: [
            'jest.config.js',
            'jest.config.mutation.js',
            'commitlint.config.cjs',
            'migrate-mongo-config.js',
            'db/migrations/**/*.js'
        ],
        extends: [tseslint.configs.disableTypeChecked],
        languageOptions: {
            sourceType: 'commonjs',
            globals: {
                ...globals.node
            }
        },
        rules: {
            'no-console': 'off',
            '@typescript-eslint/no-require-imports': 'off',
            // `up(db, client)` is migrate-mongo's signature and `moduleNameMapper` is jest's key:
            // these files spell what their tools spell.
            'unicorn/prevent-abbreviations': 'off'
        }
    },

    /**
     * "Special" files names are better to be left untouched
     */
    {
        files: ['tests/**/*', '**/*.spec.ts', '**/*.test.ts', '**/*.d.ts'],
        rules: {
            'unicorn/filename-case': 'off',
            'unicorn/prevent-abbreviations': 'off'
        }
    },

    /**
     * Type-aware relief for test code, and only the relief the mocking idiom actually needs.
     *
     * `jest.mock` factories, `jest.requireActual`, and every `expect.any(...)` shape come back
     * `any` — the `no-unsafe-*` family would demand a cast ceremony on top of each one that
     * asserts nothing the test does not already assert. `no-unnecessary-condition` reads
     * `?.`-probing of a payload as redundant, but probing IS the assertion in a test; and a test
     * legitimately deletes `process.env` keys (`no-dynamic-delete`) and passes `() => {}` as the
     * callback it is not exercising (`no-empty-function`). Everything else — including the
     * deprecation and floating-promise checks — stays on.
     */
    {
        files: ['tests/**/*.ts', 'src/modules/*/tests/**/*.ts'],
        rules: {
            '@typescript-eslint/no-unsafe-assignment': 'off',
            '@typescript-eslint/no-unsafe-member-access': 'off',
            '@typescript-eslint/no-unsafe-call': 'off',
            '@typescript-eslint/no-unsafe-argument': 'off',
            '@typescript-eslint/no-unsafe-return': 'off',
            '@typescript-eslint/no-unnecessary-condition': 'off',
            '@typescript-eslint/no-dynamic-delete': 'off',
            '@typescript-eslint/no-empty-function': 'off',
            // `expect(mock.method)` hands the method around unbound by design,
            // and a test try/catches to assert on what was thrown. The double-cast ban stays:
            // tests are where that idiom bred.
            '@typescript-eslint/unbound-method': 'off',
            'no-restricted-syntax': ['error', ...bannedDoubleCasts]
        }
    },
    {
        files: ['**/*.d.ts'],
        rules: {
            '@typescript-eslint/naming-convention': 'off'
        }
    },

    /**
     * Jest's globals, for the standalone suites and the co-located module specs alike.
     */
    {
        files: ['tests/**/*', 'src/modules/*/tests/**/*'],

        languageOptions: {
            globals: {
                ...globals.jest
            }
        }
    },

    /**
     * Disable conflicts with prettier
     */
    configPrettier
);
