/**
 * @module
 * Whether a path a comment cites still exists in this repo — the shared machinery behind
 * `check-references.ts` (every `docs/*.md` page) and `local/comment-links`'s `.ts`/`.tsx` half
 * (every source comment), so the two checkers agree on what counts as a real path instead of each
 * growing its own opinion of one.
 *
 * The two callers still differ on purpose: a markdown page resolves a `./relative` token against
 * VitePress's own routing and a bare `boilerplate-vue-frontend/...` token against the paired repo,
 * neither of which apply to a `.ts` comment — so those two policies stay with `check-references.ts`
 * and `eslint/rules/comment-links.ts` respectively, each on top of the primitives here.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import path from 'node:path';

/** The repo root, two levels up from `scripts/docs/`. */
export const ROOT = path.join(__dirname, '..', '..');

/**
 * Paths that legitimately do not exist in a clean checkout, each with the reason it is exempt.
 * Prefix match. An entry here is an argument, not a mute button — a path with no reason to be
 * absent belongs in the findings.
 */
export const ALLOWED: { prefix: string; reason: string }[] = [
    { prefix: 'reports/', reason: 'written by a test/mutation run, absent until one happens' },
    { prefix: 'coverage/', reason: 'written by test:unit:coverage, absent until one happens' },
    { prefix: 'node_modules/', reason: 'a dependency path, cited to locate one — not our tree' },
    { prefix: 'api/', reason: 'generated by gen:api, gitignored' },
    { prefix: 'src/types/asyncapi.generated.ts', reason: 'generated by gen:asyncapi, gitignored' },
    { prefix: 'asyncapi.generated.ts', reason: 'the same file, cited by its bare name' },
    {
        prefix: 'stryker-incremental.json',
        reason: "Stryker's own incremental cache under reports/, cited by its bare name"
    },
    {
        prefix: 'mutation-baseline-deep.json',
        reason: 'written by test:mutation:deep:baseline; the nightly scope is not committed'
    },
    { prefix: 'contract.bruno.yml', reason: 'a client collection, generated by contracts:bundle' },
    {
        prefix: 'contract.insomnia.json',
        reason: 'a client collection, generated by contracts:bundle'
    },
    {
        prefix: 'contract.mockoon.json',
        reason: 'a client collection, generated by contracts:bundle'
    },
    {
        prefix: 'contract.postman.json',
        reason: 'a client collection, generated by contracts:bundle'
    },
    { prefix: '.env', reason: 'a deployment writes it; only .env-example is tracked' },
    { prefix: 'docs/.vitepress/dist/', reason: 'the built site, written by docs:build' },
    { prefix: 'docs/.vitepress/cache/', reason: "vitepress's own scratch space" },
    { prefix: 'dist/', reason: 'the build output, written by build' }
];

/**
 * Whether an allowlist entry covers this token — the directory itself as well as what is under
 * it, since a page naming `reports` and a page naming `reports/mutation/` make the same claim.
 */
export const allowed = (token: string): boolean =>
    ALLOWED.some(({ prefix }) => token === prefix.replace(/\/$/, '') || token.startsWith(prefix));

/**
 * A filename: a non-empty stem and a known extension. `package.json` qualifies with no `/` in it;
 * a bare `.ts` naming the language does not — and neither does a dot-led suffix CONVENTION like
 * `.visual.cy.ts`, which is what `claimsAPath` below relies on to leave it alone.
 */
export const FILENAME =
    /^[^.][^/]*\.(ts|tsx|js|cjs|mjs|json|ya?ml|md|vue|sql|sh|css|scss|conf|lock)$/;

/**
 * Characters that mean this span is prose, a glob, a type or a command — never one real path.
 * `…` included: eliding the middle of a path is illustrating a shape, not citing a file. `<`/`>`
 * included: a `<placeholder>` segment is the author saying "this part varies", not naming one.
 */
export const NOT_A_PATH = /[\s!"'()*,<=>?[\]`{|}…]/;

/**
 * Every tail of every path git tracks, plus every directory on the way to one and ITS tails.
 *
 * Precomputed rather than matched with `endsWith` per token: a sweep asks thousands of questions
 * against thousands of files across a dozen candidate spellings each, and a set lookup turns that
 * from tens of millions of string comparisons into one hash per question.
 */
export const trackedTargets = (root: string): { targets: Set<string>; roots: Set<string> } => {
    const files = execFileSync('git', ['ls-files'], { cwd: root, encoding: 'utf8' })
        .split('\n')
        .filter(Boolean);
    const targets = new Set<string>();
    // What actually sits at the root, taken from the file list rather than from `targets` — that
    // set holds every TAIL, so `orders/model.ts` would make `orders` look top-level.
    const roots = new Set(files.map((file) => file.split('/')[0]));

    const addTails = (candidate: string) => {
        const segments = candidate.split('/');
        for (let index = 0; index < segments.length; index += 1)
            targets.add(segments.slice(index).join('/'));
    };

    for (const file of files) {
        addTails(file);
        // Directories are claims too — `src/infrastructure/` names no file and must still resolve.
        const segments = file.split('/');
        for (let index = 1; index < segments.length; index += 1)
            addTails(segments.slice(0, index).join('/'));
    }

    return { targets, roots };
};

/**
 * How a citation may spell a path it means without an extension. Both callers cite TypeScript
 * module specifiers as often as files — `@api` resolves to `contracts/rest/index`, and
 * `src/infrastructure/http/request` names `request.ts` — so an extensionless token is checked
 * against what it would import.
 */
export const SPELLINGS = [
    '',
    '.ts',
    '.tsx',
    '.js',
    '.vue',
    '.json',
    '.yaml',
    '.yml',
    '.md',
    '/index.ts',
    '/index.js'
];

/** Whether any spelling of this token is the tail of something git tracks. */
export const resolves = (targets: Set<string>, token: string): boolean =>
    SPELLINGS.some((suffix) => targets.has(token + suffix));

/**
 * Whether this token is claiming a path in THIS repo at all.
 *
 * A slash alone does not mean a path — `text/event-stream`, `grafana/loki`, `prom/prometheus`,
 * `unicorn/prevent-abbreviations` and `try/catch` are all a MIME type, two container images, a
 * lint rule and a language feature. So a token qualifies two ways only: it ends in a real
 * filename, or its first segment is something that actually sits at the root of the repo. The
 * second half is read from the tree rather than listed, so a new top-level directory needs no
 * edit here.
 */
export const claimsAPath = (roots: Set<string>, token: string): boolean =>
    // Anchored on the LAST segment, so `.visual.cy.ts` — a suffix convention, not a file — is not
    // read as one because a filename happens to sit inside it.
    FILENAME.test(token.split('/').at(-1) ?? '') || roots.has(token.split('/')[0]);

/**
 * `tsconfig`'s path aliases, as `@modules/` → `src/modules/`, read rather than transcribed — a
 * second copy of this table is exactly the kind of fact that goes stale silently.
 *
 * Comments are stripped before parsing: `tsconfig.json` is JSONC, and `JSON.parse` refuses them.
 */
export const readAliases = (): { prefix: string; target: string }[] => {
    const raw = readFileSync(path.join(ROOT, 'tsconfig.json'), 'utf8').replaceAll(
        /^\s*\/\/.*$/gm,
        ''
    );
    const paths = (JSON.parse(raw) as { compilerOptions?: { paths?: Record<string, string[]> } })
        .compilerOptions?.paths;

    return Object.entries(paths ?? {}).map(([alias, [target]]) => ({
        prefix: alias.replace(/\*$/, ''),
        target: target.replace(/^\.\//, '').replace(/\*$/, '')
    }));
};

/**
 * Rewrite a `@alias/…` token to the path it actually names, or drop it when no alias claims it —
 * an unclaimed `@scope/name` is an npm package, and this repo's tree says nothing about it.
 */
export const throughAliases = (
    aliases: { prefix: string; target: string }[],
    token: string
): string | undefined => {
    if (!token.startsWith('@')) return token;

    // A wildcard alias (`@modules/*`) keeps its trailing slash and matches a prefix; a bare one
    // (`@types`) must match whole, or `@types` would claim `@typescript-eslint/parser`.
    const alias = aliases.find((entry) =>
        entry.prefix.endsWith('/') ? token.startsWith(entry.prefix) : token === entry.prefix
    );
    if (!alias) return undefined;

    return alias.target + token.slice(alias.prefix.length);
};
