import type { Request, Response } from 'express';
import type { ParamsDictionary } from 'express-serve-static-core';
import { z } from 'zod';
import { coerceStringArray } from '@guebbit/js-toolkit';
import {
    SearchProductsBody,
    searchProductsBodyMinPriceMin,
    searchProductsBodyMaxPriceMin
} from '@api/schemas.zod';
import { productService } from '../service';
import { successResponse } from '@infrastructure/http/response';
import { readInput } from '@infrastructure/http/request';
import { pageSchema, pageSizeSchema } from '@infrastructure/http/schemas';
import type { SearchProductsRequest } from '@types';
import { emitAnalyticsEvent, buildAnalyticsBase } from '@infrastructure/observability/analytics';
import { productsAnalyticsEvents } from '../analytics';
import { catchAs, parseBody } from '@infrastructure/http/controller';

/**
 * Query parameters generated by the search form (they are the same as SearchOrdersRequest keys)
 */
export type GetProductsQuery = Partial<Record<keyof SearchProductsRequest, string>>;

/**
 * Built on the orval-generated SearchProductsBody (kept in sync with
 * openapi.yaml); page/pageSize/minPrice/maxPrice are coerced from strings
 * since GET requests carry them as query-string text, not JSON numbers.
 *
 * `page`/`pageSize` come from `@infrastructure/http/schemas` so all four search endpoints agree on what a
 * legal one is; absent stays absent, because `normalizePagination` owns the defaults.
 */
const searchProductsQuerySchema = SearchProductsBody.extend({
    page: pageSchema,
    pageSize: pageSizeSchema,
    minPrice: z.preprocess(
        (value) => (value === '' || value === null ? undefined : value),
        z.coerce.number().min(searchProductsBodyMinPriceMin).optional()
    ),
    maxPrice: z.preprocess(
        (value) => (value === '' || value === null ? undefined : value),
        z.coerce.number().min(searchProductsBodyMaxPriceMin).optional()
    )
});

/**
 * Query parameters that change this endpoint's answer, and therefore its cache key.
 *
 * Derived from the schema rather than hand-listed, because the two must not drift: a parameter
 * the controller reads but the key omits would let two different requests share one cached
 * response. Anything outside this list is stripped by the validator and changes nothing.
 */
export const searchProductsKeyParameters = Object.keys(searchProductsQuerySchema.shape);

/**
 * GET /products
 * POST /products/search
 * List/search products via query parameters or request body.
 * Admin sees all products (including inactive/deleted); public sees only active ones.
 */
export const getProducts = (
    request: Request<ParamsDictionary, unknown, SearchProductsRequest, GetProductsQuery>,
    response: Response
) => {
    // One declaration instead of a per-field assembly — see docs/theory/request-input.md.
    const input = readInput(request, { surface: 'search', ids: ['id'] });

    const parsed = parseBody(
        searchProductsQuerySchema,
        {
            ...input,
            // OpenAPI currently models category/tag as single-value filters; if arrays/CSV are provided we pick the first one.
            category: coerceStringArray(input.category)[0],
            tag: coerceStringArray(input.tag)[0]
        },
        response
    );
    if (!parsed) return;

    const { text } = parsed;

    return productService
        .search(parsed, request.authContext?.admin === true)
        .then((result) => {
            emitAnalyticsEvent({
                ...buildAnalyticsBase(request),
                event: productsAnalyticsEvents.PRODUCTS_SEARCHED,
                properties: {
                    text,
                    // Reported from the result rather than the request: the caller may not have
                    // asked for a page at all, and `normalizePagination` decides what they got.
                    page: result.meta.page,
                    pageSize: result.meta.pageSize,
                    result_count: result.items.length
                }
            });
            successResponse(response, result);
        })
        .catch(catchAs(response, 'getProducts'));
};
