import type { Request, Response } from 'express';
import { productService } from '@services/products';
import { rejectResponse, successResponse } from '@utils/response';
import { extractId, extractPagination } from '@utils/helpers-request';
import type { SearchProductsRequest } from '@types';
import type { CastError } from 'mongoose';

/**
 * Query parameters generated by the search form (they are the same as SearchOrdersRequest keys)
 */
export type IGetProductsQuery = Partial<Record<keyof SearchProductsRequest, string>>;

/**
 * GET /products
 * POST /products/search
 * List/search products via query parameters or request body.
 * Admin sees all products (including inactive/deleted); public sees only active ones.
 */
export const getProducts = (
    request: Request<{ id?: string }, unknown, SearchProductsRequest, IGetProductsQuery>,
    response: Response
) => {
    const { page, pageSize } = extractPagination({
        page: request.body?.page ?? request.query.page,
        pageSize: request.body?.pageSize ?? request.query.pageSize
    });

    const minPriceRaw = request.body?.minPrice ?? request.query.minPrice;
    const maxPriceRaw = request.body?.maxPrice ?? request.query.maxPrice;

    return productService
        .search(
            {
                id: extractId(request.params.id, request.body?.id, request.query.id),
                page,
                pageSize,
                text: request.body?.text ?? request.query.text,
                minPrice: minPriceRaw ? Number(minPriceRaw) : undefined,
                maxPrice: maxPriceRaw ? Number(maxPriceRaw) : undefined
            },
            request.user?.admin === true
        )
        .then((result) => {
            console.log("AAAAAAAAAAAa", result)
            successResponse(response, result);
        })
        .catch((error: CastError) => {
            rejectResponse(response, 500, 'Unknown Error', [error.message]);
        });
};
