import { Request, Response, NextFunction } from "express";
import type { CastError } from "mongoose";
import { databaseErrorConverter } from "../../utils/error-helpers";
import type { SearchProductsRequest } from "@api/api";
import * as ProductService from "../../services/products";

/**
 * Url parameters generated by the search form (they are the same)
 */
export type IGetAllProductsParameters = Partial<Record<keyof SearchProductsRequest, string>>;

/**
 * Get all products
 *
 * @param request
 * @param response
 * @param next
 */
export const pageAllProducts = async (request: Request & {
    params: IGetAllProductsParameters
}, response: Response, next: NextFunction) =>
    ProductService.search(
        {
            ...request.params,
            minPrice: request.params?.minPrice ? Number.parseInt(request.params.minPrice) : undefined,
            maxPrice: request.params?.maxPrice ? Number.parseInt(request.params.maxPrice) : undefined,
            page: Number.parseInt(request.params.page ?? "1"),
            pageSize: Number.parseInt(process.env.NODE_SETTINGS_PAGINATION_PAGE_SIZE ?? "10"),
        },
        request.session.user?.admin
    )
        .then(async ({ items, meta }) =>
            response.render('products/search', {
                pageMetaTitle: 'All Products',
                pageMetaLinks: [
                    "/css/product.css"
                ],
                productList: items,
                productsTotal: meta.totalItems,
                pageCurrent: meta.page,
                pageTotal: meta.totalPages,
                search: { page: meta.page, pageSize: meta.pageSize },
            })
        )
        .catch((error: Error | CastError) => next(databaseErrorConverter(error)));