import type { Request, Response, NextFunction } from "express";
import type { DatabaseError, Includeable, ValidationError, WhereOptions } from "sequelize";
import Products from "../../models/products";
import { databaseErrorConverter } from "../../utils/error-helpers";
import CartItems from "../../models/cart-items";
import type {
    SearchOrdersRequest,
    ProductsResponse,
} from "@api/api";

/**
 * Url parameters generated by the search form (they are the same)
 */
export type IGetAllProductsParameters = Partial<Record<keyof SearchOrdersRequest, string>>;

/**
 * Get all products page
 *
 * @param request
 * @param response
 * @param next
 */
export const pageAllProducts = (request: Request & {
    params: IGetAllProductsParameters
}, response: Response, next: NextFunction) =>
    Products.search(
        {
            ...request.params,
            minPrice: request.params?.minPrice ? Number.parseInt(request.params.minPrice as string) : undefined,
            maxPrice: request.params?.maxPrice ? Number.parseInt(request.params.maxPrice as string) : undefined,
            page: Number.parseInt(request.params.page ?? "1"),
            pageSize: Number.parseInt(process.env.NODE_SETTINGS_PAGINATION_PAGE_SIZE ?? "10"),
        },
        request.session.user?.admin
    )
        .then(async ({ items, meta }) =>
            response.render('products/search', {
                pageMetaTitle: 'All Products',
                pageMetaLinks: [
                    "/css/product.css"
                ],
                productList: items,
                productsTotal: meta.totalItems,
                pageCurrent: meta.page,
                pageTotal: meta.totalPages,
                search: { page: meta.page, pageSize: meta.pageSize },
            })
        )
        .catch((error: Error | ValidationError | DatabaseError) => next(databaseErrorConverter(error)))