/* eslint-disable @typescript-eslint/naming-convention */
// GENERATED — do not edit manually.
// Source: asyncapi.yaml  |  Regenerate: npm run genasyncapi

// Channel name constants (canonical identifiers from asyncapi.yaml)

/* SSE observability channel names */
export const OBSERVABILITY_CHANNELS = {
    METRICS_SNAPSHOT: 'observability.metrics.snapshot',
    METRICS_UPDATED: 'observability.metrics.updated',
    HEARTBEAT: 'observability.heartbeat'
} as const;

/* Ecommerce domain event channel names */
export const ECOMMERCE_CHANNELS = {
    CART_CHECKED_OUT: 'ecommerce.cart.checked_out'
} as const;

/* RabbitMQ worker queue channel names */
export const WORKER_CHANNELS = {
    EMAIL_SEND: 'worker.email.send',
    PDF_GENERATE: 'worker.pdf.generate'
} as const;

/* Redis pub/sub cache channel names */
export const CACHE_CHANNELS = {
    TAGS_INVALIDATED: 'cache.tags.invalidated'
} as const;

/* Union of all SSE observability channel names */
export type TObservabilityChannel =
    (typeof OBSERVABILITY_CHANNELS)[keyof typeof OBSERVABILITY_CHANNELS];

/* Union of all ecommerce channel names */
export type TEcommerceChannel = (typeof ECOMMERCE_CHANNELS)[keyof typeof ECOMMERCE_CHANNELS];

/* Union of all worker queue channel names */
export type TWorkerChannel = (typeof WORKER_CHANNELS)[keyof typeof WORKER_CHANNELS];

/* Union of all cache pub/sub channel names */
export type TCacheChannel = (typeof CACHE_CHANNELS)[keyof typeof CACHE_CHANNELS];

// TypeScript models generated by @asyncapi/modelina from asyncapi.yaml

export interface IObservabilityMetricsPayload {
    timestamp: string;
    uptimeSeconds: number;
    memory: anonymous_schema_3;
    http: anonymous_schema_8;
    realtime: anonymous_schema_11;
}
export interface anonymous_schema_3 {
    rss: number;
    heapUsed: number;
    heapTotal: number;
    external: number;
}
export interface anonymous_schema_8 {
    totalRequests: number;
    totalErrors: number;
}
export interface anonymous_schema_11 {
    sseClients: number;
}
export interface ICartCheckedOutEvent {
    eventName: anonymous_schema_13;
    eventId: string;
    occurredAt: string;
    cartId: string;
    userId: string;
    orderId: string;
    itemCount: number;
}
export type anonymous_schema_13 = 'ecommerce.cart.checked_out';
export interface IEmailJobPayload {
    request: anonymous_schema_20;
    from?: string;
    templateName: string;
    data: Record<string, unknown>;
}
export interface anonymous_schema_20 {
    to: string;
    subject?: string;
    text?: string;
    html?: string;
}
export interface IPdfJobPayload {
    templatePath: string;
    templateData: Record<string, unknown>;
    outputPath: string;
}
export interface ICacheTagsInvalidatedPayload {
    tags: string[];
    origin: string;
    timestamp: string;
}
