/**
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract. Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import localVarRequest from 'request';
import http from 'node:http';

/* tslint:disable:no-unused-locals */
import { AuthTokens } from '../model/authTokens';
import { ErrorResponse } from '../model/errorResponse';
import { LoginRequest } from '../model/loginRequest';
import { MessageResponse } from '../model/messageResponse';
import { PasswordResetConfirmRequest } from '../model/passwordResetConfirmRequest';
import { PasswordResetRequest } from '../model/passwordResetRequest';
import { RefreshTokenResponse } from '../model/refreshTokenResponse';
import { User } from '../model/user';
import { ValidationErrorResponse } from '../model/validationErrorResponse';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

const defaultBasePath = 'http://localhost:3000';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum AuthApiApiKeys {}

export class AuthApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders: any = {};
    protected _useQuerystring: boolean = false;

    protected authentications = {
        default: <Authentication>new VoidAuth(),
        bearerAuth: new HttpBearerAuth()
    };

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername;
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: AuthApiApiKeys, value: string) {
        (this.authentications as any)[AuthApiApiKeys[key]].apiKey = value;
    }

    set accessToken(accessToken: string | (() => string)) {
        this.authentications.bearerAuth.accessToken = accessToken;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Completes the password-reset flow. Validates the one-time reset token issued by `/account/reset` and, if valid, updates the user\'s password to the supplied value.
     * @param passwordResetConfirmRequest
     */
    public async confirmPasswordReset(
        passwordResetConfirmRequest: PasswordResetConfirmRequest,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: MessageResponse }> {
        const localVariablePath = this.basePath + '/account/reset-confirm';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'passwordResetConfirmRequest' is not null or undefined
        if (passwordResetConfirmRequest === null || passwordResetConfirmRequest === undefined) {
            throw new Error(
                'Required parameter passwordResetConfirmRequest was null or undefined when calling confirmPasswordReset.'
            );
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(
                passwordResetConfirmRequest,
                'PasswordResetConfirmRequest'
            )
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MessageResponse }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'MessageResponse');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Removes all expired tokens (refresh, password-reset, etc.) from every user record in the database. Restricted to administrators.
     * @summary Remove expired tokens
     */
    public async deleteExpiredTokens(
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: MessageResponse }> {
        const localVariablePath = this.basePath + '/account/tokens/expired';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.bearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() =>
                this.authentications.bearerAuth.applyToRequest(localVariableRequestOptions)
            );
        }
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MessageResponse }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'MessageResponse');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Authenticates a user with email and password credentials. On success, returns a JWT access token that must be passed as a Bearer token on subsequent authenticated requests.
     * @summary Login
     * @param loginRequest
     */
    public async login(
        loginRequest: LoginRequest,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: AuthTokens }> {
        const localVariablePath = this.basePath + '/account/login';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'loginRequest' is not null or undefined
        if (loginRequest === null || loginRequest === undefined) {
            throw new Error(
                'Required parameter loginRequest was null or undefined when calling login.'
            );
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(loginRequest, 'LoginRequest')
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: AuthTokens }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'AuthTokens');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Logs out the authenticated user from ALL devices by removing all refresh tokens from the database and clearing authentication cookies.
     * @summary Logout from all devices
     */
    public async logoutAll(
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: MessageResponse }> {
        const localVariablePath = this.basePath + '/account/logout-all';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.bearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() =>
                this.authentications.bearerAuth.applyToRequest(localVariableRequestOptions)
            );
        }
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MessageResponse }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'MessageResponse');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Creates a new short-lived access token using a refresh token. The refresh token can be provided as a query parameter, path parameter, or retrieved from the `jwt` cookie.
     * @summary Refresh access token
     */
    public async refreshToken(
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: RefreshTokenResponse }> {
        const localVariablePath = this.basePath + '/account/refresh';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: RefreshTokenResponse }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'RefreshTokenResponse');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Creates a new short-lived access token using a refresh token provided in the URL path.
     * @summary Refresh access token with token in path
     * @param token Refresh token
     */
    public async refreshTokenWithPath(
        token: string,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: RefreshTokenResponse }> {
        const localVariablePath =
            this.basePath +
            '/account/refresh/{token}'.replace(
                '{' + 'token' + '}',
                encodeURIComponent(String(token))
            );
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'token' is not null or undefined
        if (token === null || token === undefined) {
            throw new Error(
                'Required parameter token was null or undefined when calling refreshTokenWithPath.'
            );
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: RefreshTokenResponse }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'RefreshTokenResponse');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Initiates the password-reset flow by sending a one-time reset token to the provided email address. The token should then be submitted to `/account/reset-confirm`.
     * @param passwordResetRequest
     */
    public async requestPasswordReset(
        passwordResetRequest: PasswordResetRequest,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: MessageResponse }> {
        const localVariablePath = this.basePath + '/account/reset';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'passwordResetRequest' is not null or undefined
        if (passwordResetRequest === null || passwordResetRequest === undefined) {
            throw new Error(
                'Required parameter passwordResetRequest was null or undefined when calling requestPasswordReset.'
            );
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(passwordResetRequest, 'PasswordResetRequest')
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MessageResponse }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'MessageResponse');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Registers a new user account with optional image upload. Returns the newly created user profile on success.
     * @summary Signup
     * @param email
     * @param username
     * @param password
     * @param passwordConfirm
     * @param imageUpload Optional user profile image
     */
    public async signup(
        email: string,
        username: string,
        password: string,
        passwordConfirm: string,
        imageUpload?: RequestFile,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: User }> {
        const localVariablePath = this.basePath + '/account/signup';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'email' is not null or undefined
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling signup.');
        }

        // verify required parameter 'username' is not null or undefined
        if (username === null || username === undefined) {
            throw new Error(
                'Required parameter username was null or undefined when calling signup.'
            );
        }

        // verify required parameter 'password' is not null or undefined
        if (password === null || password === undefined) {
            throw new Error(
                'Required parameter password was null or undefined when calling signup.'
            );
        }

        // verify required parameter 'passwordConfirm' is not null or undefined
        if (passwordConfirm === null || passwordConfirm === undefined) {
            throw new Error(
                'Required parameter passwordConfirm was null or undefined when calling signup.'
            );
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        let localVariableUseFormData = false;

        if (email !== undefined) {
            localVariableFormParameters['email'] = ObjectSerializer.serialize(email, 'string');
        }

        if (username !== undefined) {
            localVariableFormParameters['username'] = ObjectSerializer.serialize(
                username,
                'string'
            );
        }

        if (password !== undefined) {
            localVariableFormParameters['password'] = ObjectSerializer.serialize(
                password,
                'string'
            );
        }

        if (passwordConfirm !== undefined) {
            localVariableFormParameters['passwordConfirm'] = ObjectSerializer.serialize(
                passwordConfirm,
                'string'
            );
        }

        if (imageUpload !== undefined) {
            localVariableFormParameters['imageUpload'] = imageUpload;
        }
        localVariableUseFormData = true;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: User }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'User');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
}
