/**
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract. Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import localVarRequest from 'request';
import http from 'node:http';

/* tslint:disable:no-unused-locals */
import { DeleteUserRequest } from '../model/deleteUserRequest';
import { ErrorResponse } from '../model/errorResponse';
import { MessageResponse } from '../model/messageResponse';
import { SearchUsersRequest } from '../model/searchUsersRequest';
import { User } from '../model/user';
import { UsersResponse } from '../model/usersResponse';
import { ValidationErrorResponse } from '../model/validationErrorResponse';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

const defaultBasePath = 'http://localhost:3000';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum UsersApiApiKeys {}

export class UsersApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders: any = {};
    protected _useQuerystring: boolean = false;

    protected authentications = {
        default: <Authentication>new VoidAuth(),
        bearerAuth: new HttpBearerAuth()
    };

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername;
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: UsersApiApiKeys, value: string) {
        (this.authentications as any)[UsersApiApiKeys[key]].apiKey = value;
    }

    set accessToken(accessToken: string | (() => string)) {
        this.authentications.bearerAuth.accessToken = accessToken;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Creates a new user account with the supplied email, username, and password. Optional image can be uploaded.
     * @summary Create user
     * @param email
     * @param username
     * @param password
     * @param admin
     * @param active
     * @param imageUpload Optional user profile image
     */
    public async createUser(
        email: string,
        username: string,
        password: string,
        admin?: boolean,
        active?: boolean,
        imageUpload?: RequestFile,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: User }> {
        const localVariablePath = this.basePath + '/users';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'email' is not null or undefined
        if (email === null || email === undefined) {
            throw new Error(
                'Required parameter email was null or undefined when calling createUser.'
            );
        }

        // verify required parameter 'username' is not null or undefined
        if (username === null || username === undefined) {
            throw new Error(
                'Required parameter username was null or undefined when calling createUser.'
            );
        }

        // verify required parameter 'password' is not null or undefined
        if (password === null || password === undefined) {
            throw new Error(
                'Required parameter password was null or undefined when calling createUser.'
            );
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        let localVariableUseFormData = false;

        if (email !== undefined) {
            localVariableFormParameters['email'] = ObjectSerializer.serialize(email, 'string');
        }

        if (username !== undefined) {
            localVariableFormParameters['username'] = ObjectSerializer.serialize(
                username,
                'string'
            );
        }

        if (password !== undefined) {
            localVariableFormParameters['password'] = ObjectSerializer.serialize(
                password,
                'string'
            );
        }

        if (admin !== undefined) {
            localVariableFormParameters['admin'] = ObjectSerializer.serialize(admin, 'boolean');
        }

        if (active !== undefined) {
            localVariableFormParameters['active'] = ObjectSerializer.serialize(active, 'boolean');
        }

        if (imageUpload !== undefined) {
            localVariableFormParameters['imageUpload'] = imageUpload;
        }
        localVariableUseFormData = true;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.bearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() =>
                this.authentications.bearerAuth.applyToRequest(localVariableRequestOptions)
            );
        }
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: User }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'User');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Deletes the user identified by the `id` field in the request body. Set `hardDelete` to `true` to permanently remove the record.
     * @summary Delete user
     * @param deleteUserRequest
     */
    public async deleteUser(
        deleteUserRequest: DeleteUserRequest,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: MessageResponse }> {
        const localVariablePath = this.basePath + '/users';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'deleteUserRequest' is not null or undefined
        if (deleteUserRequest === null || deleteUserRequest === undefined) {
            throw new Error(
                'Required parameter deleteUserRequest was null or undefined when calling deleteUser.'
            );
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(deleteUserRequest, 'DeleteUserRequest')
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.bearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() =>
                this.authentications.bearerAuth.applyToRequest(localVariableRequestOptions)
            );
        }
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MessageResponse }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'MessageResponse');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Deletes the user identified by `{id}` in the path. Pass the `hardDelete` query parameter as `true` to permanently remove the record. Functionally equivalent to `DELETE /users`.
     * @summary Delete user
     * @param id Resource identifier
     * @param hardDelete
     */
    public async deleteUserById(
        id: string,
        hardDelete?: boolean,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: MessageResponse }> {
        const localVariablePath =
            this.basePath + '/users/{id}'.replace('{' + 'id' + '}', encodeURIComponent(String(id)));
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error(
                'Required parameter id was null or undefined when calling deleteUserById.'
            );
        }

        if (hardDelete !== undefined) {
            localVariableQueryParameters['hardDelete'] = ObjectSerializer.serialize(
                hardDelete,
                'boolean'
            );
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.bearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() =>
                this.authentications.bearerAuth.applyToRequest(localVariableRequestOptions)
            );
        }
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MessageResponse }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'MessageResponse');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Returns the full profile of the user identified by `{id}`. Functionally equivalent to `GET /users?id={id}`.
     * @summary User details
     * @param id Resource identifier
     */
    public async getUserById(
        id: string,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: User }> {
        const localVariablePath =
            this.basePath + '/users/{id}'.replace('{' + 'id' + '}', encodeURIComponent(String(id)));
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error(
                'Required parameter id was null or undefined when calling getUserById.'
            );
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.bearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() =>
                this.authentications.bearerAuth.applyToRequest(localVariableRequestOptions)
            );
        }
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: User }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'User');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Returns a paginated list of user accounts.
     * @summary List users (paginated)
     * @param id
     * @param page 1-based page index
     * @param pageSize
     * @param text
     * @param email
     * @param username
     * @param active
     */
    public async listUsers(
        id?: string,
        page?: number,
        pageSize?: number,
        text?: string,
        email?: string,
        username?: string,
        active?: boolean,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: UsersResponse }> {
        const localVariablePath = this.basePath + '/users';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        if (id !== undefined) {
            localVariableQueryParameters['id'] = ObjectSerializer.serialize(id, 'string');
        }

        if (page !== undefined) {
            localVariableQueryParameters['page'] = ObjectSerializer.serialize(page, 'number');
        }

        if (pageSize !== undefined) {
            localVariableQueryParameters['pageSize'] = ObjectSerializer.serialize(
                pageSize,
                'number'
            );
        }

        if (text !== undefined) {
            localVariableQueryParameters['text'] = ObjectSerializer.serialize(text, 'string');
        }

        if (email !== undefined) {
            localVariableQueryParameters['email'] = ObjectSerializer.serialize(email, 'string');
        }

        if (username !== undefined) {
            localVariableQueryParameters['username'] = ObjectSerializer.serialize(
                username,
                'string'
            );
        }

        if (active !== undefined) {
            localVariableQueryParameters['active'] = ObjectSerializer.serialize(active, 'boolean');
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.bearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() =>
                this.authentications.bearerAuth.applyToRequest(localVariableRequestOptions)
            );
        }
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: UsersResponse }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'UsersResponse');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Searches and filters users via a JSON request body. Functionally equivalent to `GET /users` with query parameters
     * @summary Search users (DTO-friendly)
     * @param searchUsersRequest
     */
    public async searchUsers(
        searchUsersRequest: SearchUsersRequest,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: UsersResponse }> {
        const localVariablePath = this.basePath + '/users/search';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'searchUsersRequest' is not null or undefined
        if (searchUsersRequest === null || searchUsersRequest === undefined) {
            throw new Error(
                'Required parameter searchUsersRequest was null or undefined when calling searchUsers.'
            );
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        const localVariableUseFormData = false;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(searchUsersRequest, 'SearchUsersRequest')
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.bearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() =>
                this.authentications.bearerAuth.applyToRequest(localVariableRequestOptions)
            );
        }
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: UsersResponse }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'UsersResponse');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Updates an existing user\'s email or password. Optional image can be uploaded.
     * @summary Edit user
     * @param id Resource identifier
     * @param email
     * @param password
     * @param imageUpload Optional user profile image
     */
    public async updateUser(
        id: string,
        email?: string,
        password?: string,
        imageUpload?: RequestFile,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: User }> {
        const localVariablePath = this.basePath + '/users';
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateUser.');
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        let localVariableUseFormData = false;

        if (id !== undefined) {
            localVariableFormParameters['id'] = ObjectSerializer.serialize(id, 'string');
        }

        if (email !== undefined) {
            localVariableFormParameters['email'] = ObjectSerializer.serialize(email, 'string');
        }

        if (password !== undefined) {
            localVariableFormParameters['password'] = ObjectSerializer.serialize(
                password,
                'string'
            );
        }

        if (imageUpload !== undefined) {
            localVariableFormParameters['imageUpload'] = imageUpload;
        }
        localVariableUseFormData = true;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'PUT',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.bearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() =>
                this.authentications.bearerAuth.applyToRequest(localVariableRequestOptions)
            );
        }
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: User }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'User');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
    /**
     * Updates the email or password of the user identified by `{id}` in the path. Optional image can be uploaded.
     * @summary Edit user
     * @param id Resource identifier
     * @param email
     * @param password
     * @param imageUpload Optional user profile image
     */
    public async updateUserById(
        id: string,
        email?: string,
        password?: string,
        imageUpload?: RequestFile,
        options: { headers: { [name: string]: string } } = { headers: {} }
    ): Promise<{ response: http.IncomingMessage; body: User }> {
        const localVariablePath =
            this.basePath + '/users/{id}'.replace('{' + 'id' + '}', encodeURIComponent(String(id)));
        const localVariableQueryParameters: any = {};
        const localVariableHeaderParameters: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        localVariableHeaderParameters.Accept = produces.includes('application/json')
            ? 'application/json'
            : produces.join(',');
        const localVariableFormParameters: any = {};

        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error(
                'Required parameter id was null or undefined when calling updateUserById.'
            );
        }

        (<any>Object).assign(localVariableHeaderParameters, options.headers);

        let localVariableUseFormData = false;

        if (email !== undefined) {
            localVariableFormParameters['email'] = ObjectSerializer.serialize(email, 'string');
        }

        if (password !== undefined) {
            localVariableFormParameters['password'] = ObjectSerializer.serialize(
                password,
                'string'
            );
        }

        if (imageUpload !== undefined) {
            localVariableFormParameters['imageUpload'] = imageUpload;
        }
        localVariableUseFormData = true;

        const localVariableRequestOptions: localVarRequest.Options = {
            method: 'PUT',
            qs: localVariableQueryParameters,
            headers: localVariableHeaderParameters,
            uri: localVariablePath,
            useQuerystring: this._useQuerystring,
            json: true
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.bearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() =>
                this.authentications.bearerAuth.applyToRequest(localVariableRequestOptions)
            );
        }
        authenticationPromise = authenticationPromise.then(() =>
            this.authentications.default.applyToRequest(localVariableRequestOptions)
        );

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() =>
                interceptor(localVariableRequestOptions)
            );
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVariableFormParameters).length > 0) {
                if (localVariableUseFormData) {
                    (<any>localVariableRequestOptions).formData = localVariableFormParameters;
                } else {
                    localVariableRequestOptions.form = localVariableFormParameters;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: User }>(
                (resolve, reject) => {
                    localVarRequest(localVariableRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        } else {
                            if (
                                response.statusCode &&
                                response.statusCode >= 200 &&
                                response.statusCode <= 299
                            ) {
                                body = ObjectSerializer.deserialize(body, 'User');
                                resolve({ response: response, body: body });
                            } else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                }
            );
        });
    }
}
