import type { Request, Response } from 'express';
import { z } from 'zod';
import {
    SearchOrdersBody,
    searchOrdersBodyPageDefault,
    searchOrdersBodyPageSizeDefault,
    searchOrdersBodyPageSizeMax
} from '@api/schemas.zod';
import { orderService } from '@services/orders';
import { rejectResponse, successResponse } from '@utils/response';
import { extractId, mergeBodyQuery } from '@utils/helpers-request';
import type { SearchOrdersRequest } from '@types';
import { userScope } from '@utils/helpers-scopes';
import type { CastError } from 'mongoose';
import { emitAnalyticsEvent, AnalyticsEvent, buildAnalyticsBase } from '@utils/analytics';

/**
 * Query parameters generated by the search form (they are the same as SearchOrdersRequest keys)
 */
export type IGetOrdersQuery = Partial<Record<keyof SearchOrdersRequest, string>>;

/**
 * Built on the orval-generated SearchOrdersBody (kept in sync with
 * openapi.yaml); page/pageSize are coerced from strings since GET requests
 * carry them as query-string text, not JSON numbers.
 */
const searchOrdersQuerySchema = SearchOrdersBody.extend({
    page: z.preprocess(
        (value) =>
            value === '' || value === null || value === undefined
                ? searchOrdersBodyPageDefault
                : value,
        z.coerce.number().min(1)
    ),
    pageSize: z.preprocess(
        (value) =>
            value === '' || value === null || value === undefined
                ? searchOrdersBodyPageSizeDefault
                : value,
        z.coerce.number().min(1).max(searchOrdersBodyPageSizeMax)
    )
});

/**
 * GET /orders
 * List/search orders via query parameters or request body.
 * Non-admin users are automatically scoped to their own orders; the userId filter is ignored for non-admin callers.
 */
export const getOrders = (
    request: Request<{ id?: string }, unknown, SearchOrdersRequest, IGetOrdersQuery>,
    response: Response
) => {
    const isAdmin = Boolean(request.authContext?.admin);
    const merged = mergeBodyQuery(
        request.body as Record<string, unknown> | undefined,
        request.query as Record<string, string> | undefined
    );
    const id = extractId(request.params.id, merged.id as string | undefined);
    /* Non-admin callers cannot filter by arbitrary userId; userScope enforces their own. */
    const userId = isAdmin ? (merged.userId as string | undefined) : undefined;

    const parseResult = searchOrdersQuerySchema.safeParse({ ...merged, id, userId });
    if (!parseResult.success)
        return rejectResponse(
            response,
            422,
            'getOrders - invalid data',
            parseResult.error.issues.map(({ message }) => message)
        );

    return orderService
        .search(parseResult.data, userScope(request))
        .then((result) => {
            emitAnalyticsEvent({
                ...buildAnalyticsBase(request),
                event: AnalyticsEvent.ORDERS_VIEWED
            });
            successResponse(response, result);
        })
        .catch((error: CastError) => {
            rejectResponse(response, 500, 'getOrders', [error.message]);
        });
};
