import type { Request, Response } from 'express';
import { orderService } from '@services/orders';
import { rejectResponse, successResponse } from '@utils/response';
import { extractId, extractRequestPagination } from '@utils/helpers-request';
import type { SearchOrdersRequest } from '@types';
import { userScope } from '@utils/helpers-scopes';
import type { CastError } from 'mongoose';
import { emitAnalyticsEvent, AnalyticsEvent, buildAnalyticsBase } from '@utils/analytics';

/**
 * Query parameters generated by the search form (they are the same as SearchOrdersRequest keys)
 */
export type IGetOrdersQuery = Partial<Record<keyof SearchOrdersRequest, string>>;

/**
 * GET /orders
 * List/search orders via query parameters or request body.
 * Non-admin users are automatically scoped to their own orders; the userId filter is ignored for non-admin callers.
 */
export const getOrders = (
    request: Request<{ id?: string }, unknown, SearchOrdersRequest, IGetOrdersQuery>,
    response: Response
) => {
    const { page, pageSize } = extractRequestPagination(request);
    const isAdmin = Boolean(request.authContext?.admin);

    return orderService
        .search(
            {
                id: extractId(request.params.id, request.body?.id, request.query.id),
                page,
                pageSize,
                /* Non-admin callers cannot filter by arbitrary userId; userScope enforces their own. */
                userId: isAdmin ? (request.body?.userId ?? request.query.userId) : undefined,
                productId: request.body?.productId ?? request.query.productId,
                email: request.body?.email ?? request.query.email
            },
            userScope(request)
        )
        .then((result) => {
            emitAnalyticsEvent({
                ...buildAnalyticsBase(request),
                event: AnalyticsEvent.ORDERS_VIEWED
            });
            successResponse(response, result);
        })
        .catch((error: CastError) => {
            rejectResponse(response, 500, 'getOrders', [error.message]);
        });
};
