import type { Request, Response, NextFunction } from 'express';
import type { CastError } from 'mongoose';
import { databaseErrorConverter } from '@utils/helpers-errors';
import type { SearchOrdersRequest } from '@types';
import OrderService from '@services/orders';

/**
 * Query parameters generated by the search form (they are the same as SearchOrdersRequest keys)
 */
export type IGetAllOrdersQuery = Partial<Record<keyof SearchOrdersRequest, string>>;

/**
 * Get ALL orders info
 * Only of current user if NOT admin
 *
 * @param request
 * @param response
 * @param next
 */
export const pageAllOrders = async (
    // Page can be param or query
    request: Request<{ page?: string }, unknown, SearchOrdersRequest, IGetAllOrdersQuery>,
    response: Response,
    next: NextFunction
) => {
    const page = request.body.page ?? request.query.page ?? '1';
    const pageSize =
        request.body.pageSize ??
        request.query.pageSize ??
        process.env.NODE_SETTINGS_PAGINATION_PAGE_SIZE ??
        '10';

    return OrderService.search(
        {
            id: request.body.id ?? request.query.id,
            page: page ? Number(page) : undefined,
            pageSize: pageSize ? Number(pageSize) : undefined,
            userId: request.body.userId ?? request.query.userId,
            productId: request.body.productId ?? request.query.productId,
            email: request.body.email ?? request.query.email
        },
        // Only admin can see non-active and (soft) deleted products
        request.session.user?.admin ? {} : { userId: request.session.user?._id }
    )
        .then(({ items, meta }) =>
            response.render('orders/list', {
                pageMetaTitle: 'All Orders',
                pageMetaLinks: ['/css/order-list.css'],
                orderList: items,
                itemsTotal: meta.totalItems,
                pageCurrent: meta.page,
                pageTotal: meta.totalPages,
                search: request.query
            })
        )
        .catch((error: Error | CastError) => next(databaseErrorConverter(error)));
};
