/**
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract. Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AdminMetricsSummaryAuth } from './adminMetricsSummaryAuth';
import { AdminMetricsSummaryBusiness } from './adminMetricsSummaryBusiness';
import { AdminMetricsSummaryDatabase } from './adminMetricsSummaryDatabase';
import { AdminMetricsSummaryHttp } from './adminMetricsSummaryHttp';
import { AdminMetricsSummaryProcess } from './adminMetricsSummaryProcess';

export class AdminMetricsSummary {
    'http': AdminMetricsSummaryHttp;
    'auth': AdminMetricsSummaryAuth;
    'business': AdminMetricsSummaryBusiness;
    'database': AdminMetricsSummaryDatabase;
    'process': AdminMetricsSummaryProcess;
    'timestamp': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "http",
            "baseName": "http",
            "type": "AdminMetricsSummaryHttp"
        },
        {
            "name": "auth",
            "baseName": "auth",
            "type": "AdminMetricsSummaryAuth"
        },
        {
            "name": "business",
            "baseName": "business",
            "type": "AdminMetricsSummaryBusiness"
        },
        {
            "name": "database",
            "baseName": "database",
            "type": "AdminMetricsSummaryDatabase"
        },
        {
            "name": "process",
            "baseName": "process",
            "type": "AdminMetricsSummaryProcess"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return AdminMetricsSummary.attributeTypeMap;
    }
}

