/**
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract. Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AdminHealthDatabase {
    'status': AdminHealthDatabase.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "AdminHealthDatabase.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return AdminHealthDatabase.attributeTypeMap;
    }
}

export namespace AdminHealthDatabase {
    export enum StatusEnum {
        Connected = <any> 'connected',
        Connecting = <any> 'connecting',
        Disconnected = <any> 'disconnected'
    }
}
