/**
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract. Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AdminHealthIntegrations {
    'loki'?: boolean;
    'posthog'?: boolean;
    'otelEnabled'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "loki",
            "baseName": "loki",
            "type": "boolean"
        },
        {
            "name": "posthog",
            "baseName": "posthog",
            "type": "boolean"
        },
        {
            "name": "otelEnabled",
            "baseName": "otelEnabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return AdminHealthIntegrations.attributeTypeMap;
    }
}

