/**
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract. Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AuditEventItem {
    'actorUserId': string;
    'actorRole': AuditEventItem.ActorRoleEnum;
    /**
    * Dot-notation action name (e.g. auth.login.succeeded)
    */
    'action': string;
    'outcome': AuditEventItem.OutcomeEnum;
    'ip'?: string;
    'userAgent'?: string;
    'requestId'?: string;
    'traceId'?: string;
    'targetType'?: string;
    'targetId'?: string;
    'metadata'?: { [key: string]: any; };
    'timestamp': Date;
    'level': AuditEventItem.LevelEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actorUserId",
            "baseName": "actor_user_id",
            "type": "string"
        },
        {
            "name": "actorRole",
            "baseName": "actor_role",
            "type": "AuditEventItem.ActorRoleEnum"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "string"
        },
        {
            "name": "outcome",
            "baseName": "outcome",
            "type": "AuditEventItem.OutcomeEnum"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "userAgent",
            "baseName": "user_agent",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        },
        {
            "name": "traceId",
            "baseName": "trace_id",
            "type": "string"
        },
        {
            "name": "targetType",
            "baseName": "target_type",
            "type": "string"
        },
        {
            "name": "targetId",
            "baseName": "target_id",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "AuditEventItem.LevelEnum"
        }    ];

    static getAttributeTypeMap() {
        return AuditEventItem.attributeTypeMap;
    }
}

export namespace AuditEventItem {
    export enum ActorRoleEnum {
        Admin = <any> 'admin',
        User = <any> 'user',
        Anonymous = <any> 'anonymous'
    }
    export enum OutcomeEnum {
        Success = <any> 'success',
        Failure = <any> 'failure'
    }
    export enum LevelEnum {
        Info = <any> 'info',
        Warn = <any> 'warn'
    }
}
