/**
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract. Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CartItem } from './cartItem';

/**
 * Create a new order.
 */
export class CreateOrderRequest {
    /**
     * Resource identifier
     */
    'userId': string;
    'email': string;
    'items': Array<CartItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'userId',
            baseName: 'userId',
            type: 'string'
        },
        {
            name: 'email',
            baseName: 'email',
            type: 'string'
        },
        {
            name: 'items',
            baseName: 'items',
            type: 'Array<CartItem>'
        }
    ];

    static getAttributeTypeMap() {
        return CreateOrderRequest.attributeTypeMap;
    }
}
