/**
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract. Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrderItem } from './orderItem';

export class UpdateOrderRequest {
    /**
    * Resource identifier
    */
    'id': string;
    /**
    * Updated order status
    */
    'status'?: UpdateOrderRequest.StatusEnum;
    /**
    * Resource identifier
    */
    'userId'?: string;
    'email'?: string;
    'items'?: Array<OrderItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UpdateOrderRequest.StatusEnum"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<OrderItem>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateOrderRequest.attributeTypeMap;
    }
}

export namespace UpdateOrderRequest {
    export enum StatusEnum {
        Pending = <any> 'pending',
        Paid = <any> 'paid',
        Processing = <any> 'processing',
        Shipped = <any> 'shipped',
        Delivered = <any> 'delivered',
        Cancelled = <any> 'cancelled'
    }
}
