/**
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract. Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CartItem } from './cartItem';

export class UpdateOrderByIdRequest {
    /**
     * Updated order status
     */
    'status'?: UpdateOrderByIdRequest.StatusEnum;
    /**
     * Resource identifier
     */
    'userId'?: string;
    'email'?: string;
    'items'?: Array<CartItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'status',
            baseName: 'status',
            type: 'UpdateOrderByIdRequest.StatusEnum'
        },
        {
            name: 'userId',
            baseName: 'userId',
            type: 'string'
        },
        {
            name: 'email',
            baseName: 'email',
            type: 'string'
        },
        {
            name: 'items',
            baseName: 'items',
            type: 'Array<CartItem>'
        }
    ];

    static getAttributeTypeMap() {
        return UpdateOrderByIdRequest.attributeTypeMap;
    }
}

export namespace UpdateOrderByIdRequest {
    export enum StatusEnum {
        Pending = <any>'pending',
        Paid = <any>'paid',
        Processing = <any>'processing',
        Shipped = <any>'shipped',
        Delivered = <any>'delivered',
        Cancelled = <any>'cancelled'
    }
}
