/**
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract. Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorDetail } from './errorDetail';
import { ValidationErrorResponseAllOfErrors } from './validationErrorResponseAllOfErrors';

export class ValidationErrorResponse {
    'success': boolean;
    'error': ErrorDetail;
    /**
     * Correlation ID for support/debugging
     */
    'traceId'?: string;
    'errors': Array<ValidationErrorResponseAllOfErrors>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'success',
            baseName: 'success',
            type: 'boolean'
        },
        {
            name: 'error',
            baseName: 'error',
            type: 'ErrorDetail'
        },
        {
            name: 'traceId',
            baseName: 'traceId',
            type: 'string'
        },
        {
            name: 'errors',
            baseName: 'errors',
            type: 'Array<ValidationErrorResponseAllOfErrors>'
        }
    ];

    static getAttributeTypeMap() {
        return ValidationErrorResponse.attributeTypeMap;
    }
}
