  - info:
      name: Inventory
      type: folder
      seq: 13
    request:
      auth: inherit
    items:
      - info:
          name: List stock movements
          type: http
          seq: 1
          tags:
            - Inventory
        http:
          method: GET
          url: "{{baseUrl}}/inventory/movements"
          auth:
            type: bearer
            token: "{{token}}"
        settings:
          encodeUrl: true
          timeout: 0
          followRedirects: true
          maxRedirects: 5
        examples:
          - name: 200 Response
            description: The latest movements
            request:
              url: "{{baseUrl}}/inventory/movements"
              method: GET
            response:
              status: 200
              statusText: OK
              headers:
                - name: Content-Type
                  value: application/json
              body:
                type: json
                data: |-
                  {
                    "success": true,
                    "status": 200,
                    "message": "The latest movements",
                    "data": {
                      "items": [
                        {
                          "id": "65dc8a99604c307b702b5ccc",
                          "productId": "65dc8a99604c307b702b5ccc",
                          "delta": 1,
                          "reason": "order",
                          "reference": "string",
                          "createdAt": "2026-01-01T00:00:00.000Z",
                          "updatedAt": "2026-01-01T00:00:00.000Z"
                        }
                      ]
                    }
                  }
          - name: 401 Response
            description: Unauthorized
            request:
              url: "{{baseUrl}}/inventory/movements"
              method: GET
            response:
              status: 401
              statusText: Unauthorized
              headers:
                - name: Content-Type
                  value: application/json
              body:
                type: json
                data: |-
                  {
                    "success": false,
                    "status": 401,
                    "message": "Unauthorized",
                    "errors": [
                      {
                        "code": "VALIDATION_ERROR",
                        "message": "Field \"email\" is required",
                        "details": "string"
                      }
                    ]
                  }
          - name: 403 Response
            description: Forbidden
            request:
              url: "{{baseUrl}}/inventory/movements"
              method: GET
            response:
              status: 403
              statusText: Forbidden
              headers:
                - name: Content-Type
                  value: application/json
              body:
                type: json
                data: |-
                  {
                    "success": false,
                    "status": 403,
                    "message": "Forbidden",
                    "errors": [
                      {
                        "code": "VALIDATION_ERROR",
                        "message": "Field \"email\" is required",
                        "details": "string"
                      }
                    ]
                  }
          - name: 422 Response
            description: Validation failed
            request:
              url: "{{baseUrl}}/inventory/movements"
              method: GET
            response:
              status: 422
              statusText: Unprocessable Entity
              headers:
                - name: Content-Type
                  value: application/json
              body:
                type: json
                data: |-
                  {
                    "success": false,
                    "status": 422,
                    "message": "Validation failed",
                    "errors": [
                      {
                        "code": "VALIDATION_ERROR",
                        "message": "Field \"email\" is required",
                        "details": "string"
                      }
                    ]
                  }
          - name: 500 Response
            description: Internal server error
            request:
              url: "{{baseUrl}}/inventory/movements"
              method: GET
            response:
              status: 500
              statusText: Internal Server Error
              headers:
                - name: Content-Type
                  value: application/json
              body:
                type: json
                data: |-
                  {
                    "success": false,
                    "status": 500,
                    "message": "Internal server error",
                    "errors": [
                      {
                        "code": "VALIDATION_ERROR",
                        "message": "Field \"email\" is required",
                        "details": "string"
                      }
                    ]
                  }
      - info:
          name: Restock a product
          type: http
          seq: 2
          tags:
            - Inventory
        http:
          method: POST
          url: "{{baseUrl}}/inventory/restock"
          body:
            type: json
            data: |-
              {
                "productId": "65dc8a99604c307b702b5ccc",
                "quantity": 2
              }
          auth:
            type: bearer
            token: "{{token}}"
        settings:
          encodeUrl: true
          timeout: 0
          followRedirects: true
          maxRedirects: 5
        examples:
          - name: 200 Response
            description: The shelf after the delivery
            request:
              url: "{{baseUrl}}/inventory/restock"
              method: POST
              body:
                type: json
                data: |-
                  {
                    "productId": "65dc8a99604c307b702b5ccc",
                    "quantity": 2
                  }
            response:
              status: 200
              statusText: OK
              headers:
                - name: Content-Type
                  value: application/json
              body:
                type: json
                data: |-
                  {
                    "success": true,
                    "status": 200,
                    "message": "The shelf after the delivery",
                    "data": {
                      "productId": "65dc8a99604c307b702b5ccc",
                      "stock": 0
                    }
                  }
          - name: 401 Response
            description: Unauthorized
            request:
              url: "{{baseUrl}}/inventory/restock"
              method: POST
              body:
                type: json
                data: |-
                  {
                    "productId": "65dc8a99604c307b702b5ccc",
                    "quantity": 2
                  }
            response:
              status: 401
              statusText: Unauthorized
              headers:
                - name: Content-Type
                  value: application/json
              body:
                type: json
                data: |-
                  {
                    "success": false,
                    "status": 401,
                    "message": "Unauthorized",
                    "errors": [
                      {
                        "code": "VALIDATION_ERROR",
                        "message": "Field \"email\" is required",
                        "details": "string"
                      }
                    ]
                  }
          - name: 403 Response
            description: Forbidden
            request:
              url: "{{baseUrl}}/inventory/restock"
              method: POST
              body:
                type: json
                data: |-
                  {
                    "productId": "65dc8a99604c307b702b5ccc",
                    "quantity": 2
                  }
            response:
              status: 403
              statusText: Forbidden
              headers:
                - name: Content-Type
                  value: application/json
              body:
                type: json
                data: |-
                  {
                    "success": false,
                    "status": 403,
                    "message": "Forbidden",
                    "errors": [
                      {
                        "code": "VALIDATION_ERROR",
                        "message": "Field \"email\" is required",
                        "details": "string"
                      }
                    ]
                  }
          - name: 404 Response
            description: Resource not found
            request:
              url: "{{baseUrl}}/inventory/restock"
              method: POST
              body:
                type: json
                data: |-
                  {
                    "productId": "65dc8a99604c307b702b5ccc",
                    "quantity": 2
                  }
            response:
              status: 404
              statusText: Not Found
              headers:
                - name: Content-Type
                  value: application/json
              body:
                type: json
                data: |-
                  {
                    "success": false,
                    "status": 404,
                    "message": "Resource not found",
                    "errors": [
                      {
                        "code": "VALIDATION_ERROR",
                        "message": "Field \"email\" is required",
                        "details": "string"
                      }
                    ]
                  }
          - name: 422 Response
            description: Validation failed
            request:
              url: "{{baseUrl}}/inventory/restock"
              method: POST
              body:
                type: json
                data: |-
                  {
                    "productId": "65dc8a99604c307b702b5ccc",
                    "quantity": 2
                  }
            response:
              status: 422
              statusText: Unprocessable Entity
              headers:
                - name: Content-Type
                  value: application/json
              body:
                type: json
                data: |-
                  {
                    "success": false,
                    "status": 422,
                    "message": "Validation failed",
                    "errors": [
                      {
                        "code": "VALIDATION_ERROR",
                        "message": "Field \"email\" is required",
                        "details": "string"
                      }
                    ]
                  }
          - name: 500 Response
            description: Internal server error
            request:
              url: "{{baseUrl}}/inventory/restock"
              method: POST
              body:
                type: json
                data: |-
                  {
                    "productId": "65dc8a99604c307b702b5ccc",
                    "quantity": 2
                  }
            response:
              status: 500
              statusText: Internal Server Error
              headers:
                - name: Content-Type
                  value: application/json
              body:
                type: json
                data: |-
                  {
                    "success": false,
                    "status": 500,
                    "message": "Internal server error",
                    "errors": [
                      {
                        "code": "VALIDATION_ERROR",
                        "message": "Field \"email\" is required",
                        "details": "string"
                      }
                    ]
                  }
