import type { Request, Response } from 'express';
import type { ParamsDictionary } from 'express-serve-static-core';
import { SearchOrdersBody } from '@api/schemas.zod';
import { orderService } from '../service';
import { successResponse } from '@infrastructure/http/response';
import { readInput } from '@infrastructure/http/request';
import { pageSchema, pageSizeSchema } from '@infrastructure/http/schemas';
import type { SearchOrdersRequest } from '@types';
import { emitAnalyticsEvent, buildAnalyticsBase } from '@infrastructure/observability/analytics';
import { ordersAnalyticsEvents } from '../analytics';
import { catchAs, parseBody } from '@infrastructure/http/controller';

/**
 * Query parameters generated by the search form (they are the same as SearchOrdersRequest keys)
 */
export type GetOrdersQuery = Partial<Record<keyof SearchOrdersRequest, string>>;

/**
 * Built on the orval-generated SearchOrdersBody (kept in sync with
 * openapi.yaml); page/pageSize are coerced from strings since GET requests
 * carry them as query-string text, not JSON numbers.
 *
 * `page`/`pageSize` come from `@infrastructure/http/schemas` so all four search endpoints agree on what a
 * legal one is; absent stays absent, because `normalizePagination` owns the defaults.
 */
const searchOrdersQuerySchema = SearchOrdersBody.extend({
    page: pageSchema,
    pageSize: pageSizeSchema
});

/**
 * Query parameters that change this endpoint's answer, and therefore its cache key.
 *
 * Derived from the schema rather than hand-listed, because the two must not drift: a parameter
 * the controller reads but the key omits would let two different requests share one cached
 * response. Anything outside this list is stripped by the validator and changes nothing.
 */
export const searchOrdersKeyParameters = Object.keys(searchOrdersQuerySchema.shape);

/**
 * GET /orders
 * List/search orders via query parameters or request body.
 * Non-admin users are automatically scoped to their own orders; the userId filter is ignored for non-admin callers.
 */
export const getOrders = (
    request: Request<ParamsDictionary, unknown, SearchOrdersRequest, GetOrdersQuery>,
    response: Response
) => {
    const isAdmin = Boolean(request.authContext?.admin);
    // One declaration instead of a per-field assembly — see docs/theory/request-input.md.
    const input = readInput(request, { surface: 'search', ids: ['id'] });

    const parsed = parseBody(
        searchOrdersQuerySchema,
        {
            ...input,
            /* Non-admin callers cannot filter by arbitrary userId; orderService.callerScope enforces their own. */
            userId: isAdmin ? (input.userId as string | undefined) : undefined
        },
        response
    );
    if (!parsed) return;

    return orderService
        .search(parsed, orderService.callerScope(request.authContext))
        .then((result) => {
            emitAnalyticsEvent({
                ...buildAnalyticsBase(request),
                event: ordersAnalyticsEvents.ORDERS_VIEWED
            });
            successResponse(response, result);
        })
        .catch(catchAs(response, 'getOrders'));
};
