#!/usr/bin/env tsx
/*
 * Generates src/types/asyncapi.ts from asyncapi.yaml using @asyncapi/modelina.
 *
 * Modelina handles schema-to-TypeScript conversion for all named component
 * schemas. Channel name constants and application-level union types are
 * appended as custom code since modelina does not produce those.
 *
 * Usage: npm run gen:asyncapi-types
 */
import { TypeScriptGenerator, typeScriptDefaultModelNameConstraints } from '@asyncapi/modelina';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const INPUT = resolve(ROOT, 'asyncapi.yaml');
const OUTPUT = resolve(ROOT, 'src/types/asyncapi.ts');

/* Named (non-anonymous) models get an I prefix, anonymous helpers keep their name. */
const modelNameConstraints = typeScriptDefaultModelNameConstraints({
    NAMING_FORMATTER: (value: string) => {
        if (value.toLowerCase().startsWith('anonymous')) return value;
        const pascal = value.charAt(0).toUpperCase() + value.slice(1);
        return `I${pascal}`;
    }
});

const generator = new TypeScriptGenerator({
    modelType: 'interface',
    enumType: 'union',
    rawPropertyNames: true,
    constraints: { modelName: modelNameConstraints }
});

/* Read spec once — modelina consumes it as a string; yaml for channel parsing. */
const specText = readFileSync(INPUT, 'utf8');

interface AsyncApiDoc {
    channels: Record<string, unknown>;
}

const { channels } = yaml.load(specText) as AsyncApiDoc;
const channelKeys = Object.keys(channels ?? {});

const chatChannels = channelKeys.filter((k) => k.startsWith('realtime.chat.'));
const observabilityChannels = channelKeys.filter((k) => k.startsWith('observability.'));
const ecommerceChannels = channelKeys.filter((k) => k.startsWith('ecommerce.'));
const workerChannels = channelKeys.filter((k) => k.startsWith('worker.'));
const cacheChannels = channelKeys.filter((k) => k.startsWith('cache.'));

/* 'realtime.chat.event.user.joined' → 'EVENT_USER_JOINED' */
const toConstKey = (channelName: string, prefix: string): string =>
    channelName.replace(prefix, '').replace(/[._]/g, '_').replace(/^_/, '').toUpperCase();

const renderConstGroup = (
    exportName: string,
    chList: string[],
    prefix: string,
    description: string
): string => {
    const entries = chList.map((ch) => `    ${toConstKey(ch, prefix)}: '${ch}',`).join('\n');
    return `/* ${description} */\nexport const ${exportName} = {\n${entries}\n} as const;\n`;
};

generator.generate(specText).then((models) => {
    const header = [
        '/* eslint-disable @typescript-eslint/naming-convention */',
        '// GENERATED — do not edit manually.',
        '// Source: asyncapi.yaml  |  Regenerate: npm run gen:asyncapi-types',
        ''
    ];

    const channelSection = [
        '// Channel name constants (canonical identifiers from asyncapi.yaml)',
        '',
        renderConstGroup(
            'CHAT_CHANNELS',
            chatChannels,
            'realtime.chat.',
            'WebSocket chat channel names'
        ),
        renderConstGroup(
            'OBSERVABILITY_CHANNELS',
            observabilityChannels,
            'observability.',
            'SSE observability channel names'
        ),
        renderConstGroup(
            'ECOMMERCE_CHANNELS',
            ecommerceChannels,
            'ecommerce.',
            'Ecommerce domain event channel names'
        ),
        renderConstGroup(
            'WORKER_CHANNELS',
            workerChannels,
            'worker.',
            'RabbitMQ worker queue channel names'
        ),
        renderConstGroup(
            'CACHE_CHANNELS',
            cacheChannels,
            'cache.',
            'Redis pub/sub cache channel names'
        ),
        '/* Union of all SSE observability channel names */',
        'export type TObservabilityChannel =',
        '    (typeof OBSERVABILITY_CHANNELS)[keyof typeof OBSERVABILITY_CHANNELS];',
        '',
        '/* Union of all ecommerce channel names */',
        'export type TEcommerceChannel =',
        '    (typeof ECOMMERCE_CHANNELS)[keyof typeof ECOMMERCE_CHANNELS];',
        '',
        '/* Union of all worker queue channel names */',
        'export type TWorkerChannel = (typeof WORKER_CHANNELS)[keyof typeof WORKER_CHANNELS];',
        '',
        '/* Union of all cache pub/sub channel names */',
        'export type TCacheChannel = (typeof CACHE_CHANNELS)[keyof typeof CACHE_CHANNELS];',
        ''
    ];

    /* Modelina-generated models: named interfaces + anonymous helpers. */
    const modelSection = [
        '// TypeScript models generated by @asyncapi/modelina from asyncapi.yaml',
        '',
        ...models.map((m) => `export ${m.result.replace(/Map<string, any>/g, 'Record<string, unknown>')}`),
        ''
    ];

    const appTypes = [
        '// Application-level union types',
        '',
        '/* Default chat room — mirrors the enum constraint in asyncapi.yaml */',
        "export const DEFAULT_CHAT_ROOM = 'general' as const;",
        'export type TChatRoom = typeof DEFAULT_CHAT_ROOM;',
        '',
        '/* All event types a chat client can send to the server */',
        'export type TChatClientEvent = IChatJoinCommand | IChatMessageSendCommand;',
        '',
        '/* All event types the server can push to a chat client */',
        'export type TChatServerEvent =',
        '    | IChatSystemPayload',
        '    | IChatMessagePayload',
        '    | IChatPresencePayload',
        '    | IChatJoinedEvent',
        '    | IChatErrorEvent;',
        ''
    ];

    const output = [...header, ...channelSection, ...modelSection, ...appTypes].join('\n');
    writeFileSync(OUTPUT, output, 'utf8');
    console.log(`✓ Generated ${OUTPUT}`);
});
