/**
 * Node Demo API
 * Stable, codegen-oriented OpenAPI contract. Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorDetail } from './errorDetail';
import { FieldError } from './fieldError';

export class ValidationErrorResponse {
    'error': ErrorDetail;
    /**
    * Correlation ID for support/debugging
    */
    'traceId'?: string;
    'errors': Array<FieldError>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "ErrorDetail"
        },
        {
            "name": "traceId",
            "baseName": "traceId",
            "type": "string"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<FieldError>"
        }    ];

    static getAttributeTypeMap() {
        return ValidationErrorResponse.attributeTypeMap;
    }
}

