/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import type { AuditEventItemActorRole } from './auditEventItemActorRole';
import type { AuditEventItemLevel } from './auditEventItemLevel';
import type { AuditEventItemMetadata } from './auditEventItemMetadata';
import type { AuditEventItemOutcome } from './auditEventItemOutcome';

export interface AuditEventItem {
  actor_user_id: string;
  actor_role: AuditEventItemActorRole;
  /** Dot-notation action name (e.g. auth.login.succeeded) */
  action: string;
  outcome: AuditEventItemOutcome;
  ip?: string;
  user_agent?: string;
  request_id?: string;
  trace_id?: string;
  target_type?: string;
  target_id?: string;
  metadata?: AuditEventItemMetadata;
  timestamp: string;
  level: AuditEventItemLevel;
}
