/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */

export type AuditEventItemActorRole = typeof AuditEventItemActorRole[keyof typeof AuditEventItemActorRole];


export const AuditEventItemActorRole = {
  admin: 'admin',
  user: 'user',
  anonymous: 'anonymous',
} as const;
