/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * Language: every endpoint honours `Accept-Language` (q-weights and region tags
 * included). It selects the language of user-facing copy only — `errors[].message` and a
 * success envelope's `message` — never the response shape, the status code, or a
 * machine-readable field such as `errors[].code`. An unsupported language falls back
 * instead of erroring; `Content-Language` states what was used and `Vary:
 * Accept-Language` is always set. `GET /locales` lists what a deployment supports.
 *
 * The header is intentionally not declared per operation: it applies to all of them and
 * clients set it once in an interceptor, so declaring it 33 times would only add a
 * redundant argument to every generated function. This paragraph is its contract.
 *
 * OpenAPI spec version: 2.0.0
 */
import type { AuditEventItemActorRole } from './auditEventItemActorRole';
import type { AuditEventItemLevel } from './auditEventItemLevel';
import type { AuditEventItemMetadata } from './auditEventItemMetadata';
import type { AuditEventItemOutcome } from './auditEventItemOutcome';

export interface AuditEventItem {
  actor_user_id: string;
  actor_role: AuditEventItemActorRole;
  /** Dot-notation action name (e.g. auth.login.succeeded) */
  action: string;
  outcome: AuditEventItemOutcome;
  ip?: string;
  user_agent?: string;
  request_id?: string;
  trace_id?: string;
  target_type?: string;
  target_id?: string;
  metadata?: AuditEventItemMetadata;
  timestamp: string;
  level: AuditEventItemLevel;
}
