/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */

export interface CartSummaryResponse {
  /**
     * Number of distinct cart lines/items
     * @minimum 0
     */
  itemsCount: number;
  /**
     * Sum of quantities across all items
     * @minimum 0
     */
  totalQuantity: number;
  /**
     * Sum of item prices * quantity (before tax/shipping/discounts)
     * @minimum 0
     */
  total: number;
  /** ISO-4217 currency code (e.g. USD) */
  currency?: string;
}
