/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import type { ErrorItem } from './errorItem';

export interface ErrorResponse {
  success: false;
  status: number;
  /** Human-readable summary for this failure */
  message: string;
  /**
     * Structured machine-friendly errors
     * @minItems 1
     */
  errors: ErrorItem[];
}
