/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import type { FeedbackRequestsResponse } from './feedbackRequestsResponse';

export interface FeedbackRequestsResponseEnvelope {
  success: true;
  status: number;
  message: string;
  data: FeedbackRequestsResponse;
}
