/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */

export type FeedbackRequestStatus = typeof FeedbackRequestStatus[keyof typeof FeedbackRequestStatus];


export const FeedbackRequestStatus = {
  new: 'new',
  in_progress: 'in_progress',
  resolved: 'resolved',
  spam: 'spam',
} as const;
