/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import type { HealthPingStatus } from './healthPingStatus';

export interface HealthPing {
  /** Liveness indicator. Always `ok` when the process is answering. */
  status: HealthPingStatus;
}
