/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * Language: every endpoint honours `Accept-Language` (q-weights and region tags
 * included). It selects the language of user-facing copy only — `errors[].message` and a
 * success envelope's `message` — never the response shape, the status code, or a
 * machine-readable field such as `errors[].code`. An unsupported language falls back
 * instead of erroring; `Content-Language` states what was used and `Vary:
 * Accept-Language` is always set. `GET /locales` lists what a deployment supports.
 *
 * The header is intentionally not declared per operation: it applies to all of them and
 * clients set it once in an interceptor, so declaring it 33 times would only add a
 * redundant argument to every generated function. This paragraph is its contract.
 *
 * OpenAPI spec version: 2.0.0
 */
import type { Id } from './id';
import type { Locale } from './locale';
import type { LocaleDirection } from './localeDirection';

/**
 * A language registered in the DYNAMIC tier. Its existence means entries can be translated into it and a client can download the result — never that the API can answer a request in it, which is decided by a deployed file and nothing else.
 */
export interface Language {
  id: Id;
  tag: Locale;
  /**
     * The ISO 639-1 code at the front of `tag` — the BCP 47 PRIMARY SUBTAG, with any region or script dropped. `pt-BR` and `pt-PT` are two languages here and both answer `pt`.
     * Derived from `tag` and never sent by a client: two fields that can disagree about the same fact are a bug waiting for the first person who edits one of them. Stored rather than computed on read because it is what groups the variants of a language, and a stored column can be queried and indexed while a split cannot.
     * @pattern ^[a-z]{2}$
     */
  baseLanguage: string;
  /** English name, for an admin list. */
  name: string;
  /** The language's own name, for a client's language picker. */
  nativeName: string;
  direction: LocaleDirection;
  active: boolean;
  /** @minimum 0 */
  revision: number;
  createdAt?: string;
  updatedAt?: string;
}
