/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * Language: every endpoint honours `Accept-Language` (q-weights and region tags
 * included). It selects the language of user-facing copy only — `errors[].message` and a
 * success envelope's `message` — never the response shape, the status code, or a
 * machine-readable field such as `errors[].code`. An unsupported language falls back
 * instead of erroring; `Content-Language` states what was used and `Vary:
 * Accept-Language` is always set. `GET /locales` lists what a deployment supports.
 *
 * The header is intentionally not declared per operation: it applies to all of them and
 * clients set it once in an interceptor, so declaring it 33 times would only add a
 * redundant argument to every generated function. This paragraph is its contract.
 *
 * OpenAPI spec version: 2.0.0
 */
import type { EntryScopeQueryParamParameter } from './entryScopeQueryParamParameter';
import type { LocaleScope } from './localeScope';
import type { Page } from './page';
import type { PageParamParameter } from './pageParamParameter';
import type { PageSize } from './pageSize';
import type { PageSizeParamParameter } from './pageSizeParamParameter';
import type { Text } from './text';
import type { TextParamParameter } from './textParamParameter';

export type ListLocaleEntriesParams = {
/**
 * 1-based page index
 * @minimum 1
 */
page?: PageParamParameter;
/**
 * Optional override; server may clamp to a max
 * @minimum 1
 * @maximum 100
 */
pageSize?: PageSizeParamParameter;
/**
 * Free-text search string
 * @minLength 1
 */
text?: TextParamParameter;
/**
 * Which of the two dictionaries something belongs to. `api` is the API's own — the
 * backend's words. `app` is the client's — the frontend's words. They are separate
 * keyspaces, authored by different people, and a key present in both means two
 * unrelated strings.
 *
 * On a LANGUAGE it reports capability, and the two are independent: `api` — the API
 * can answer requests in it, because a dictionary file is deployed; `app` — a client
 * dictionary is downloadable for it.
 *
 * On an ENTRY it says which dictionary that row OVERRIDES. `app` rows are what
 * `GET /locales/{locale}/messages` serves to a frontend; `api` rows are layered over
 * the API's own deployed files at resolution time.
 */
scope?: EntryScopeQueryParamParameter;
};
