/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import type { Email } from './email';
import type { Id } from './id';
import type { IdParamParameter } from './idParamParameter';
import type { Page } from './page';
import type { PageParamParameter } from './pageParamParameter';
import type { PageSize } from './pageSize';
import type { PageSizeParamParameter } from './pageSizeParamParameter';
import type { ProductIdParamParameter } from './productIdParamParameter';
import type { UserIdParamParameter } from './userIdParamParameter';

export type ListOrdersParams = {
/**
 * 1-based page index
 * @minimum 1
 */
page?: PageParamParameter;
/**
 * Optional override; server may clamp to a max
 * @minimum 1
 * @maximum 100
 */
pageSize?: PageSizeParamParameter;
/**
 * Resource identifier
 */
id?: IdParamParameter;
/**
 * Resource identifier
 */
userId?: UserIdParamParameter;
/**
 * Resource identifier
 */
productId?: ProductIdParamParameter;
email?: Email;
};
