/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import type { ObservabilityMetricsSummaryAuth } from './observabilityMetricsSummaryAuth';
import type { ObservabilityMetricsSummaryBusiness } from './observabilityMetricsSummaryBusiness';
import type { ObservabilityMetricsSummaryDatabase } from './observabilityMetricsSummaryDatabase';
import type { ObservabilityMetricsSummaryHttp } from './observabilityMetricsSummaryHttp';
import type { ObservabilityMetricsSummaryProcess } from './observabilityMetricsSummaryProcess';

export interface ObservabilityMetricsSummary {
  http: ObservabilityMetricsSummaryHttp;
  auth: ObservabilityMetricsSummaryAuth;
  business: ObservabilityMetricsSummaryBusiness;
  database: ObservabilityMetricsSummaryDatabase;
  process: ObservabilityMetricsSummaryProcess;
  timestamp: string;
}
