/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * Language: every endpoint honours `Accept-Language` (q-weights and region tags
 * included). It selects the language of user-facing copy only — `errors[].message` and a
 * success envelope's `message` — never the response shape, the status code, or a
 * machine-readable field such as `errors[].code`. An unsupported language falls back
 * instead of erroring; `Content-Language` states what was used and `Vary:
 * Accept-Language` is always set. `GET /locales` lists what a deployment supports.
 *
 * The header is intentionally not declared per operation: it applies to all of them and
 * clients set it once in an interceptor, so declaring it 33 times would only add a
 * redundant argument to every generated function. This paragraph is its contract.
 *
 * OpenAPI spec version: 2.0.0
 */

export interface ObservabilityLoadTestResult {
  /** Wall-clock time in ms spent on the synthetic CPU load */
  durationMs: number;
}
