/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * Language: every endpoint honours `Accept-Language` (q-weights and region tags
 * included). It selects the language of user-facing copy only — `errors[].message` and a
 * success envelope's `message` — never the response shape, the status code, or a
 * machine-readable field such as `errors[].code`. An unsupported language falls back
 * instead of erroring; `Content-Language` states what was used and `Vary:
 * Accept-Language` is always set. `GET /locales` lists what a deployment supports.
 *
 * The header is intentionally not declared per operation: it applies to all of them and
 * clients set it once in an interceptor, so declaring it 33 times would only add a
 * redundant argument to every generated function. This paragraph is its contract.
 *
 * OpenAPI spec version: 2.0.0
 */
import type { Id } from './id';
import type { PaymentStatus } from './paymentStatus';

export interface Payment {
  id: Id;
  orderId: Id;
  userId: Id;
  /**
     * The order's total as the intent froze it.
     * @minimum 0
     */
  amount: number;
  /** ISO-4217 currency code (e.g. EUR) */
  currency: string;
  /** The provider-facing lifecycle. `declined` is retryable — the confirm endpoint accepts the same payment again; `refunded` is terminal. */
  status: PaymentStatus;
  /** Which provider implementation handled it (`fake` in the demo). */
  provider: string;
  /** The only card digits a payment system may remember. */
  cardLast4?: string;
  createdAt?: string;
  updatedAt?: string;
}
