/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */

export interface RefreshTokenResponse {
  /** New access JWT */
  token: string;
  /** New refresh token if returned by backend */
  refreshToken?: string;
  /** New access token expiry in seconds */
  expiresIn?: number;
}
