/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import type { Email } from './email';
import type { Id } from './id';
import type { Page } from './page';
import type { PageSize } from './pageSize';
import type { Text } from './text';

export interface SearchUsersRequest {
  page?: Page;
  pageSize?: PageSize;
  text?: Text;
  id?: Id;
  email?: Email;
  username?: string;
  active?: boolean;
}
