/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */

export interface UpdateProductByIdRequest {
  title: string;
  description?: string;
  /** @minimum 0 */
  price: number;
  active?: boolean;
  imageUrl?: string;
  categories?: string[];
  tags?: string[];
}
