import type { Request, Response } from 'express';
import { userService } from '@services/users';
import { rejectResponse, successResponse } from '@utils/response';
import { extractId, extractPagination } from '@utils/helpers-request';
import type { SearchUsersRequest } from '@types';
import type { CastError } from 'mongoose';

/**
 * Query parameters generated by the search form
 */
export type IGetUsersQuery = Partial<Record<keyof SearchUsersRequest, string>>;

/**
 * GET /users
 * List/search users via query parameters (admin only).
 */
export const getUsers = (
    request: Request<{ id?: string }, unknown, SearchUsersRequest, IGetUsersQuery>,
    response: Response
) => {
    const { page, pageSize } = extractPagination({
        page: request.body?.page ?? request.query.page,
        pageSize: request.body?.pageSize ?? request.query.pageSize
    });

    const activeRaw = request.body?.active ?? request.query.active;

    return userService
        .search({
            id: extractId(request.params.id, request.body?.id, request.query.id),
            text: request.body?.text ?? request.query.text,
            email: request.body?.email ?? request.query.email,
            username: request.body?.username ?? request.query.username,
            page,
            pageSize,
            active: activeRaw === undefined ? undefined : activeRaw === 'true'
        })
        .then((result) => {
            successResponse(response, result);
        })
        .catch((error: CastError) => {
            rejectResponse(response, 500, 'Unknown Error', [error.message]);
        });
};
