/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import type {
  AccountDeleteConfirmRequest,
  AuditLogsResponseEnvelope,
  AuthTokensEnvelope,
  CartResponseEnvelope,
  CartSummaryResponseEnvelope,
  CheckoutRequest,
  CheckoutResponseEnvelope,
  CreateFeedbackRequest,
  CreateOrderRequest,
  CreateProductRequest,
  CreateProductRequestMultipart,
  CreateUserRequest,
  CreateUserRequestMultipart,
  DeleteOrderRequest,
  DeleteProductByIdParams,
  DeleteProductRequest,
  DeleteUserByIdParams,
  DeleteUserRequest,
  FeedbackRequestEnvelope,
  FeedbackRequestsResponseEnvelope,
  ForbiddenResponse,
  GetObservabilityAuditLogsParams,
  InternalErrorResponse,
  ListOrdersParams,
  ListProductsParams,
  ListUsersParams,
  LoginRequest,
  MessageResponse,
  NotFoundResponse,
  ObservabilityHealthResponseEnvelope,
  ObservabilityMetricsSummaryResponseEnvelope,
  OrderEnvelope,
  OrdersResponseEnvelope,
  PasswordResetConfirmRequest,
  PasswordResetRequest,
  ProductEnvelope,
  ProductsResponseEnvelope,
  RefreshTokenEnvelope,
  RemoveCartItemRequest,
  SearchFeedbackRequestsRequest,
  SearchOrdersRequest,
  SearchProductsRequest,
  SearchUsersRequest,
  SignupRequest,
  SignupRequestMultipart,
  SuccessResponse,
  UnauthorizedResponse,
  UpdateCartItemByIdRequest,
  UpdateFeedbackRequestStatusRequest,
  UpdateOrderByIdRequest,
  UpdateOrderRequest,
  UpdateProductByIdRequest,
  UpdateProductByIdRequestMultipart,
  UpdateProductRequest,
  UpdateProductRequestMultipart,
  UpdateUserByIdRequest,
  UpdateUserByIdRequestMultipart,
  UpdateUserRequest,
  UpdateUserRequestMultipart,
  UpsertCartItemRequest,
  UserEnvelope,
  UsersResponseEnvelope,
  ValidationErrorResponse
} from './models';

export type getHealthResponse200 = {
  data: MessageResponse
  status: 200
}

export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {




  return `/`
}

/**
 * Public ping endpoint. Returns a simple liveness indicator confirming the API process is running.
 * @summary API health check
 */
export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {

  const res = await fetch(getGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getHealthResponse
}



export type getObservabilityEventsResponse200 = {
  data: string
  status: 200
}

export type getObservabilityEventsResponseSuccess = (getObservabilityEventsResponse200) & {
  headers: Headers;
};
;

export type getObservabilityEventsResponse = (getObservabilityEventsResponseSuccess)

export const getGetObservabilityEventsUrl = () => {




  return `/observability/events`
}

/**
 * Live Server-Sent Events stream for demo dashboards.
 * Sends `metrics.snapshot` on connect, followed by periodic `metrics.updated` and `heartbeat` events.
 * @summary Observability SSE stream
 */
export const getObservabilityEvents = async ( options?: RequestInit): Promise<getObservabilityEventsResponse> => {

  const res = await fetch(getGetObservabilityEventsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getObservabilityEventsResponse['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as getObservabilityEventsResponse
}



export type getObservabilityHealthResponse200 = {
  data: ObservabilityHealthResponseEnvelope
  status: 200
}

export type getObservabilityHealthResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getObservabilityHealthResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getObservabilityHealthResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getObservabilityHealthResponseSuccess = (getObservabilityHealthResponse200) & {
  headers: Headers;
};
export type getObservabilityHealthResponseError = (getObservabilityHealthResponse401 | getObservabilityHealthResponse403 | getObservabilityHealthResponse500) & {
  headers: Headers;
};

export type getObservabilityHealthResponse = (getObservabilityHealthResponseSuccess | getObservabilityHealthResponseError)

export const getGetObservabilityHealthUrl = () => {




  return `/observability/health`
}

/**
 * Full JSON health snapshot for dashboard use.
 * Includes uptime, database status, memory, integrations, and system info.
 * Requires admin role.
 * @summary Health snapshot
 */
export const getObservabilityHealth = async ( options?: RequestInit): Promise<getObservabilityHealthResponse> => {

  const res = await fetch(getGetObservabilityHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getObservabilityHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getObservabilityHealthResponse
}



export type getObservabilityMetricsResponse200 = {
  data: string
  status: 200
}

export type getObservabilityMetricsResponseSuccess = (getObservabilityMetricsResponse200) & {
  headers: Headers;
};
;

export type getObservabilityMetricsResponse = (getObservabilityMetricsResponseSuccess)

export const getGetObservabilityMetricsUrl = () => {




  return `/observability/metrics`
}

/**
 * Raw Prometheus text (exposition format 0.0.4).
 * Intended for Prometheus scraping, not for browser clients.
 * Use `GET /observability/metrics/overview` for a JSON summary suitable for dashboards.
 * @summary Prometheus metrics
 */
export const getObservabilityMetrics = async ( options?: RequestInit): Promise<getObservabilityMetricsResponse> => {

  const res = await fetch(getGetObservabilityMetricsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getObservabilityMetricsResponse['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as getObservabilityMetricsResponse
}



export type getObservabilityMetricsOverviewResponse200 = {
  data: ObservabilityMetricsSummaryResponseEnvelope
  status: 200
}

export type getObservabilityMetricsOverviewResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getObservabilityMetricsOverviewResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getObservabilityMetricsOverviewResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getObservabilityMetricsOverviewResponseSuccess = (getObservabilityMetricsOverviewResponse200) & {
  headers: Headers;
};
export type getObservabilityMetricsOverviewResponseError = (getObservabilityMetricsOverviewResponse401 | getObservabilityMetricsOverviewResponse403 | getObservabilityMetricsOverviewResponse500) & {
  headers: Headers;
};

export type getObservabilityMetricsOverviewResponse = (getObservabilityMetricsOverviewResponseSuccess | getObservabilityMetricsOverviewResponseError)

export const getGetObservabilityMetricsOverviewUrl = () => {




  return `/observability/metrics/overview`
}

/**
 * Key operational metrics derived from Prometheus counters/histograms,
 * returned as structured JSON for dashboard KPI cards and charts.
 * Requires admin role.
 * @summary Metrics overview (JSON)
 */
export const getObservabilityMetricsOverview = async ( options?: RequestInit): Promise<getObservabilityMetricsOverviewResponse> => {

  const res = await fetch(getGetObservabilityMetricsOverviewUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getObservabilityMetricsOverviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getObservabilityMetricsOverviewResponse
}



export type getObservabilityAuditLogsResponse200 = {
  data: AuditLogsResponseEnvelope
  status: 200
}

export type getObservabilityAuditLogsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getObservabilityAuditLogsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getObservabilityAuditLogsResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type getObservabilityAuditLogsResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getObservabilityAuditLogsResponseSuccess = (getObservabilityAuditLogsResponse200) & {
  headers: Headers;
};
export type getObservabilityAuditLogsResponseError = (getObservabilityAuditLogsResponse401 | getObservabilityAuditLogsResponse403 | getObservabilityAuditLogsResponse422 | getObservabilityAuditLogsResponse500) & {
  headers: Headers;
};

export type getObservabilityAuditLogsResponse = (getObservabilityAuditLogsResponseSuccess | getObservabilityAuditLogsResponseError)

export const getGetObservabilityAuditLogsUrl = (params?: GetObservabilityAuditLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/observability/audit?${stringifiedParams}` : `/observability/audit`
}

/**
 * Returns the most recent audit events from the in-memory ring buffer (up to 200).
 * Events include auth flows, admin CRUD actions, and security blocks.
 * Requires admin role.
 * @summary Recent audit events
 */
export const getObservabilityAuditLogs = async (params?: GetObservabilityAuditLogsParams, options?: RequestInit): Promise<getObservabilityAuditLogsResponse> => {

  const res = await fetch(getGetObservabilityAuditLogsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getObservabilityAuditLogsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getObservabilityAuditLogsResponse
}



export type getAccountResponse200 = {
  data: UserEnvelope
  status: 200
}

export type getAccountResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getAccountResponseSuccess = (getAccountResponse200) & {
  headers: Headers;
};
export type getAccountResponseError = (getAccountResponse401) & {
  headers: Headers;
};

export type getAccountResponse = (getAccountResponseSuccess | getAccountResponseError)

export const getGetAccountUrl = () => {




  return `/account`
}

/**
 * Returns the full profile of the currently authenticated user
 * @summary Current user info
 */
export const getAccount = async ( options?: RequestInit): Promise<getAccountResponse> => {

  const res = await fetch(getGetAccountUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAccountResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAccountResponse
}



export type requestAccountDeleteResponse200 = {
  data: SuccessResponse
  status: 200
}

export type requestAccountDeleteResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type requestAccountDeleteResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type requestAccountDeleteResponseSuccess = (requestAccountDeleteResponse200) & {
  headers: Headers;
};
export type requestAccountDeleteResponseError = (requestAccountDeleteResponse401 | requestAccountDeleteResponse500) & {
  headers: Headers;
};

export type requestAccountDeleteResponse = (requestAccountDeleteResponseSuccess | requestAccountDeleteResponseError)

export const getRequestAccountDeleteUrl = () => {




  return `/account`
}

/**
 * Initiates the account-deletion flow for the authenticated user. A one-time confirmation token is sent to the user's email address. The token must then be submitted to `/account/delete-confirm` to complete the deletion.
 * @summary Request account deletion
 */
export const requestAccountDelete = async ( options?: RequestInit): Promise<requestAccountDeleteResponse> => {

  const res = await fetch(getRequestAccountDeleteUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: requestAccountDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as requestAccountDeleteResponse
}



export type confirmAccountDeleteResponse200 = {
  data: SuccessResponse
  status: 200
}

export type confirmAccountDeleteResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type confirmAccountDeleteResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type confirmAccountDeleteResponseSuccess = (confirmAccountDeleteResponse200) & {
  headers: Headers;
};
export type confirmAccountDeleteResponseError = (confirmAccountDeleteResponse422 | confirmAccountDeleteResponse500) & {
  headers: Headers;
};

export type confirmAccountDeleteResponse = (confirmAccountDeleteResponseSuccess | confirmAccountDeleteResponseError)

export const getConfirmAccountDeleteUrl = () => {




  return `/account/delete-confirm`
}

/**
 * Completes the account-deletion flow. Validates the one-time token issued by `DELETE /account` and, if valid, permanently removes the user account.
 * @summary Confirm account deletion
 */
export const confirmAccountDelete = async (accountDeleteConfirmRequest: AccountDeleteConfirmRequest, options?: RequestInit): Promise<confirmAccountDeleteResponse> => {

  const res = await fetch(getConfirmAccountDeleteUrl(),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(accountDeleteConfirmRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: confirmAccountDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as confirmAccountDeleteResponse
}



export type loginResponse200 = {
  data: AuthTokensEnvelope
  status: 200
}

export type loginResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type loginResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type loginResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse401 | loginResponse422 | loginResponse500) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {




  return `/account/login`
}

/**
 * Authenticates a user with email and password credentials. On success, returns a JWT access token that must be passed as a Bearer token on subsequent authenticated requests.
 * @summary Login
 */
export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginResponse> => {

  const res = await fetch(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponse
}



export type signupResponse201 = {
  data: UserEnvelope
  status: 201
}

export type signupResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type signupResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type signupResponseSuccess = (signupResponse201) & {
  headers: Headers;
};
export type signupResponseError = (signupResponse422 | signupResponse500) & {
  headers: Headers;
};

export type signupResponse = (signupResponseSuccess | signupResponseError)

export const getSignupUrl = () => {




  return `/account/signup`
}

/**
 * Registers a new user account with optional image upload. Returns the newly created user profile on success.
 * @summary Signup
 */
export const signup = async (signupBody: SignupRequest | SignupRequestMultipart, options?: RequestInit): Promise<signupResponse> => {

  const res = await fetch(getSignupUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(signupBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: signupResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as signupResponse
}



export type requestPasswordResetResponse200 = {
  data: SuccessResponse
  status: 200
}

export type requestPasswordResetResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type requestPasswordResetResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type requestPasswordResetResponseSuccess = (requestPasswordResetResponse200) & {
  headers: Headers;
};
export type requestPasswordResetResponseError = (requestPasswordResetResponse422 | requestPasswordResetResponse500) & {
  headers: Headers;
};

export type requestPasswordResetResponse = (requestPasswordResetResponseSuccess | requestPasswordResetResponseError)

export const getRequestPasswordResetUrl = () => {




  return `/account/reset`
}

/**
 * Initiates the password-reset flow by sending a one-time reset token to the provided email address. The token should then be submitted to `/account/reset-confirm`.
 */
export const requestPasswordReset = async (passwordResetRequest: PasswordResetRequest, options?: RequestInit): Promise<requestPasswordResetResponse> => {

  const res = await fetch(getRequestPasswordResetUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(passwordResetRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: requestPasswordResetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as requestPasswordResetResponse
}



export type confirmPasswordResetResponse200 = {
  data: SuccessResponse
  status: 200
}

export type confirmPasswordResetResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type confirmPasswordResetResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type confirmPasswordResetResponseSuccess = (confirmPasswordResetResponse200) & {
  headers: Headers;
};
export type confirmPasswordResetResponseError = (confirmPasswordResetResponse422 | confirmPasswordResetResponse500) & {
  headers: Headers;
};

export type confirmPasswordResetResponse = (confirmPasswordResetResponseSuccess | confirmPasswordResetResponseError)

export const getConfirmPasswordResetUrl = () => {




  return `/account/reset-confirm`
}

/**
 * Completes the password-reset flow. Validates the one-time reset token issued by `/account/reset` and, if valid, updates the user's password to the supplied value.
 */
export const confirmPasswordReset = async (passwordResetConfirmRequest: PasswordResetConfirmRequest, options?: RequestInit): Promise<confirmPasswordResetResponse> => {

  const res = await fetch(getConfirmPasswordResetUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(passwordResetConfirmRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: confirmPasswordResetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as confirmPasswordResetResponse
}



export type refreshTokenResponse200 = {
  data: RefreshTokenEnvelope
  status: 200
}

export type refreshTokenResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type refreshTokenResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type refreshTokenResponseSuccess = (refreshTokenResponse200) & {
  headers: Headers;
};
export type refreshTokenResponseError = (refreshTokenResponse401 | refreshTokenResponse500) & {
  headers: Headers;
};

export type refreshTokenResponse = (refreshTokenResponseSuccess | refreshTokenResponseError)

export const getRefreshTokenUrl = () => {




  return `/account/refresh`
}

/**
 * Creates a new short-lived access token using a refresh token. The refresh token can be provided as a query parameter, path parameter, or retrieved from the `jwt` cookie.
 * @summary Refresh access token
 */
export const refreshToken = async ( options?: RequestInit): Promise<refreshTokenResponse> => {

  const res = await fetch(getRefreshTokenUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: refreshTokenResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as refreshTokenResponse
}



export type refreshTokenWithPathResponse200 = {
  data: RefreshTokenEnvelope
  status: 200
}

export type refreshTokenWithPathResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type refreshTokenWithPathResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type refreshTokenWithPathResponseSuccess = (refreshTokenWithPathResponse200) & {
  headers: Headers;
};
export type refreshTokenWithPathResponseError = (refreshTokenWithPathResponse401 | refreshTokenWithPathResponse500) & {
  headers: Headers;
};

export type refreshTokenWithPathResponse = (refreshTokenWithPathResponseSuccess | refreshTokenWithPathResponseError)

export const getRefreshTokenWithPathUrl = (token: string,) => {




  return `/account/refresh/${token}`
}

/**
 * Creates a new short-lived access token using a refresh token provided in the URL path.
 * @summary Refresh access token with token in path
 */
export const refreshTokenWithPath = async (token: string, options?: RequestInit): Promise<refreshTokenWithPathResponse> => {

  const res = await fetch(getRefreshTokenWithPathUrl(token),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: refreshTokenWithPathResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as refreshTokenWithPathResponse
}



export type logoutAllResponse200 = {
  data: SuccessResponse
  status: 200
}

export type logoutAllResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type logoutAllResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type logoutAllResponseSuccess = (logoutAllResponse200) & {
  headers: Headers;
};
export type logoutAllResponseError = (logoutAllResponse401 | logoutAllResponse500) & {
  headers: Headers;
};

export type logoutAllResponse = (logoutAllResponseSuccess | logoutAllResponseError)

export const getLogoutAllUrl = () => {




  return `/account/logout-all`
}

/**
 * Logs out the authenticated user from ALL devices by removing all refresh tokens from the database and clearing authentication cookies.
 * @summary Logout from all devices
 */
export const logoutAll = async ( options?: RequestInit): Promise<logoutAllResponse> => {

  const res = await fetch(getLogoutAllUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: logoutAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as logoutAllResponse
}



export type deleteExpiredTokensResponse200 = {
  data: SuccessResponse
  status: 200
}

export type deleteExpiredTokensResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteExpiredTokensResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteExpiredTokensResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type deleteExpiredTokensResponseSuccess = (deleteExpiredTokensResponse200) & {
  headers: Headers;
};
export type deleteExpiredTokensResponseError = (deleteExpiredTokensResponse401 | deleteExpiredTokensResponse403 | deleteExpiredTokensResponse500) & {
  headers: Headers;
};

export type deleteExpiredTokensResponse = (deleteExpiredTokensResponseSuccess | deleteExpiredTokensResponseError)

export const getDeleteExpiredTokensUrl = () => {




  return `/account/tokens/expired`
}

/**
 * Removes all expired tokens (refresh, password-reset, etc.) from every user record in the database. Restricted to administrators.
 * @summary Remove expired tokens
 */
export const deleteExpiredTokens = async ( options?: RequestInit): Promise<deleteExpiredTokensResponse> => {

  const res = await fetch(getDeleteExpiredTokensUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteExpiredTokensResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteExpiredTokensResponse
}



export type listUsersResponse200 = {
  data: UsersResponseEnvelope
  status: 200
}

export type listUsersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listUsersResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type listUsersResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type listUsersResponseSuccess = (listUsersResponse200) & {
  headers: Headers;
};
export type listUsersResponseError = (listUsersResponse401 | listUsersResponse403 | listUsersResponse500) & {
  headers: Headers;
};

export type listUsersResponse = (listUsersResponseSuccess | listUsersResponseError)

export const getListUsersUrl = (params?: ListUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users?${stringifiedParams}` : `/users`
}

/**
 * Returns a paginated list of user accounts.
 * @summary List users (paginated)
 */
export const listUsers = async (params?: ListUsersParams, options?: RequestInit): Promise<listUsersResponse> => {

  const res = await fetch(getListUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listUsersResponse
}



export type createUserResponse201 = {
  data: UserEnvelope
  status: 201
}

export type createUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createUserResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createUserResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type createUserResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type createUserResponseSuccess = (createUserResponse201) & {
  headers: Headers;
};
export type createUserResponseError = (createUserResponse401 | createUserResponse403 | createUserResponse422 | createUserResponse500) & {
  headers: Headers;
};

export type createUserResponse = (createUserResponseSuccess | createUserResponseError)

export const getCreateUserUrl = () => {




  return `/users`
}

/**
 * Creates a new user account with the supplied email, username, and password. Optional image can be uploaded.
 * @summary Create user
 */
export const createUser = async (createUserBody: CreateUserRequest | CreateUserRequestMultipart, options?: RequestInit): Promise<createUserResponse> => {

  const res = await fetch(getCreateUserUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(createUserBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createUserResponse
}



export type updateUserResponse200 = {
  data: UserEnvelope
  status: 200
}

export type updateUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateUserResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateUserResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type updateUserResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type updateUserResponseSuccess = (updateUserResponse200) & {
  headers: Headers;
};
export type updateUserResponseError = (updateUserResponse401 | updateUserResponse403 | updateUserResponse422 | updateUserResponse500) & {
  headers: Headers;
};

export type updateUserResponse = (updateUserResponseSuccess | updateUserResponseError)

export const getUpdateUserUrl = () => {




  return `/users`
}

/**
 * Updates an existing user's email or password. Optional image can be uploaded.
 * @summary Edit user
 */
export const updateUser = async (updateUserBody: UpdateUserRequest | UpdateUserRequestMultipart, options?: RequestInit): Promise<updateUserResponse> => {

  const res = await fetch(getUpdateUserUrl(),
  {
    ...options,
    method: 'PUT'
    ,
    body: JSON.stringify(updateUserBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateUserResponse
}



export type deleteUserResponse200 = {
  data: SuccessResponse
  status: 200
}

export type deleteUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteUserResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteUserResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteUserResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type deleteUserResponseSuccess = (deleteUserResponse200) & {
  headers: Headers;
};
export type deleteUserResponseError = (deleteUserResponse401 | deleteUserResponse403 | deleteUserResponse404 | deleteUserResponse500) & {
  headers: Headers;
};

export type deleteUserResponse = (deleteUserResponseSuccess | deleteUserResponseError)

export const getDeleteUserUrl = () => {




  return `/users`
}

/**
 * Deletes the user identified by the `id` field in the request body. Set `hardDelete` to `true` to permanently remove the record.
 * @summary Delete user
 */
export const deleteUser = async (deleteUserRequest: DeleteUserRequest, options?: RequestInit): Promise<deleteUserResponse> => {

  const res = await fetch(getDeleteUserUrl(),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deleteUserRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteUserResponse
}



export type getUserByIdResponse200 = {
  data: UserEnvelope
  status: 200
}

export type getUserByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getUserByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getUserByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getUserByIdResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getUserByIdResponseSuccess = (getUserByIdResponse200) & {
  headers: Headers;
};
export type getUserByIdResponseError = (getUserByIdResponse401 | getUserByIdResponse403 | getUserByIdResponse404 | getUserByIdResponse500) & {
  headers: Headers;
};

export type getUserByIdResponse = (getUserByIdResponseSuccess | getUserByIdResponseError)

export const getGetUserByIdUrl = (id: string,) => {




  return `/users/${id}`
}

/**
 * Returns the full profile of the user identified by `{id}`. Functionally equivalent to `GET /users?id={id}`.
 * @summary User details
 */
export const getUserById = async (id: string, options?: RequestInit): Promise<getUserByIdResponse> => {

  const res = await fetch(getGetUserByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserByIdResponse
}



export type updateUserByIdResponse200 = {
  data: UserEnvelope
  status: 200
}

export type updateUserByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateUserByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateUserByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateUserByIdResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type updateUserByIdResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type updateUserByIdResponseSuccess = (updateUserByIdResponse200) & {
  headers: Headers;
};
export type updateUserByIdResponseError = (updateUserByIdResponse401 | updateUserByIdResponse403 | updateUserByIdResponse404 | updateUserByIdResponse422 | updateUserByIdResponse500) & {
  headers: Headers;
};

export type updateUserByIdResponse = (updateUserByIdResponseSuccess | updateUserByIdResponseError)

export const getUpdateUserByIdUrl = (id: string,) => {




  return `/users/${id}`
}

/**
 * Updates the email or password of the user identified by `{id}` in the path. Optional image can be uploaded.
 * @summary Edit user
 */
export const updateUserById = async (id: string,
    updateUserByIdBody: UpdateUserByIdRequest | UpdateUserByIdRequestMultipart, options?: RequestInit): Promise<updateUserByIdResponse> => {

  const res = await fetch(getUpdateUserByIdUrl(id),
  {
    ...options,
    method: 'PUT'
    ,
    body: JSON.stringify(updateUserByIdBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateUserByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateUserByIdResponse
}



export type deleteUserByIdResponse200 = {
  data: SuccessResponse
  status: 200
}

export type deleteUserByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteUserByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteUserByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteUserByIdResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type deleteUserByIdResponseSuccess = (deleteUserByIdResponse200) & {
  headers: Headers;
};
export type deleteUserByIdResponseError = (deleteUserByIdResponse401 | deleteUserByIdResponse403 | deleteUserByIdResponse404 | deleteUserByIdResponse500) & {
  headers: Headers;
};

export type deleteUserByIdResponse = (deleteUserByIdResponseSuccess | deleteUserByIdResponseError)

export const getDeleteUserByIdUrl = (id: string,
    params?: DeleteUserByIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users/${id}?${stringifiedParams}` : `/users/${id}`
}

/**
 * Deletes the user identified by `{id}` in the path. Pass the `hardDelete` query parameter as `true` to permanently remove the record. Functionally equivalent to `DELETE /users`.
 * @summary Delete user
 */
export const deleteUserById = async (id: string,
    params?: DeleteUserByIdParams, options?: RequestInit): Promise<deleteUserByIdResponse> => {

  const res = await fetch(getDeleteUserByIdUrl(id,params),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUserByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteUserByIdResponse
}



export type searchUsersResponse200 = {
  data: UsersResponseEnvelope
  status: 200
}

export type searchUsersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type searchUsersResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type searchUsersResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type searchUsersResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type searchUsersResponseSuccess = (searchUsersResponse200) & {
  headers: Headers;
};
export type searchUsersResponseError = (searchUsersResponse401 | searchUsersResponse403 | searchUsersResponse422 | searchUsersResponse500) & {
  headers: Headers;
};

export type searchUsersResponse = (searchUsersResponseSuccess | searchUsersResponseError)

export const getSearchUsersUrl = () => {




  return `/users/search`
}

/**
 * Searches and filters users via a JSON request body. Functionally equivalent to `GET /users` with query parameters
 * @summary Search users (DTO-friendly)
 */
export const searchUsers = async (searchUsersRequest: SearchUsersRequest, options?: RequestInit): Promise<searchUsersResponse> => {

  const res = await fetch(getSearchUsersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(searchUsersRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchUsersResponse
}



export type createFeedbackRequestResponse201 = {
  data: FeedbackRequestEnvelope
  status: 201
}

export type createFeedbackRequestResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type createFeedbackRequestResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type createFeedbackRequestResponseSuccess = (createFeedbackRequestResponse201) & {
  headers: Headers;
};
export type createFeedbackRequestResponseError = (createFeedbackRequestResponse422 | createFeedbackRequestResponse500) & {
  headers: Headers;
};

export type createFeedbackRequestResponse = (createFeedbackRequestResponseSuccess | createFeedbackRequestResponseError)

export const getCreateFeedbackRequestUrl = () => {




  return `/feedback/contact`
}

/**
 * Creates a user feedback/contact request and notifies admins via email.
 * @summary Submit contact request
 */
export const createFeedbackRequest = async (createFeedbackRequest: CreateFeedbackRequest, options?: RequestInit): Promise<createFeedbackRequestResponse> => {

  const res = await fetch(getCreateFeedbackRequestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createFeedbackRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createFeedbackRequestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createFeedbackRequestResponse
}



export type listFeedbackRequestsResponse200 = {
  data: FeedbackRequestsResponseEnvelope
  status: 200
}

export type listFeedbackRequestsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listFeedbackRequestsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type listFeedbackRequestsResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type listFeedbackRequestsResponseSuccess = (listFeedbackRequestsResponse200) & {
  headers: Headers;
};
export type listFeedbackRequestsResponseError = (listFeedbackRequestsResponse401 | listFeedbackRequestsResponse403 | listFeedbackRequestsResponse500) & {
  headers: Headers;
};

export type listFeedbackRequestsResponse = (listFeedbackRequestsResponseSuccess | listFeedbackRequestsResponseError)

export const getListFeedbackRequestsUrl = () => {




  return `/feedback`
}

/**
 * Returns feedback/contact requests for admin review.
 * @summary List feedback requests
 */
export const listFeedbackRequests = async (searchFeedbackRequestsRequest?: SearchFeedbackRequestsRequest, options?: RequestInit): Promise<listFeedbackRequestsResponse> => {

  const res = await fetch(getListFeedbackRequestsUrl(),
  {
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(searchFeedbackRequestsRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listFeedbackRequestsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listFeedbackRequestsResponse
}



export type updateFeedbackRequestStatusResponse200 = {
  data: FeedbackRequestEnvelope
  status: 200
}

export type updateFeedbackRequestStatusResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateFeedbackRequestStatusResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateFeedbackRequestStatusResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateFeedbackRequestStatusResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type updateFeedbackRequestStatusResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type updateFeedbackRequestStatusResponseSuccess = (updateFeedbackRequestStatusResponse200) & {
  headers: Headers;
};
export type updateFeedbackRequestStatusResponseError = (updateFeedbackRequestStatusResponse401 | updateFeedbackRequestStatusResponse403 | updateFeedbackRequestStatusResponse404 | updateFeedbackRequestStatusResponse422 | updateFeedbackRequestStatusResponse500) & {
  headers: Headers;
};

export type updateFeedbackRequestStatusResponse = (updateFeedbackRequestStatusResponseSuccess | updateFeedbackRequestStatusResponseError)

export const getUpdateFeedbackRequestStatusUrl = (id: string,) => {




  return `/feedback/${id}`
}

/**
 * Updates status/notes of a feedback request.
 * @summary Update feedback request status
 */
export const updateFeedbackRequestStatus = async (id: string,
    updateFeedbackRequestStatusRequest: UpdateFeedbackRequestStatusRequest, options?: RequestInit): Promise<updateFeedbackRequestStatusResponse> => {

  const res = await fetch(getUpdateFeedbackRequestStatusUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateFeedbackRequestStatusRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateFeedbackRequestStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateFeedbackRequestStatusResponse
}



export type listProductsResponse200 = {
  data: ProductsResponseEnvelope
  status: 200
}

export type listProductsResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type listProductsResponseSuccess = (listProductsResponse200) & {
  headers: Headers;
};
export type listProductsResponseError = (listProductsResponse500) & {
  headers: Headers;
};

export type listProductsResponse = (listProductsResponseSuccess | listProductsResponseError)

export const getListProductsUrl = (params?: ListProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/products?${stringifiedParams}` : `/products`
}

/**
 * Returns a paginated list of products.
 * @summary List products (paginated)
 */
export const listProducts = async (params?: ListProductsParams, options?: RequestInit): Promise<listProductsResponse> => {

  const res = await fetch(getListProductsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listProductsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listProductsResponse
}



export type createProductResponse201 = {
  data: ProductEnvelope
  status: 201
}

export type createProductResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createProductResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createProductResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type createProductResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type createProductResponseSuccess = (createProductResponse201) & {
  headers: Headers;
};
export type createProductResponseError = (createProductResponse401 | createProductResponse403 | createProductResponse422 | createProductResponse500) & {
  headers: Headers;
};

export type createProductResponse = (createProductResponseSuccess | createProductResponseError)

export const getCreateProductUrl = () => {




  return `/products`
}

/**
 * Creates a new product with optional image upload
 * @summary Create product
 */
export const createProduct = async (createProductBody: CreateProductRequest | CreateProductRequestMultipart, options?: RequestInit): Promise<createProductResponse> => {

  const res = await fetch(getCreateProductUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(createProductBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createProductResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createProductResponse
}



export type updateProductResponse200 = {
  data: ProductEnvelope
  status: 200
}

export type updateProductResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateProductResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateProductResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateProductResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type updateProductResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type updateProductResponseSuccess = (updateProductResponse200) & {
  headers: Headers;
};
export type updateProductResponseError = (updateProductResponse401 | updateProductResponse403 | updateProductResponse404 | updateProductResponse422 | updateProductResponse500) & {
  headers: Headers;
};

export type updateProductResponse = (updateProductResponseSuccess | updateProductResponseError)

export const getUpdateProductUrl = () => {




  return `/products`
}

/**
 * Updates an existing product with optional image upload
 * @summary Edit product
 */
export const updateProduct = async (updateProductBody: UpdateProductRequest | UpdateProductRequestMultipart, options?: RequestInit): Promise<updateProductResponse> => {

  const res = await fetch(getUpdateProductUrl(),
  {
    ...options,
    method: 'PUT'
    ,
    body: JSON.stringify(updateProductBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateProductResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateProductResponse
}



export type deleteProductResponse200 = {
  data: SuccessResponse
  status: 200
}

export type deleteProductResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteProductResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteProductResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteProductResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type deleteProductResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type deleteProductResponseSuccess = (deleteProductResponse200) & {
  headers: Headers;
};
export type deleteProductResponseError = (deleteProductResponse401 | deleteProductResponse403 | deleteProductResponse404 | deleteProductResponse422 | deleteProductResponse500) & {
  headers: Headers;
};

export type deleteProductResponse = (deleteProductResponseSuccess | deleteProductResponseError)

export const getDeleteProductUrl = () => {




  return `/products`
}

/**
 * Deletes the product identified by the `id` field in the request body. Set `hardDelete` to `true` to permanently remove the record
 * @summary Delete product
 */
export const deleteProduct = async (deleteProductRequest: DeleteProductRequest, options?: RequestInit): Promise<deleteProductResponse> => {

  const res = await fetch(getDeleteProductUrl(),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deleteProductRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteProductResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteProductResponse
}



export type getProductByIdResponse200 = {
  data: ProductEnvelope
  status: 200
}

export type getProductByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getProductByIdResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getProductByIdResponseSuccess = (getProductByIdResponse200) & {
  headers: Headers;
};
export type getProductByIdResponseError = (getProductByIdResponse404 | getProductByIdResponse500) & {
  headers: Headers;
};

export type getProductByIdResponse = (getProductByIdResponseSuccess | getProductByIdResponseError)

export const getGetProductByIdUrl = (id: string,) => {




  return `/products/${id}`
}

/**
 * Returns the full details of the product identified by `{id}`. Functionally equivalent to `GET /products?id={id}`.
 * @summary Product details
 */
export const getProductById = async (id: string, options?: RequestInit): Promise<getProductByIdResponse> => {

  const res = await fetch(getGetProductByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getProductByIdResponse
}



export type updateProductByIdResponse200 = {
  data: ProductEnvelope
  status: 200
}

export type updateProductByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateProductByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateProductByIdResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type updateProductByIdResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type updateProductByIdResponseSuccess = (updateProductByIdResponse200) & {
  headers: Headers;
};
export type updateProductByIdResponseError = (updateProductByIdResponse401 | updateProductByIdResponse404 | updateProductByIdResponse422 | updateProductByIdResponse500) & {
  headers: Headers;
};

export type updateProductByIdResponse = (updateProductByIdResponseSuccess | updateProductByIdResponseError)

export const getUpdateProductByIdUrl = (id: string,) => {




  return `/products/${id}`
}

/**
 * Updates the product identified by `{id}` in the path with optional image upload. Functionally equivalent to `PUT /products` with the id in the body.
 * @summary Edit product
 */
export const updateProductById = async (id: string,
    updateProductByIdBody: UpdateProductByIdRequest | UpdateProductByIdRequestMultipart, options?: RequestInit): Promise<updateProductByIdResponse> => {

  const res = await fetch(getUpdateProductByIdUrl(id),
  {
    ...options,
    method: 'PUT'
    ,
    body: JSON.stringify(updateProductByIdBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateProductByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateProductByIdResponse
}



export type deleteProductByIdResponse200 = {
  data: SuccessResponse
  status: 200
}

export type deleteProductByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteProductByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteProductByIdResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type deleteProductByIdResponseSuccess = (deleteProductByIdResponse200) & {
  headers: Headers;
};
export type deleteProductByIdResponseError = (deleteProductByIdResponse401 | deleteProductByIdResponse404 | deleteProductByIdResponse500) & {
  headers: Headers;
};

export type deleteProductByIdResponse = (deleteProductByIdResponseSuccess | deleteProductByIdResponseError)

export const getDeleteProductByIdUrl = (id: string,
    params?: DeleteProductByIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/products/${id}?${stringifiedParams}` : `/products/${id}`
}

/**
 * Deletes the product identified by `{id}` in the path. Pass the `hardDelete` query parameter as `true` to permanently remove the record. Functionally equivalent to `DELETE /products`.
 * @summary Delete product
 */
export const deleteProductById = async (id: string,
    params?: DeleteProductByIdParams, options?: RequestInit): Promise<deleteProductByIdResponse> => {

  const res = await fetch(getDeleteProductByIdUrl(id,params),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteProductByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteProductByIdResponse
}



export type searchProductsResponse200 = {
  data: ProductsResponseEnvelope
  status: 200
}

export type searchProductsResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type searchProductsResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type searchProductsResponseSuccess = (searchProductsResponse200) & {
  headers: Headers;
};
export type searchProductsResponseError = (searchProductsResponse422 | searchProductsResponse500) & {
  headers: Headers;
};

export type searchProductsResponse = (searchProductsResponseSuccess | searchProductsResponseError)

export const getSearchProductsUrl = () => {




  return `/products/search`
}

/**
 * Searches and filters products via a JSON request body. Functionally equivalent to `GET /products` with query parameters.
 * @summary Search products (DTO-friendly)
 */
export const searchProducts = async (searchProductsRequest: SearchProductsRequest, options?: RequestInit): Promise<searchProductsResponse> => {

  const res = await fetch(getSearchProductsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(searchProductsRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchProductsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchProductsResponse
}



export type getCartResponse200 = {
  data: CartResponseEnvelope
  status: 200
}

export type getCartResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getCartResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getCartResponseSuccess = (getCartResponse200) & {
  headers: Headers;
};
export type getCartResponseError = (getCartResponse401 | getCartResponse500) & {
  headers: Headers;
};

export type getCartResponse = (getCartResponseSuccess | getCartResponseError)

export const getGetCartUrl = () => {




  return `/cart`
}

/**
 * Returns all items currently in the authenticated user's cart along with a computed summary
 * @summary Get cart
 */
export const getCart = async ( options?: RequestInit): Promise<getCartResponse> => {

  const res = await fetch(getGetCartUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCartResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCartResponse
}



export type upsertCartItemResponse200 = {
  data: CartResponseEnvelope
  status: 200
}

export type upsertCartItemResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type upsertCartItemResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type upsertCartItemResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type upsertCartItemResponseSuccess = (upsertCartItemResponse200) & {
  headers: Headers;
};
export type upsertCartItemResponseError = (upsertCartItemResponse401 | upsertCartItemResponse422 | upsertCartItemResponse500) & {
  headers: Headers;
};

export type upsertCartItemResponse = (upsertCartItemResponseSuccess | upsertCartItemResponseError)

export const getUpsertCartItemUrl = () => {




  return `/cart`
}

/**
 * Adds or edit a product to the authenticated user's cart. Returns the updated cart.
 * @summary Add/Edit cart item
 */
export const upsertCartItem = async (upsertCartItemRequest: UpsertCartItemRequest, options?: RequestInit): Promise<upsertCartItemResponse> => {

  const res = await fetch(getUpsertCartItemUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertCartItemRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: upsertCartItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as upsertCartItemResponse
}



export type clearCartResponse200 = {
  data: CartResponseEnvelope
  status: 200
}

export type clearCartResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type clearCartResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type clearCartResponseSuccess = (clearCartResponse200) & {
  headers: Headers;
};
export type clearCartResponseError = (clearCartResponse401 | clearCartResponse500) & {
  headers: Headers;
};

export type clearCartResponse = (clearCartResponseSuccess | clearCartResponseError)

export const getClearCartUrl = () => {




  return `/cart`
}

/**
 * Clear cart or, ir productId is set, removes a specific product from the authenticated user's cart. Returns the updated cart (can be empty)
 * @summary Empty cart or, if productId is set, remove target cart item
 */
export const clearCart = async (removeCartItemRequest?: RemoveCartItemRequest, options?: RequestInit): Promise<clearCartResponse> => {

  const res = await fetch(getClearCartUrl(),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(removeCartItemRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: clearCartResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clearCartResponse
}



export type updateCartItemByIdResponse200 = {
  data: CartResponseEnvelope
  status: 200
}

export type updateCartItemByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateCartItemByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateCartItemByIdResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type updateCartItemByIdResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type updateCartItemByIdResponseSuccess = (updateCartItemByIdResponse200) & {
  headers: Headers;
};
export type updateCartItemByIdResponseError = (updateCartItemByIdResponse401 | updateCartItemByIdResponse404 | updateCartItemByIdResponse422 | updateCartItemByIdResponse500) & {
  headers: Headers;
};

export type updateCartItemByIdResponse = (updateCartItemByIdResponseSuccess | updateCartItemByIdResponseError)

export const getUpdateCartItemByIdUrl = (productId: string,) => {




  return `/cart/${productId}`
}

/**
 * Sets the quantity of the cart line for the product identified by `{productId}` in the path. Functionally equivalent to `POST /cart`. Returns the updated cart.
 * @summary Set cart item quantity
 */
export const updateCartItemById = async (productId: string,
    updateCartItemByIdRequest: UpdateCartItemByIdRequest, options?: RequestInit): Promise<updateCartItemByIdResponse> => {

  const res = await fetch(getUpdateCartItemByIdUrl(productId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCartItemByIdRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateCartItemByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateCartItemByIdResponse
}



export type removeCartItemResponse200 = {
  data: CartResponseEnvelope
  status: 200
}

export type removeCartItemResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type removeCartItemResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type removeCartItemResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type removeCartItemResponseSuccess = (removeCartItemResponse200) & {
  headers: Headers;
};
export type removeCartItemResponseError = (removeCartItemResponse401 | removeCartItemResponse404 | removeCartItemResponse500) & {
  headers: Headers;
};

export type removeCartItemResponse = (removeCartItemResponseSuccess | removeCartItemResponseError)

export const getRemoveCartItemUrl = (productId: string,) => {




  return `/cart/${productId}`
}

/**
 * Removes the cart line for the product identified by `{productId}` in the path from the authenticated user's cart. Returns the updated cart.
 * @summary Remove item from cart
 */
export const removeCartItem = async (productId: string, options?: RequestInit): Promise<removeCartItemResponse> => {

  const res = await fetch(getRemoveCartItemUrl(productId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: removeCartItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeCartItemResponse
}



export type getCartSummaryResponse200 = {
  data: CartSummaryResponseEnvelope
  status: 200
}

export type getCartSummaryResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getCartSummaryResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getCartSummaryResponseSuccess = (getCartSummaryResponse200) & {
  headers: Headers;
};
export type getCartSummaryResponseError = (getCartSummaryResponse401 | getCartSummaryResponse500) & {
  headers: Headers;
};

export type getCartSummaryResponse = (getCartSummaryResponseSuccess | getCartSummaryResponseError)

export const getGetCartSummaryUrl = () => {




  return `/cart/summary`
}

/**
 * Returns a lightweight summary of the authenticated user's cart.
 * @summary Get cart summary
 */
export const getCartSummary = async ( options?: RequestInit): Promise<getCartSummaryResponse> => {

  const res = await fetch(getGetCartSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCartSummaryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCartSummaryResponse
}



export type checkoutResponse201 = {
  data: CheckoutResponseEnvelope
  status: 201
}

export type checkoutResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type checkoutResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type checkoutResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type checkoutResponseSuccess = (checkoutResponse201) & {
  headers: Headers;
};
export type checkoutResponseError = (checkoutResponse401 | checkoutResponse422 | checkoutResponse500) & {
  headers: Headers;
};

export type checkoutResponse = (checkoutResponseSuccess | checkoutResponseError)

export const getCheckoutUrl = () => {




  return `/cart/checkout`
}

/**
 * Converts the authenticated user's current cart into a new order. The cart is cleared upon success. An optional email address and order notes can be supplied in the request body. Returns the created order.
 * @summary Checkout (place order from cart)
 */
export const checkout = async (checkoutRequest?: CheckoutRequest, options?: RequestInit): Promise<checkoutResponse> => {

  const res = await fetch(getCheckoutUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(checkoutRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: checkoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as checkoutResponse
}



export type listOrdersResponse200 = {
  data: OrdersResponseEnvelope
  status: 200
}

export type listOrdersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listOrdersResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type listOrdersResponseSuccess = (listOrdersResponse200) & {
  headers: Headers;
};
export type listOrdersResponseError = (listOrdersResponse401 | listOrdersResponse500) & {
  headers: Headers;
};

export type listOrdersResponse = (listOrdersResponseSuccess | listOrdersResponseError)

export const getListOrdersUrl = (params?: ListOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/orders?${stringifiedParams}` : `/orders`
}

/**
 * Returns a paginated list of orders.
 * Non-admin users are automatically scoped to their own orders; the `userId` filter is ignored for non-admin callers.
 * @summary List orders (paginated)
 */
export const listOrders = async (params?: ListOrdersParams, options?: RequestInit): Promise<listOrdersResponse> => {

  const res = await fetch(getListOrdersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listOrdersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listOrdersResponse
}



export type createOrderResponse201 = {
  data: OrderEnvelope
  status: 201
}

export type createOrderResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createOrderResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createOrderResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type createOrderResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type createOrderResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type createOrderResponseSuccess = (createOrderResponse201) & {
  headers: Headers;
};
export type createOrderResponseError = (createOrderResponse401 | createOrderResponse403 | createOrderResponse404 | createOrderResponse422 | createOrderResponse500) & {
  headers: Headers;
};

export type createOrderResponse = (createOrderResponseSuccess | createOrderResponseError)

export const getCreateOrderUrl = () => {




  return `/orders`
}

/**
 * Creates a new order directly from the supplied payload.
 * @summary Create order
 */
export const createOrder = async (createOrderRequest: CreateOrderRequest, options?: RequestInit): Promise<createOrderResponse> => {

  const res = await fetch(getCreateOrderUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrderRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createOrderResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createOrderResponse
}



export type updateOrderResponse200 = {
  data: OrderEnvelope
  status: 200
}

export type updateOrderResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateOrderResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateOrderResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateOrderResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type updateOrderResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type updateOrderResponseSuccess = (updateOrderResponse200) & {
  headers: Headers;
};
export type updateOrderResponseError = (updateOrderResponse401 | updateOrderResponse403 | updateOrderResponse404 | updateOrderResponse422 | updateOrderResponse500) & {
  headers: Headers;
};

export type updateOrderResponse = (updateOrderResponseSuccess | updateOrderResponseError)

export const getUpdateOrderUrl = () => {




  return `/orders`
}

/**
 * Updates an existing order identified by id in the request body.
 * @summary Update order
 */
export const updateOrder = async (updateOrderRequest: UpdateOrderRequest, options?: RequestInit): Promise<updateOrderResponse> => {

  const res = await fetch(getUpdateOrderUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateOrderRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateOrderResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateOrderResponse
}



export type deleteOrderResponse200 = {
  data: SuccessResponse
  status: 200
}

export type deleteOrderResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteOrderResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteOrderResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteOrderResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type deleteOrderResponseSuccess = (deleteOrderResponse200) & {
  headers: Headers;
};
export type deleteOrderResponseError = (deleteOrderResponse401 | deleteOrderResponse403 | deleteOrderResponse404 | deleteOrderResponse500) & {
  headers: Headers;
};

export type deleteOrderResponse = (deleteOrderResponseSuccess | deleteOrderResponseError)

export const getDeleteOrderUrl = () => {




  return `/orders`
}

/**
 * Permanently removes the order identified by id.
 * @summary Delete order
 */
export const deleteOrder = async (deleteOrderRequest: DeleteOrderRequest, options?: RequestInit): Promise<deleteOrderResponse> => {

  const res = await fetch(getDeleteOrderUrl(),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deleteOrderRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteOrderResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteOrderResponse
}



export type searchOrdersResponse200 = {
  data: OrdersResponseEnvelope
  status: 200
}

export type searchOrdersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type searchOrdersResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type searchOrdersResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type searchOrdersResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type searchOrdersResponseSuccess = (searchOrdersResponse200) & {
  headers: Headers;
};
export type searchOrdersResponseError = (searchOrdersResponse401 | searchOrdersResponse403 | searchOrdersResponse422 | searchOrdersResponse500) & {
  headers: Headers;
};

export type searchOrdersResponse = (searchOrdersResponseSuccess | searchOrdersResponseError)

export const getSearchOrdersUrl = () => {




  return `/orders/search`
}

/**
 * Searches and filters orders via a JSON request body. Functionally equivalent to `GET /orders`.
 * Non-admin users are automatically scoped to their own orders; the `userId` filter is ignored for non-admin callers.
 * @summary Search orders (DTO-friendly)
 */
export const searchOrders = async (searchOrdersRequest: SearchOrdersRequest, options?: RequestInit): Promise<searchOrdersResponse> => {

  const res = await fetch(getSearchOrdersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(searchOrdersRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchOrdersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchOrdersResponse
}



export type getOrderByIdResponse200 = {
  data: OrderEnvelope
  status: 200
}

export type getOrderByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getOrderByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getOrderByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getOrderByIdResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getOrderByIdResponseSuccess = (getOrderByIdResponse200) & {
  headers: Headers;
};
export type getOrderByIdResponseError = (getOrderByIdResponse401 | getOrderByIdResponse403 | getOrderByIdResponse404 | getOrderByIdResponse500) & {
  headers: Headers;
};

export type getOrderByIdResponse = (getOrderByIdResponseSuccess | getOrderByIdResponseError)

export const getGetOrderByIdUrl = (id: string,) => {




  return `/orders/${id}`
}

/**
 * Returns the full details of the order identified by `{id}`. Functionally equivalent to `GET /orders?id={id}`.
 * @summary Order details
 */
export const getOrderById = async (id: string, options?: RequestInit): Promise<getOrderByIdResponse> => {

  const res = await fetch(getGetOrderByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getOrderByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOrderByIdResponse
}



export type updateOrderByIdResponse200 = {
  data: OrderEnvelope
  status: 200
}

export type updateOrderByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateOrderByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateOrderByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateOrderByIdResponse422 = {
  data: ValidationErrorResponse
  status: 422
}

export type updateOrderByIdResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type updateOrderByIdResponseSuccess = (updateOrderByIdResponse200) & {
  headers: Headers;
};
export type updateOrderByIdResponseError = (updateOrderByIdResponse401 | updateOrderByIdResponse403 | updateOrderByIdResponse404 | updateOrderByIdResponse422 | updateOrderByIdResponse500) & {
  headers: Headers;
};

export type updateOrderByIdResponse = (updateOrderByIdResponseSuccess | updateOrderByIdResponseError)

export const getUpdateOrderByIdUrl = (id: string,) => {




  return `/orders/${id}`
}

/**
 * Updates the order identified by `{id}` in the path.
 * @summary Edit order
 */
export const updateOrderById = async (id: string,
    updateOrderByIdRequest: UpdateOrderByIdRequest, options?: RequestInit): Promise<updateOrderByIdResponse> => {

  const res = await fetch(getUpdateOrderByIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateOrderByIdRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateOrderByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateOrderByIdResponse
}



export type deleteOrderByIdResponse200 = {
  data: SuccessResponse
  status: 200
}

export type deleteOrderByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteOrderByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteOrderByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteOrderByIdResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type deleteOrderByIdResponseSuccess = (deleteOrderByIdResponse200) & {
  headers: Headers;
};
export type deleteOrderByIdResponseError = (deleteOrderByIdResponse401 | deleteOrderByIdResponse403 | deleteOrderByIdResponse404 | deleteOrderByIdResponse500) & {
  headers: Headers;
};

export type deleteOrderByIdResponse = (deleteOrderByIdResponseSuccess | deleteOrderByIdResponseError)

export const getDeleteOrderByIdUrl = (id: string,) => {




  return `/orders/${id}`
}

/**
 * Permanently removes the order identified by `id`.
 * @summary Delete order
 */
export const deleteOrderById = async (id: string, options?: RequestInit): Promise<deleteOrderByIdResponse> => {

  const res = await fetch(getDeleteOrderByIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteOrderByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteOrderByIdResponse
}



export type getOrderInvoiceResponse200 = {
  data: Blob
  status: 200
}

export type getOrderInvoiceResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getOrderInvoiceResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getOrderInvoiceResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getOrderInvoiceResponseSuccess = (getOrderInvoiceResponse200) & {
  headers: Headers;
};
export type getOrderInvoiceResponseError = (getOrderInvoiceResponse401 | getOrderInvoiceResponse404 | getOrderInvoiceResponse500) & {
  headers: Headers;
};

export type getOrderInvoiceResponse = (getOrderInvoiceResponseSuccess | getOrderInvoiceResponseError)

export const getGetOrderInvoiceUrl = (id: string,) => {




  return `/orders/${id}/invoice`
}

/**
 * Generates and returns the invoice for the order identified by `{id}` as a binary PDF file. The client should save or stream the response with an appropriate `Content-Disposition` header.
 * @summary Download order invoice (PDF)
 */
export const getOrderInvoice = async (id: string, options?: RequestInit): Promise<getOrderInvoiceResponse> => {

  const res = await fetch(getGetOrderInvoiceUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
  const data: getOrderInvoiceResponse['data'] = body as getOrderInvoiceResponse['data']
  return { data, status: res.status, headers: res.headers } as getOrderInvoiceResponse
}
